<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.14 — Executive Business Scorecard */
function tuff_beatz_v1414_clamp($n){return max(0,min(100,(float)$n));}
function tuff_beatz_v1414_scorecard(){
 $forecast=function_exists('tuff_beatz_v1410_forecast')?tuff_beatz_v1410_forecast():array();
 $operating=function_exists('tuff_beatz_v1412_operating_view')?tuff_beatz_v1412_operating_view():array();
 $trends=function_exists('tuff_beatz_v1413_trends')?tuff_beatz_v1413_trends(12):array();
 $pipeline=function_exists('tuff_beatz_v14_pipeline_summary')?tuff_beatz_v14_pipeline_summary():array();
 $business=function_exists('tuff_beatz_v14_project_business_summary')?tuff_beatz_v14_project_business_summary():array();
 $goal=(float)($forecast['goal']??0);$goal_score=$goal>0?tuff_beatz_v1414_clamp(((float)($forecast['month_collected']??0)/$goal)*100):50;
 $pipeline_value=(float)($pipeline['weighted_value']??0);$receivable=(float)($business['receivable']??0);$pipeline_score=$goal>0?tuff_beatz_v1414_clamp((($pipeline_value+$receivable)/$goal)*100):($pipeline_value+$receivable>0?70:35);
 $margin=$operating['operating_margin']??null;$margin_score=$margin===null?45:tuff_beatz_v1414_clamp(((float)$margin+10)*1.5);
 $coverage=tuff_beatz_v1414_clamp((float)($operating['cost_coverage']??0));
 $growth=$trends['revenue_change']??null;$growth_score=$growth===null?50:tuff_beatz_v1414_clamp(50+((float)$growth*1.5));
 $over=(float)($operating['overhead']??0);$covered=(float)($operating['covered_collected']??0);$overhead_score=$covered>0?tuff_beatz_v1414_clamp(100-(($over/$covered)*100)):($over>0?25:60);
 $scores=array('revenue'=>$goal_score,'pipeline'=>$pipeline_score,'margin'=>$margin_score,'cost_data'=>$coverage,'growth'=>$growth_score,'overhead'=>$overhead_score);
 $weights=array('revenue'=>.22,'pipeline'=>.18,'margin'=>.20,'cost_data'=>.15,'growth'=>.15,'overhead'=>.10);$total=0;foreach($scores as $k=>$v)$total+=$v*$weights[$k];$total=round($total);
 $grade=$total>=90?'A+':($total>=80?'A':($total>=70?'B':($total>=60?'C':($total>=50?'D':'E'))));$status=$total>=80?'STRONG':($total>=65?'STABLE':($total>=50?'WATCH':'ACTION REQUIRED'));
 $signals=array();if($goal>0&&$goal_score<70)$signals[]='Collections are behind the configured monthly revenue target.';if($pipeline_score<50)$signals[]='Weighted pipeline and receivables provide limited forward coverage.';if($margin!==null&&$margin<20)$signals[]='Covered operating margin is below the 20% management reference.';if($coverage<70)$signals[]='Cost-basis coverage is incomplete, reducing profitability confidence.';if($growth!==null&&$growth<0)$signals[]='Collections declined versus the previous month.';if($covered>0&&$over/$covered>.35)$signals[]='Entered overhead exceeds 35% of cost-covered collections.';if(!$signals)$signals[]='No major scorecard exception is currently detected from recorded Business OS data.';
 return array('score'=>$total,'grade'=>$grade,'status'=>$status,'scores'=>$scores,'signals'=>$signals,'forecast'=>$forecast,'operating'=>$operating,'trends'=>$trends,'pipeline'=>$pipeline,'business'=>$business);
}
function tuff_beatz_v1414_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$x=tuff_beatz_v1414_scorecard();$labels=array('revenue'=>'Revenue Target','pipeline'=>'Pipeline Coverage','margin'=>'Operating Margin','cost_data'=>'Cost Data Quality','growth'=>'Revenue Momentum','overhead'=>'Overhead Efficiency');ob_start();?><section class="tb-v1414-scorecard"><div class="tb-v1414-head"><div><small>EXECUTIVE SCORECARD • V14.14</small><h3>Business Performance Index</h3><p>A weighted management score combining collections, pipeline coverage, operating performance, data completeness, momentum and overhead efficiency.</p></div><div class="tb-v1414-score"><strong><?php echo esc_html((string)$x['score']);?></strong><span>/ 100</span><b><?php echo esc_html($x['grade'].' • '.$x['status']);?></b></div></div><div class="tb-v1414-bars"><?php foreach($x['scores'] as $k=>$v):?><article><div><span><?php echo esc_html($labels[$k]);?></span><b><?php echo esc_html(number_format((float)$v,0));?></b></div><i><em style="width:<?php echo esc_attr((string)tuff_beatz_v1414_clamp($v));?>%"></em></i></article><?php endforeach;?></div><div class="tb-v1414-signals"><small>EXECUTIVE SIGNALS</small><?php foreach($x['signals'] as $signal):?><p><?php echo esc_html($signal);?></p><?php endforeach;?></div><p class="tb-v1414-foot">This score is an internal decision-support index, not a credit score, valuation, audit opinion or formal accounting metric. Scores depend on the completeness of Business OS records.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var anchor=document.querySelector('.tb-v1413-trends')||document.querySelector('.tb-v1412-overhead');if(!anchor||document.querySelector('.tb-v1414-scorecard'))return;var box=document.createElement('div');box.innerHTML=<?php echo wp_json_encode($html);?>;anchor.insertAdjacentElement('afterend',box.firstElementChild);var eye=document.querySelector('.tb-biz-hero .eyebrow');if(eye)eye.textContent='TUFF BEATZ • STUDIO BUSINESS OS V14.14';});</script><?php }
add_action('wp_footer','tuff_beatz_v1414_panel',14);
function tuff_beatz_v1414_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v1414-scorecard{margin-top:18px;padding:20px;border:1px solid rgba(216,180,90,.16);border-radius:18px;background:#090909}.tb-v1414-head{display:flex;justify-content:space-between;gap:24px;align-items:center;padding-bottom:16px;border-bottom:1px solid rgba(255,255,255,.05)}.tb-v1414-head small,.tb-v1414-signals small{display:block;color:#967c43;font-size:.52rem;letter-spacing:.14em}.tb-v1414-head h3{margin:4px 0;color:#e0d6c1;font-family:Cinzel,serif}.tb-v1414-head p{margin:5px 0 0;max-width:720px;color:#716a5e;font-size:.6rem;line-height:1.5}.tb-v1414-score{text-align:center;min-width:125px;padding:12px;border:1px solid rgba(216,180,90,.18);border-radius:14px;background:rgba(216,180,90,.025)}.tb-v1414-score strong{color:#e5c969;font:2rem Cinzel,serif}.tb-v1414-score span{color:#776b51;font-size:.55rem}.tb-v1414-score b{display:block;margin-top:4px;color:#b99d5a;font-size:.55rem;letter-spacing:.08em}.tb-v1414-bars{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:14px}.tb-v1414-bars article{padding:12px;border:1px solid rgba(255,255,255,.05);border-radius:12px;background:rgba(255,255,255,.012)}.tb-v1414-bars article>div{display:flex;justify-content:space-between;color:#8a8173;font-size:.57rem}.tb-v1414-bars b{color:#d8bd6b}.tb-v1414-bars i{display:block;height:5px;margin-top:8px;border-radius:99px;background:#171717;overflow:hidden}.tb-v1414-bars em{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,#725d2d,#d8b95d)}.tb-v1414-signals{margin-top:10px;padding:14px;border:1px solid rgba(255,255,255,.05);border-radius:12px}.tb-v1414-signals p{margin:7px 0 0;color:#8a8174;font-size:.58rem;line-height:1.45}.tb-v1414-foot{margin:10px 0 0;color:#625c53;font-size:.51rem;line-height:1.5}@media(max-width:760px){.tb-v1414-head{align-items:flex-start;flex-direction:column}.tb-v1414-bars{grid-template-columns:1fr}.tb-v1414-score{text-align:left}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v1414_css',110);
