<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.15 — Executive Action Center */
function tuff_beatz_v1415_actions(){
 $s=function_exists('tuff_beatz_v1414_scorecard')?tuff_beatz_v1414_scorecard():array();$f=$s['forecast']??array();$o=$s['operating']??array();$t=$s['trends']??array();$p=$s['pipeline']??array();$b=$s['business']??array();$actions=array();
 $add=function($severity,$title,$reason,$action,$url,$area)use(&$actions){$rank=array('critical'=>4,'high'=>3,'medium'=>2,'low'=>1);$actions[]=array('severity'=>$severity,'rank'=>$rank[$severity]??1,'title'=>$title,'reason'=>$reason,'action'=>$action,'url'=>$url,'area'=>$area);};
 $goal=(float)($f['goal']??0);$collected=(float)($f['month_collected']??0);if($goal>0&&$collected<$goal*.7)$add('high','Close the monthly revenue gap','Collections are below 70% of the configured monthly target.','Review receivables and prioritize near-close opportunities.',home_url('/business-command/'),'REVENUE');
 $weighted=(float)($p['weighted_value']??0);$receivable=(float)($b['receivable']??0);if($goal>0&&$weighted+$receivable<$goal*.5)$add('high','Rebuild forward pipeline','Weighted pipeline plus receivables cover less than half of the monthly target.','Qualify new leads and advance active opportunities toward proposal.',home_url('/business-command/'),'PIPELINE');
 $margin=$o['operating_margin']??null;if($margin!==null&&$margin<20)$add('high','Protect operating margin','Covered operating margin is below the 20% management reference.','Review project pricing, direct costs and monthly overhead before accepting low-margin work.',home_url('/business-command/'),'MARGIN');
 $coverage=(float)($o['cost_coverage']??0);if($coverage<70)$add('medium','Complete project cost basis','Less than 70% of monthly collections are represented by projects with recorded cost basis.','Enter missing direct project costs to improve profitability confidence.',admin_url('edit.php?post_type=tb_request'),'DATA');
 $growth=$t['revenue_change']??null;if($growth!==null&&$growth<0)$add('medium','Reverse collection decline','Recorded collections declined versus the previous month.','Review open invoices, deposits and follow-up activity.',home_url('/business-command/'),'MOMENTUM');
 $over=(float)($o['overhead']??0);$covered=(float)($o['covered_collected']??0);if($covered>0&&$over/$covered>.35)$add('medium','Review overhead load','Entered monthly overhead exceeds 35% of cost-covered collections.','Audit recurring overhead and identify expenses that can be reduced or delayed.',home_url('/business-command/'),'OVERHEAD');
 if(!$actions)$add('low','Maintain current operating discipline','No major exception is currently triggered by the executive scorecard.','Keep opportunity follow-ups, cost records, collections and overhead entries current.',home_url('/business-command/'),'HEALTH');
 usort($actions,function($a,$b){return $b['rank']<=>$a['rank'];});return $actions;
}
function tuff_beatz_v1415_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$actions=tuff_beatz_v1415_actions();$counts=array('critical'=>0,'high'=>0,'medium'=>0,'low'=>0);foreach($actions as $a)$counts[$a['severity']]++;ob_start();?><section class="tb-v1415-actions"><div class="tb-v1415-head"><div><small>EXECUTIVE ACTION CENTER • V14.15</small><h3>Priority Management Actions</h3><p>Converts current Business OS signals into a ranked operating queue. Recommendations remain advisory; no financial or workflow mutation is performed automatically.</p></div><div class="tb-v1415-count"><strong><?php echo esc_html((string)count($actions));?></strong><span>ACTIVE ACTIONS</span></div></div><div class="tb-v1415-list"><?php foreach($actions as $a):?><article class="is-<?php echo esc_attr($a['severity']);?>"><div class="tb-v1415-sev"><b><?php echo esc_html(strtoupper($a['severity']));?></b><span><?php echo esc_html($a['area']);?></span></div><div class="tb-v1415-copy"><h4><?php echo esc_html($a['title']);?></h4><p><?php echo esc_html($a['reason']);?></p><small>RECOMMENDED ACTION</small><p><?php echo esc_html($a['action']);?></p></div><a href="<?php echo esc_url($a['url']);?>">OPEN WORKFLOW →</a></article><?php endforeach;?></div><p class="tb-v1415-foot">Action priority is rule-based from recorded Business OS data and should be reviewed with business context before decisions are made.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var anchor=document.querySelector('.tb-v1414-scorecard')||document.querySelector('.tb-v1413-trends');if(!anchor||document.querySelector('.tb-v1415-actions'))return;var box=document.createElement('div');box.innerHTML=<?php echo wp_json_encode($html);?>;anchor.insertAdjacentElement('afterend',box.firstElementChild);var eye=document.querySelector('.tb-biz-hero .eyebrow');if(eye)eye.textContent='TUFF BEATZ • STUDIO BUSINESS OS V14.15';});</script><?php }
add_action('wp_footer','tuff_beatz_v1415_panel',15);
function tuff_beatz_v1415_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v1415-actions{margin-top:18px;padding:20px;border:1px solid rgba(216,180,90,.16);border-radius:18px;background:#090909}.tb-v1415-head{display:flex;justify-content:space-between;gap:24px;align-items:center;padding-bottom:16px;border-bottom:1px solid rgba(255,255,255,.05)}.tb-v1415-head small{display:block;color:#967c43;font-size:.52rem;letter-spacing:.14em}.tb-v1415-head h3{margin:4px 0;color:#e0d6c1;font-family:Cinzel,serif}.tb-v1415-head p{margin:5px 0 0;max-width:720px;color:#716a5e;font-size:.6rem;line-height:1.5}.tb-v1415-count{text-align:center;min-width:110px}.tb-v1415-count strong,.tb-v1415-count span{display:block}.tb-v1415-count strong{color:#e4c768;font:1.8rem Cinzel,serif}.tb-v1415-count span{color:#756a53;font-size:.48rem;letter-spacing:.1em}.tb-v1415-list{display:grid;gap:9px;margin-top:14px}.tb-v1415-list article{display:grid;grid-template-columns:95px 1fr auto;gap:16px;align-items:center;padding:14px;border:1px solid rgba(255,255,255,.05);border-radius:13px;background:rgba(255,255,255,.012)}.tb-v1415-sev b,.tb-v1415-sev span{display:block}.tb-v1415-sev b{color:#d8b95d;font-size:.55rem;letter-spacing:.08em}.tb-v1415-sev span{margin-top:4px;color:#6d6558;font-size:.48rem}.tb-v1415-copy h4{margin:0;color:#d8cfbd;font-size:.72rem}.tb-v1415-copy p{margin:4px 0;color:#7b7367;font-size:.56rem;line-height:1.4}.tb-v1415-copy small{display:block;margin-top:7px;color:#8f7744;font-size:.45rem;letter-spacing:.1em}.tb-v1415-list a{padding:8px 10px;border:1px solid rgba(216,180,90,.16);border-radius:8px;color:#c7a958;text-decoration:none;font-size:.5rem;white-space:nowrap}.tb-v1415-list .is-critical{border-color:rgba(220,90,70,.25)}.tb-v1415-list .is-high{border-color:rgba(216,180,90,.18)}.tb-v1415-foot{margin:10px 0 0;color:#625c53;font-size:.51rem}@media(max-width:760px){.tb-v1415-head{align-items:flex-start;flex-direction:column}.tb-v1415-count{text-align:left}.tb-v1415-list article{grid-template-columns:1fr}.tb-v1415-list a{justify-self:start}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v1415_css',111);
