<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.1 — Opportunity Engine */
function tuff_beatz_v14_opportunity_stages(){return array('new-lead'=>'New Lead','qualified'=>'Qualified','discovery'=>'Discovery','proposal'=>'Proposal','contract'=>'Contract','deposit-due'=>'Deposit Due','won'=>'Won / Project Created','lost'=>'Lost');}
function tuff_beatz_v14_stage_probability($stage){$map=array('new-lead'=>10,'qualified'=>25,'discovery'=>40,'proposal'=>60,'contract'=>75,'deposit-due'=>90,'won'=>100,'lost'=>0);return (int)($map[$stage]??10);}
function tuff_beatz_v14_register_opportunity(){register_post_type('tb_opportunity',array('labels'=>array('name'=>'Opportunities','singular_name'=>'Opportunity','add_new_item'=>'Add Opportunity','edit_item'=>'Edit Opportunity'),'public'=>false,'show_ui'=>true,'show_in_menu'=>true,'menu_icon'=>'dashicons-chart-line','supports'=>array('title'),'capability_type'=>'post','map_meta_cap'=>true));}
add_action('init','tuff_beatz_v14_register_opportunity',22);
function tuff_beatz_v14_opportunity_data($id){$id=(int)$id;$stage=sanitize_key(get_post_meta($id,'_tb_v14_stage',true)?:'new-lead');$prob=get_post_meta($id,'_tb_v14_probability',true);return array('id'=>$id,'title'=>get_the_title($id),'client_id'=>(int)get_post_meta($id,'_tb_v14_client_id',true),'contact_name'=>(string)get_post_meta($id,'_tb_v14_contact_name',true),'contact_email'=>(string)get_post_meta($id,'_tb_v14_contact_email',true),'service'=>(string)get_post_meta($id,'_tb_v14_service',true),'source'=>(string)get_post_meta($id,'_tb_v14_source',true),'stage'=>$stage,'estimated_value'=>(float)get_post_meta($id,'_tb_v14_estimated_value',true),'probability'=>$prob===''?tuff_beatz_v14_stage_probability($stage):max(0,min(100,(int)$prob)),'next_action'=>(string)get_post_meta($id,'_tb_v14_next_action',true),'followup_at'=>(string)get_post_meta($id,'_tb_v14_followup_at',true),'linked_request_id'=>(int)get_post_meta($id,'_tb_v14_linked_request_id',true),'lost_reason'=>(string)get_post_meta($id,'_tb_v14_lost_reason',true));}
function tuff_beatz_v14_opportunity_activity($id){$v=get_post_meta((int)$id,'_tb_v14_activity',true);return is_array($v)?array_values($v):array();}
function tuff_beatz_v14_add_opportunity_activity($id,$type,$message){$a=tuff_beatz_v14_opportunity_activity($id);$a[]=array('id'=>wp_generate_uuid4(),'type'=>sanitize_key($type),'message'=>sanitize_text_field($message),'user_id'=>get_current_user_id(),'time'=>current_time('mysql'));if(count($a)>200)$a=array_slice($a,-200);update_post_meta((int)$id,'_tb_v14_activity',$a);}
function tuff_beatz_v14_opportunity_metaboxes(){add_meta_box('tb_v14_opportunity','Studio Business OS — Opportunity','tuff_beatz_v14_opportunity_box','tb_opportunity','normal','high');}
add_action('add_meta_boxes','tuff_beatz_v14_opportunity_metaboxes');
function tuff_beatz_v14_opportunity_box($post){$d=tuff_beatz_v14_opportunity_data($post->ID);$stages=tuff_beatz_v14_opportunity_stages();wp_nonce_field('tb_v14_save_opportunity','tb_v14_nonce');?><style>.tb-v14-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.tb-v14-grid label{display:block;font-weight:700;margin-bottom:5px}.tb-v14-grid input,.tb-v14-grid select,.tb-v14-grid textarea{width:100%}.tb-v14-wide{grid-column:1/-1}@media(max-width:782px){.tb-v14-grid{grid-template-columns:1fr}}</style><div class="tb-v14-grid"><div><label>Contact name</label><input name="tb_v14_contact_name" value="<?php echo esc_attr($d['contact_name']);?>"></div><div><label>Contact email</label><input type="email" name="tb_v14_contact_email" value="<?php echo esc_attr($d['contact_email']);?>"></div><div><label>Existing client user ID</label><input type="number" min="0" name="tb_v14_client_id" value="<?php echo esc_attr((string)$d['client_id']);?>"></div><div><label>Service interest</label><input name="tb_v14_service" value="<?php echo esc_attr($d['service']);?>"></div><div><label>Lead source</label><input name="tb_v14_source" value="<?php echo esc_attr($d['source']);?>"></div><div><label>Pipeline stage</label><select name="tb_v14_stage"><?php foreach($stages as $k=>$v):?><option value="<?php echo esc_attr($k);?>" <?php selected($d['stage'],$k);?>><?php echo esc_html($v);?></option><?php endforeach;?></select></div><div><label>Estimated value ($)</label><input type="number" step="0.01" min="0" name="tb_v14_estimated_value" value="<?php echo esc_attr((string)$d['estimated_value']);?>"></div><div><label>Probability (%)</label><input type="number" min="0" max="100" name="tb_v14_probability" value="<?php echo esc_attr((string)$d['probability']);?>"></div><div><label>Follow-up</label><input type="datetime-local" name="tb_v14_followup_at" value="<?php echo esc_attr($d['followup_at']);?>"></div><div><label>Linked project ID</label><input type="number" min="0" readonly value="<?php echo esc_attr((string)$d['linked_request_id']);?>"></div><div class="tb-v14-wide"><label>Next action</label><textarea rows="2" name="tb_v14_next_action"><?php echo esc_textarea($d['next_action']);?></textarea></div><div class="tb-v14-wide"><label>Lost reason</label><textarea rows="2" name="tb_v14_lost_reason"><?php echo esc_textarea($d['lost_reason']);?></textarea></div></div><?php }
function tuff_beatz_v14_save_opportunity($id,$post){if($post->post_type!=='tb_opportunity'||defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!isset($_POST['tb_v14_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_v14_nonce'])),'tb_v14_save_opportunity')||!current_user_can('edit_post',$id))return;$old=tuff_beatz_v14_opportunity_data($id);$stage=sanitize_key(wp_unslash($_POST['tb_v14_stage']??'new-lead'));if(!isset(tuff_beatz_v14_opportunity_stages()[$stage]))$stage='new-lead';$map=array('_tb_v14_client_id'=>max(0,(int)($_POST['tb_v14_client_id']??0)),'_tb_v14_contact_name'=>sanitize_text_field(wp_unslash($_POST['tb_v14_contact_name']??'')),'_tb_v14_contact_email'=>sanitize_email(wp_unslash($_POST['tb_v14_contact_email']??'')),'_tb_v14_service'=>sanitize_text_field(wp_unslash($_POST['tb_v14_service']??'')),'_tb_v14_source'=>sanitize_text_field(wp_unslash($_POST['tb_v14_source']??'')),'_tb_v14_stage'=>$stage,'_tb_v14_estimated_value'=>max(0,(float)($_POST['tb_v14_estimated_value']??0)),'_tb_v14_probability'=>max(0,min(100,(int)($_POST['tb_v14_probability']??tuff_beatz_v14_stage_probability($stage)))),'_tb_v14_next_action'=>sanitize_textarea_field(wp_unslash($_POST['tb_v14_next_action']??'')),'_tb_v14_followup_at'=>sanitize_text_field(wp_unslash($_POST['tb_v14_followup_at']??'')),'_tb_v14_lost_reason'=>sanitize_textarea_field(wp_unslash($_POST['tb_v14_lost_reason']??'')));foreach($map as $k=>$v)update_post_meta($id,$k,$v);if($old['stage']!==$stage)tuff_beatz_v14_add_opportunity_activity($id,'stage','Stage changed from '.($old['stage']?:'new-lead').' to '.$stage);}
add_action('save_post_tb_opportunity','tuff_beatz_v14_save_opportunity',10,2);
function tuff_beatz_v14_opportunities($args=array()){$defaults=array('post_type'=>'tb_opportunity','post_status'=>array('publish','draft','private'),'posts_per_page'=>200,'orderby'=>'modified','order'=>'DESC');$q=new WP_Query(wp_parse_args($args,$defaults));return array_map(function($p){return tuff_beatz_v14_opportunity_data($p->ID);},$q->posts);}
function tuff_beatz_v14_pipeline_summary(){$items=tuff_beatz_v14_opportunities();$r=array('count'=>count($items),'open'=>0,'won'=>0,'lost'=>0,'pipeline_value'=>0.0,'weighted_value'=>0.0,'followups_due'=>0);$now=current_time('timestamp');foreach($items as $o){if($o['stage']==='won'){$r['won']++;continue;}if($o['stage']==='lost'){$r['lost']++;continue;}$r['open']++;$r['pipeline_value']+=$o['estimated_value'];$r['weighted_value']+=$o['estimated_value']*($o['probability']/100);if($o['followup_at']&&strtotime($o['followup_at'])<=$now)$r['followups_due']++;}return $r;}
