<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.16 — KPI-aware Executive Action Center */
function tuff_beatz_v1415_actions(){
 $s=function_exists('tuff_beatz_v1414_scorecard')?tuff_beatz_v1414_scorecard():array();$f=$s['forecast']??array();$o=$s['operating']??array();$t=$s['trends']??array();$p=$s['pipeline']??array();$b=$s['business']??array();$targets=function_exists('tuff_beatz_v1416_targets')?tuff_beatz_v1416_targets():array();$actions=array();
 $add=function($severity,$title,$reason,$action,$url,$area)use(&$actions){$rank=array('critical'=>4,'high'=>3,'medium'=>2,'low'=>1);$actions[]=array('severity'=>$severity,'rank'=>$rank[$severity]??1,'title'=>$title,'reason'=>$reason,'action'=>$action,'url'=>$url,'area'=>$area);};
 $goal=(float)($targets['monthly_revenue']??($f['goal']??0));$collected=(float)($f['month_collected']??0);if($goal>0&&$collected<$goal*.7)$add('high','Close the monthly revenue gap','Collections are below 70% of the configured monthly revenue target.','Review receivables and prioritize near-close opportunities.',home_url('/business-command/'),'REVENUE');
 $weighted=(float)($p['weighted_value']??0);$receivable=(float)($b['receivable']??0);$pipeline_target=(float)($targets['pipeline_coverage']??100);$pipeline_ratio=$goal>0?(($weighted+$receivable)/$goal)*100:0;if($goal>0&&$pipeline_ratio<$pipeline_target)$add('high','Rebuild forward pipeline','Weighted pipeline and receivables are below the configured pipeline coverage target.','Qualify new leads and advance active opportunities toward proposal.',home_url('/business-command/'),'PIPELINE');
 $margin=$o['operating_margin']??null;$margin_target=(float)($targets['operating_margin']??20);if($margin!==null&&$margin<$margin_target)$add('high','Protect operating margin','Covered operating margin is below the configured executive target.','Review project pricing, direct costs and monthly overhead before accepting low-margin work.',home_url('/business-command/'),'MARGIN');
 $coverage=(float)($o['cost_coverage']??0);$coverage_target=(float)($targets['cost_coverage']??90);if($coverage<$coverage_target)$add('medium','Complete project cost basis','Cost-data coverage is below the configured executive target.','Enter missing direct project costs to improve profitability confidence.',admin_url('edit.php?post_type=tb_request'),'DATA');
 $growth=$t['revenue_change']??null;$growth_target=(float)($targets['monthly_growth']??5);if($growth!==null&&$growth<$growth_target)$add('medium','Improve collection momentum','Monthly collection growth is below the configured growth target.','Review open invoices, deposits and follow-up activity.',home_url('/business-command/'),'MOMENTUM');
 $over=(float)($o['overhead']??0);$covered=(float)($o['covered_collected']??0);$max_over=(float)($targets['max_overhead_ratio']??35);if($covered>0&&(($over/$covered)*100)>$max_over)$add('medium','Review overhead load','Entered overhead exceeds the configured maximum overhead ratio.','Audit recurring overhead and identify expenses that can be reduced or delayed.',home_url('/business-command/'),'OVERHEAD');
 if(!$actions)$add('low','Maintain current operating discipline','No major exception is currently triggered against configured executive targets.','Keep opportunity follow-ups, cost records, collections and overhead entries current.',home_url('/business-command/'),'HEALTH');
 usort($actions,function($a,$b){return $b['rank']<=>$a['rank'];});return $actions;
}
function tuff_beatz_v1415_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$actions=tuff_beatz_v1415_actions();ob_start();?><section class="tb-v1415-actions"><div class="tb-v1415-head"><div><small>EXECUTIVE ACTION CENTER • V14.16</small><h3>Priority Management Actions</h3><p>Ranked operating actions measured against your configured Executive KPI Control targets. No workflow or financial mutation is performed automatically.</p></div><div class="tb-v1415-count"><strong><?php echo esc_html((string)count($actions));?></strong><span>ACTIVE ACTIONS</span></div></div><div class="tb-v1415-list"><?php foreach($actions as $a):?><article class="is-<?php echo esc_attr($a['severity']);?>"><div class="tb-v1415-sev"><b><?php echo esc_html(strtoupper($a['severity']));?></b><span><?php echo esc_html($a['area']);?></span></div><div class="tb-v1415-copy"><h4><?php echo esc_html($a['title']);?></h4><p><?php echo esc_html($a['reason']);?></p><small>RECOMMENDED ACTION</small><p><?php echo esc_html($a['action']);?></p></div><a href="<?php echo esc_url($a['url']);?>">OPEN WORKFLOW →</a></article><?php endforeach;?></div><p class="tb-v1415-foot">Rule-based management guidance from recorded Business OS data; review business context before decisions.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var anchor=document.querySelector('.tb-v1414-scorecard')||document.querySelector('.tb-v1413-trends');if(!anchor||document.querySelector('.tb-v1415-actions'))return;var box=document.createElement('div');box.innerHTML=<?php echo wp_json_encode($html);?>;anchor.insertAdjacentElement('afterend',box.firstElementChild);});</script><?php }
add_action('wp_footer','tuff_beatz_v1415_panel',15);
function tuff_beatz_v1415_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v1415-actions{margin-top:18px;padding:20px;border:1px solid rgba(216,180,90,.16);border-radius:18px;background:#090909}.tb-v1415-head{display:flex;justify-content:space-between;gap:24px;align-items:center;padding-bottom:16px;border-bottom:1px solid rgba(255,255,255,.05)}.tb-v1415-head small{color:#967c43;font-size:.52rem;letter-spacing:.14em}.tb-v1415-head h3{margin:4px 0;color:#e0d6c1;font-family:Cinzel,serif}.tb-v1415-head p{color:#716a5e;font-size:.6rem}.tb-v1415-count{text-align:center;min-width:110px}.tb-v1415-count strong,.tb-v1415-count span{display:block}.tb-v1415-count strong{color:#e4c768;font:1.8rem Cinzel,serif}.tb-v1415-count span{color:#756a53;font-size:.48rem}.tb-v1415-list{display:grid;gap:9px;margin-top:14px}.tb-v1415-list article{display:grid;grid-template-columns:95px 1fr auto;gap:16px;align-items:center;padding:14px;border:1px solid rgba(255,255,255,.05);border-radius:13px}.tb-v1415-sev b,.tb-v1415-sev span{display:block}.tb-v1415-sev b{color:#d8b95d;font-size:.55rem}.tb-v1415-sev span{color:#6d6558;font-size:.48rem}.tb-v1415-copy h4{margin:0;color:#d8cfbd;font-size:.72rem}.tb-v1415-copy p{margin:4px 0;color:#7b7367;font-size:.56rem}.tb-v1415-copy small{color:#8f7744;font-size:.45rem}.tb-v1415-list a{padding:8px 10px;border:1px solid rgba(216,180,90,.16);border-radius:8px;color:#c7a958;text-decoration:none;font-size:.5rem}.tb-v1415-foot{color:#625c53;font-size:.51rem}@media(max-width:760px){.tb-v1415-head{flex-direction:column;align-items:flex-start}.tb-v1415-list article{grid-template-columns:1fr}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v1415_css',111);