<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.2 — Business Command Center */
function tuff_beatz_v14_business_command_setup(){
 $p=get_page_by_path('business-command');
 if(!$p){$id=wp_insert_post(array('post_title'=>'Business Command Center','post_name'=>'business-command','post_status'=>'publish','post_type'=>'page','post_content'=>''));if(!is_wp_error($id)&&$id)update_post_meta($id,'_wp_page_template','page-business-command.php');}
 else update_post_meta($p->ID,'_wp_page_template','page-business-command.php');
}
add_action('init','tuff_beatz_v14_business_command_setup',36);
function tuff_beatz_v14_business_command_assets(){if(!is_page('business-command'))return;$base=get_template_directory();$hub=$base.'/assets/css/portal-hubs.css';$lux=$base.'/assets/css/luxury-studio-os.css';$biz=$base.'/assets/css/business-command.css';if(file_exists($hub))wp_enqueue_style('tuff-beatz-portal-hubs',get_template_directory_uri().'/assets/css/portal-hubs.css',array('tuff-beatz-main'),filemtime($hub));if(file_exists($lux))wp_enqueue_style('tuff-beatz-luxury-studio-os',get_template_directory_uri().'/assets/css/luxury-studio-os.css',array('tuff-beatz-portal-hubs'),filemtime($lux));if(file_exists($biz))wp_enqueue_style('tuff-beatz-business-command',get_template_directory_uri().'/assets/css/business-command.css',array('tuff-beatz-luxury-studio-os'),filemtime($biz));}
add_action('wp_enqueue_scripts','tuff_beatz_v14_business_command_assets',84);
function tuff_beatz_v14_business_command_body($classes){if(is_page('business-command')){$classes[]='tb-studio-os';$classes[]='tb-business-command-page';}return $classes;}
add_filter('body_class','tuff_beatz_v14_business_command_body');
function tuff_beatz_v14_business_command_adminbar($show){return !is_admin()&&is_page('business-command')?false:$show;}
add_filter('show_admin_bar','tuff_beatz_v14_business_command_adminbar',100);
function tuff_beatz_v14_project_business_summary(){
 $q=new WP_Query(array('post_type'=>'tb_request','post_status'=>'publish','posts_per_page'=>300,'orderby'=>'date','order'=>'DESC'));
 $r=array('project_count'=>count($q->posts),'quoted'=>0.0,'paid'=>0.0,'receivable'=>0.0,'deposit_due'=>0,'balance_due'=>0,'quotes_pending'=>0,'contracts_pending'=>0,'active_value'=>0.0,'completed_revenue'=>0.0,'receivable_projects'=>array());
 foreach($q->posts as $p){$id=$p->ID;$quote=function_exists('tuff_beatz_quote_data')?tuff_beatz_quote_data($id):array();$tot=function_exists('tuff_beatz_payment_totals')?tuff_beatz_payment_totals($id):array('total'=>0,'paid'=>0,'balance'=>0);$total=(float)($tot['total']??0);$paid=(float)($tot['paid']??0);$balance=(float)($tot['balance']??0);$r['quoted']+=$total;$r['paid']+=$paid;$r['receivable']+=$balance;$payment=(string)get_post_meta($id,'_tb_request_payment_status',true);if($payment==='Deposit due')$r['deposit_due']++;if($payment==='Balance due')$r['balance_due']++;if(!empty($quote)&&($quote['status']??'sent')!=='accepted')$r['quotes_pending']++;if(!empty($quote)&&!get_post_meta($id,'_tb_contract_acceptance',true))$r['contracts_pending']++;$status=(string)(get_post_meta($id,'_tb_request_status',true)?:'new');if($status==='completed')$r['completed_revenue']+=$paid;elseif($status!=='declined')$r['active_value']+=$total;if($balance>0)$r['receivable_projects'][]=array('id'=>$id,'title'=>$p->post_title,'client'=>get_post_meta($id,'_tb_request_artist',true)?:'Client','balance'=>$balance,'payment_status'=>$payment?:'Due','status'=>$status);}
 usort($r['receivable_projects'],function($a,$b){return $b['balance']<=>$a['balance'];});return $r;
}
function tuff_beatz_v14_opportunity_attention(){if(!function_exists('tuff_beatz_v14_opportunities'))return array();$out=array();$now=current_time('timestamp');foreach(tuff_beatz_v14_opportunities() as $o){if(in_array($o['stage'],array('won','lost'),true))continue;$score=0;$reason='';if($o['followup_at']&&strtotime($o['followup_at'])<=$now){$score=5;$reason='Follow-up due';}elseif($o['stage']==='deposit-due'){$score=4;$reason='Deposit due';}elseif($o['stage']==='contract'){$score=3;$reason='Contract decision';}elseif($o['stage']==='proposal'){$score=2;$reason='Proposal pending';}if($score)$out[]=array('id'=>$o['id'],'title'=>$o['title'],'contact'=>$o['contact_name']?:$o['contact_email'],'stage'=>$o['stage'],'reason'=>$reason,'value'=>$o['estimated_value'],'score'=>$score,'followup_at'=>$o['followup_at']);}usort($out,function($a,$b){return $b['score']<=>$a['score'];});return $out;}
function tuff_beatz_v14_stage_buckets(){if(!function_exists('tuff_beatz_v14_opportunity_stages'))return array();$b=array();foreach(tuff_beatz_v14_opportunity_stages() as $k=>$label)$b[$k]=array('label'=>$label,'count'=>0,'value'=>0.0,'weighted'=>0.0);foreach(function_exists('tuff_beatz_v14_opportunities')?tuff_beatz_v14_opportunities():array() as $o){if(!isset($b[$o['stage']]))continue;$b[$o['stage']]['count']++;$b[$o['stage']]['value']+=(float)$o['estimated_value'];$b[$o['stage']]['weighted']+=(float)$o['estimated_value']*((int)$o['probability']/100);}return $b;}
function tuff_beatz_v14_producer_business_link(){if(!is_page('producer-portal')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;?><script>document.addEventListener('DOMContentLoaded',function(){var a=document.querySelector('.tb-command-hero .tb-hub-actions');if(!a||a.querySelector('[data-tb-business-os]'))return;var x=document.createElement('a');x.className='btn btn-outline';x.href=<?php echo wp_json_encode(home_url('/business-command/'));?>;x.textContent='Business OS';x.setAttribute('data-tb-business-os','1');a.appendChild(x);});</script><?php }
add_action('wp_footer','tuff_beatz_v14_producer_business_link',8);
