<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.4 — Opportunity Proposal Engine */
function tuff_beatz_v14_proposal_data($id){$p=get_post_meta((int)$id,'_tb_v14_proposal',true);return is_array($p)?$p:array();}
function tuff_beatz_v14_proposal_acceptance($id){$a=get_post_meta((int)$id,'_tb_v14_proposal_acceptance',true);return is_array($a)?$a:array();}
function tuff_beatz_v14_proposal_totals($p){$subtotal=max(0,(float)($p['subtotal']??0));$discount=max(0,(float)($p['discount']??0));$tax=max(0,(float)($p['tax']??0));$total=max(0,$subtotal-$discount+$tax);$deposit_pct=min(100,max(0,(float)($p['deposit_percent']??50)));$deposit=round($total*$deposit_pct/100,2);return compact('subtotal','discount','tax','total','deposit_pct','deposit');}
function tuff_beatz_v14_proposal_token($id){$t=(string)get_post_meta((int)$id,'_tb_v14_proposal_token',true);if(!$t){$t=wp_generate_password(32,false,false);update_post_meta((int)$id,'_tb_v14_proposal_token',$t);}return $t;}
function tuff_beatz_v14_proposal_url($id){return add_query_arg(array('opportunity'=>(int)$id,'proposal_token'=>rawurlencode(tuff_beatz_v14_proposal_token($id))),home_url('/proposal/'));}
function tuff_beatz_v14_proposal_setup(){if(!get_page_by_path('proposal')){$id=wp_insert_post(array('post_title'=>'Proposal','post_name'=>'proposal','post_status'=>'publish','post_type'=>'page','post_content'=>''));if(!is_wp_error($id)&&$id)update_post_meta($id,'_wp_page_template','page-proposal.php');}}
add_action('init','tuff_beatz_v14_proposal_setup',38);
function tuff_beatz_v14_proposal_box($post){$p=tuff_beatz_v14_proposal_data($post->ID);$t=tuff_beatz_v14_proposal_totals($p);$url=tuff_beatz_v14_proposal_url($post->ID);wp_nonce_field('tb_v14_proposal_'.$post->ID,'tb_v14_proposal_nonce');echo '<style>.tb-v14-proposal-admin label{display:block;font-weight:700;margin:10px 0 4px}.tb-v14-proposal-admin input,.tb-v14-proposal-admin textarea{width:100%}.tb-v14-proposal-money{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.tb-v14-proposal-money div{padding:10px;background:#f6f7f7}</style><div class="tb-v14-proposal-admin"><label>Proposal #</label><input name="tb_v14_proposal_number" value="'.esc_attr($p['number']??('TBP-'.str_pad($post->ID,5,'0',STR_PAD_LEFT))).'"><label>Executive Summary</label><textarea rows="4" name="tb_v14_proposal_summary">'.esc_textarea($p['summary']??'').'</textarea><label>Scope / Deliverables</label><textarea rows="7" name="tb_v14_proposal_scope">'.esc_textarea($p['scope']??'').'</textarea><div class="tb-v14-proposal-money"><div><label>Subtotal</label><input type="number" step="0.01" min="0" name="tb_v14_proposal_subtotal" value="'.esc_attr($p['subtotal']??'').' "></div><div><label>Discount</label><input type="number" step="0.01" min="0" name="tb_v14_proposal_discount" value="'.esc_attr($p['discount']??0).'"></div><div><label>Tax / Fees</label><input type="number" step="0.01" min="0" name="tb_v14_proposal_tax" value="'.esc_attr($p['tax']??0).'"></div><div><label>Deposit %</label><input type="number" min="0" max="100" name="tb_v14_proposal_deposit" value="'.esc_attr($p['deposit_percent']??50).'"></div></div><label>Expires</label><input type="date" name="tb_v14_proposal_expires" value="'.esc_attr($p['expires']??'').'"><p><strong>Total: '.esc_html(function_exists('tuff_beatz_money')?tuff_beatz_money($t['total']):'$'.number_format($t['total'],2)).' • Deposit: '.esc_html(function_exists('tuff_beatz_money')?tuff_beatz_money($t['deposit']):'$'.number_format($t['deposit'],2)).'</strong></p><p><label>Client Proposal Link</label><input readonly value="'.esc_attr($url).'" onclick="this.select()"></p></div>';}
function tuff_beatz_v14_proposal_metabox(){add_meta_box('tb_v14_proposal','Studio Business OS — Proposal','tuff_beatz_v14_proposal_box','tb_opportunity','normal','high');}
add_action('add_meta_boxes_tb_opportunity','tuff_beatz_v14_proposal_metabox');
function tuff_beatz_v14_save_proposal($id,$post){if($post->post_type!=='tb_opportunity'||defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!isset($_POST['tb_v14_proposal_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_v14_proposal_nonce'])),'tb_v14_proposal_'.$id)||!current_user_can('edit_post',$id))return;$old=tuff_beatz_v14_proposal_data($id);$p=array('number'=>sanitize_text_field(wp_unslash($_POST['tb_v14_proposal_number']??'')),'summary'=>sanitize_textarea_field(wp_unslash($_POST['tb_v14_proposal_summary']??'')),'scope'=>sanitize_textarea_field(wp_unslash($_POST['tb_v14_proposal_scope']??'')),'subtotal'=>max(0,(float)($_POST['tb_v14_proposal_subtotal']??0)),'discount'=>max(0,(float)($_POST['tb_v14_proposal_discount']??0)),'tax'=>max(0,(float)($_POST['tb_v14_proposal_tax']??0)),'deposit_percent'=>min(100,max(0,(float)($_POST['tb_v14_proposal_deposit']??50))),'expires'=>sanitize_text_field(wp_unslash($_POST['tb_v14_proposal_expires']??'')),'updated_at'=>current_time('mysql'));
 $finger=hash('sha256',wp_json_encode(array($p['summary'],$p['scope'],$p['subtotal'],$p['discount'],$p['tax'],$p['deposit_percent'],$p['expires'])));$p['version']=$finger;$p['revision']=max(1,(int)($old['revision']??0)+((($old['version']??'')&&($old['version']??'')!==$finger)?1:0));$p['status']=(($old['version']??'')===$finger&&isset($old['status']))?$old['status']:'draft';if(($old['version']??'')&&($old['version']??'')!==$finger){delete_post_meta($id,'_tb_v14_proposal_acceptance');tuff_beatz_v14_add_opportunity_activity($id,'proposal','Proposal revised to version '.$p['revision']);}update_post_meta($id,'_tb_v14_proposal',$p);}
add_action('save_post_tb_opportunity','tuff_beatz_v14_save_proposal',30,2);
function tuff_beatz_v14_proposal_access($id,$token){if(get_post_type($id)!=='tb_opportunity')return false;if(current_user_can('edit_post',$id))return true;$saved=(string)get_post_meta($id,'_tb_v14_proposal_token',true);return $saved&&$token&&hash_equals($saved,$token);}
function tuff_beatz_v14_proposal_decision(){ $id=(int)($_POST['opportunity_id']??0);$token=sanitize_text_field(wp_unslash($_POST['proposal_token']??''));$url=add_query_arg(array('opportunity'=>$id,'proposal_token'=>rawurlencode($token)),home_url('/proposal/'));if(!$id||!tuff_beatz_v14_proposal_access($id,$token)){wp_die('Proposal access denied.',403);}if(!isset($_POST['tb_v14_proposal_decision_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_v14_proposal_decision_nonce'])),'tb_v14_proposal_decision_'.$id)){wp_die('Proposal verification failed.',403);}$p=tuff_beatz_v14_proposal_data($id);if(!$p){wp_safe_redirect($url);exit;}if(!empty($p['expires'])&&strtotime($p['expires'].' 23:59:59')<current_time('timestamp')){wp_safe_redirect(add_query_arg('proposal_state','expired',$url));exit;}$decision=sanitize_key($_POST['decision']??'');if(!in_array($decision,array('accepted','declined'),true)){wp_safe_redirect($url);exit;}$record=array('decision'=>$decision,'proposal_version'=>$p['version']??'','proposal_revision'=>(int)($p['revision']??1),'name'=>sanitize_text_field(wp_unslash($_POST['client_name']??'')),'email'=>sanitize_email(wp_unslash($_POST['client_email']??'')),'decided_at'=>current_time('mysql'),'ip_hash'=>hash('sha256',($_SERVER['REMOTE_ADDR']??'').'|'.wp_salt('auth')));update_post_meta($id,'_tb_v14_proposal_acceptance',$record);$p['status']=$decision;update_post_meta($id,'_tb_v14_proposal',$p);if($decision==='accepted'){update_post_meta($id,'_tb_v14_stage','contract');update_post_meta($id,'_tb_v14_probability',75);tuff_beatz_v14_add_opportunity_activity($id,'proposal','Proposal accepted by '.$record['name']);}else{tuff_beatz_v14_add_opportunity_activity($id,'proposal','Proposal declined by '.$record['name']);}wp_mail(get_option('admin_email'),'TUFF BEATZ — Proposal '.ucfirst($decision),get_the_title($id).' — '.$record['name'].' <'.$record['email'].'>');wp_safe_redirect(add_query_arg('proposal_state',$decision,$url));exit;}
add_action('admin_post_nopriv_tb_v14_proposal_decision','tuff_beatz_v14_proposal_decision');add_action('admin_post_tb_v14_proposal_decision','tuff_beatz_v14_proposal_decision');
function tuff_beatz_v14_proposal_mark_sent(){ $id=(int)($_POST['opportunity_id']??0);if(!$id||!current_user_can('edit_post',$id))wp_die('Not allowed.',403);check_admin_referer('tb_v14_mark_sent_'.$id,'tb_v14_mark_sent_nonce');$p=tuff_beatz_v14_proposal_data($id);if($p){$p['status']='sent';$p['sent_at']=current_time('mysql');update_post_meta($id,'_tb_v14_proposal',$p);update_post_meta($id,'_tb_v14_stage','proposal');update_post_meta($id,'_tb_v14_probability',60);tuff_beatz_v14_add_opportunity_activity($id,'proposal','Proposal marked sent');}wp_safe_redirect(get_edit_post_link($id,'url'));exit;}
add_action('admin_post_tb_v14_proposal_mark_sent','tuff_beatz_v14_proposal_mark_sent');
function tuff_beatz_v14_proposal_send_box($post){$p=tuff_beatz_v14_proposal_data($post->ID);if(!$p){echo '<p>Create and save the proposal first.</p>';return;}echo '<p><strong>Status:</strong> '.esc_html(strtoupper($p['status']??'draft')).'</p><p><strong>Revision:</strong> '.esc_html((int)($p['revision']??1)).'</p><p><a class="button button-primary" target="_blank" href="'.esc_url(tuff_beatz_v14_proposal_url($post->ID)).'">Preview Client Proposal</a></p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tb_v14_proposal_mark_sent"><input type="hidden" name="opportunity_id" value="'.esc_attr($post->ID).'">';wp_nonce_field('tb_v14_mark_sent_'.$post->ID,'tb_v14_mark_sent_nonce');echo '<button class="button" type="submit">Mark Proposal Sent</button></form>';}
function tuff_beatz_v14_proposal_send_metabox(){add_meta_box('tb_v14_proposal_send','Proposal Delivery','tuff_beatz_v14_proposal_send_box','tb_opportunity','side','high');}
add_action('add_meta_boxes_tb_opportunity','tuff_beatz_v14_proposal_send_metabox');
