<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.8 — Commercial Automation Intelligence + event-driven reliability */
function tuff_beatz_v147_age_days($mysql){if(!$mysql)return 0;$ts=strtotime($mysql);return $ts?max(0,(int)floor((current_time('timestamp')-$ts)/DAY_IN_SECONDS)):0;}
function tuff_beatz_v147_opportunity_intelligence($id){$o=tuff_beatz_v14_opportunity_data($id);$stage=$o['stage'];$proposal=function_exists('tuff_beatz_v14_proposal_data')?tuff_beatz_v14_proposal_data($id):array();$pa=function_exists('tuff_beatz_v14_proposal_acceptance')?tuff_beatz_v14_proposal_acceptance($id):array();$contract=function_exists('tuff_beatz_v145_contract_data')?tuff_beatz_v145_contract_data($id):array();$ca=function_exists('tuff_beatz_v145_contract_acceptance')?tuff_beatz_v145_contract_acceptance($id):array();$deposit=function_exists('tuff_beatz_v146_deposit_data')?tuff_beatz_v146_deposit_data($id):array();$modified=get_post_modified_time('Y-m-d H:i:s',false,$id);$age=tuff_beatz_v147_age_days($modified);$score=0;$kind='healthy';$headline='Pipeline healthy';$suggestion=$o['next_action']?:'Keep the opportunity moving toward the next commercial decision.';$due='';if($o['followup_at']&&strtotime($o['followup_at'])<=current_time('timestamp')){$score=95;$kind='followup';$headline='Follow-up overdue';$suggestion='Contact the prospect and record the next decision or follow-up date.';$due=$o['followup_at'];}elseif($stage==='proposal'&&empty($pa)){$sent=$proposal['sent_at']??$proposal['updated_at']??$modified;$days=tuff_beatz_v147_age_days($sent);$score=$days>=5?90:($days>=2?70:45);$kind='proposal';$headline=$days>=2?'Proposal awaiting decision':'Proposal sent';$suggestion='Follow up on the proposal and confirm scope, pricing, or decision timing.';$due=$sent;}elseif($stage==='contract'&&($ca['decision']??'')!=='accepted'){$sent=$contract['sent_at']??$contract['updated_at']??$modified;$days=tuff_beatz_v147_age_days($sent);$score=$days>=5?92:($days>=2?72:48);$kind='contract';$headline=$days>=2?'Contract awaiting acceptance':'Contract pending';$suggestion='Confirm agreement acceptance or resolve any contract questions.';$due=$sent;}elseif($stage==='deposit-due'&&($deposit['status']??'due')!=='verified'){$updated=$deposit['updated_at']??$modified;$days=tuff_beatz_v147_age_days($updated);$score=$days>=3?98:82;$kind='deposit';$headline=$days>=3?'Deposit overdue':'Deposit awaiting verification';$suggestion='Confirm payment status, send the checkout link if needed, and verify the deposit.';$due=$updated;}elseif(in_array($stage,array('new-lead','qualified','discovery'),true)&&$age>=3){$score=min(88,55+$age*3);$kind='stale';$headline='Opportunity needs movement';$suggestion='Schedule the next conversation and move the deal to a defined decision stage.';$due=$modified;}elseif($stage==='won'&&$o['linked_request_id']){$score=10;$kind='converted';$headline='Converted to production';$suggestion='Manage this client from the Production Command Center.';}elseif($stage==='lost'){$score=0;$kind='closed';$headline='Opportunity closed';$suggestion='No sales action required.';}return array('id'=>$id,'score'=>$score,'kind'=>$kind,'headline'=>$headline,'suggestion'=>$suggestion,'due'=>$due,'age_days'=>$age,'opportunity'=>$o);}
function tuff_beatz_v147_attention_queue($limit=12){$items=array();foreach(function_exists('tuff_beatz_v14_opportunities')?tuff_beatz_v14_opportunities():array() as $o){$x=tuff_beatz_v147_opportunity_intelligence($o['id']);if($x['score']>=45)$items[]=$x;}usort($items,function($a,$b){if($a['score']===$b['score'])return ($b['opportunity']['estimated_value']<=>$a['opportunity']['estimated_value']);return $b['score']<=>$a['score'];});return array_slice($items,0,max(1,(int)$limit));}
function tuff_beatz_v147_summary(){$r=array('critical'=>0,'due'=>0,'proposal'=>0,'contract'=>0,'deposit'=>0,'stale'=>0);foreach(tuff_beatz_v147_attention_queue(200) as $x){$r['due']++;if($x['score']>=90)$r['critical']++;if(isset($r[$x['kind']]))$r[$x['kind']]++;}return $r;}
function tuff_beatz_v148_clear_intelligence($id){delete_post_meta($id,'_tb_v147_suggested_action');delete_post_meta($id,'_tb_v147_attention_kind');delete_post_meta($id,'_tb_v147_attention_score');delete_post_meta($id,'_tb_v147_attention_updated_at');}
function tuff_beatz_v148_sync_opportunity($id){$id=(int)$id;if(!$id||get_post_type($id)!=='tb_opportunity'||!function_exists('tuff_beatz_v14_opportunity_data'))return;$x=tuff_beatz_v147_opportunity_intelligence($id);if($x['score']<45){tuff_beatz_v148_clear_intelligence($id);return;}update_post_meta($id,'_tb_v147_suggested_action',$x['suggestion']);update_post_meta($id,'_tb_v147_attention_kind',$x['kind']);update_post_meta($id,'_tb_v147_attention_score',(int)$x['score']);update_post_meta($id,'_tb_v147_attention_updated_at',current_time('mysql'));}
function tuff_beatz_v147_sync_next_actions(){if(!function_exists('tuff_beatz_v14_opportunities'))return;foreach(tuff_beatz_v14_opportunities() as $o)tuff_beatz_v148_sync_opportunity($o['id']);}
function tuff_beatz_v148_sync_on_save($post_id,$post,$update){if($post->post_type!=='tb_opportunity'||wp_is_post_revision($post_id)||wp_is_post_autosave($post_id))return;tuff_beatz_v148_sync_opportunity($post_id);}
add_action('save_post_tb_opportunity','tuff_beatz_v148_sync_on_save',90,3);
function tuff_beatz_v148_schedule(){if(!wp_next_scheduled('tuff_beatz_v148_hourly_sync'))wp_schedule_event(time()+300,'hourly','tuff_beatz_v148_hourly_sync');}
add_action('init','tuff_beatz_v148_schedule',61);
add_action('tuff_beatz_v148_hourly_sync','tuff_beatz_v147_sync_next_actions');
function tuff_beatz_v148_unschedule(){$ts=wp_next_scheduled('tuff_beatz_v148_hourly_sync');if($ts)wp_unschedule_event($ts,'tuff_beatz_v148_hourly_sync');}
add_action('switch_theme','tuff_beatz_v148_unschedule');
function tuff_beatz_v147_admin_notice(){if(!is_admin()||!current_user_can('edit_posts'))return;$screen=function_exists('get_current_screen')?get_current_screen():null;if(!$screen||$screen->post_type!=='tb_opportunity')return;$id=(int)($_GET['post']??0);if(!$id)return;$x=tuff_beatz_v147_opportunity_intelligence($id);if($x['score']<45)return;echo '<div class="notice notice-warning"><p><strong>Studio Business OS:</strong> '.esc_html($x['headline']).' — '.esc_html($x['suggestion']).'</p></div>';}
add_action('admin_notices','tuff_beatz_v147_admin_notice');
