<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio Business OS V14.16 — Executive Goals & KPI Control */
function tuff_beatz_v1416_defaults(){return array('annual_revenue'=>0,'monthly_revenue'=>0,'operating_margin'=>20,'pipeline_coverage'=>100,'collection_rate'=>90,'monthly_growth'=>5,'cost_coverage'=>90,'max_overhead_ratio'=>35);}
function tuff_beatz_v1416_targets(){return wp_parse_args((array)get_option('_tb_v1416_kpi_targets',array()),tuff_beatz_v1416_defaults());}
function tuff_beatz_v1416_save(){if(!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())wp_die('Unauthorized',403);check_admin_referer('tb_v1416_save','tb_v1416_nonce');$d=tuff_beatz_v1416_defaults();$raw=is_array($_POST['targets']??null)?wp_unslash($_POST['targets']):array();$out=array();foreach($d as $k=>$v)$out[$k]=max(0,(float)($raw[$k]??$v));update_option('_tb_v1416_kpi_targets',$out,false);if($out['monthly_revenue']>0)update_option('_tb_v1410_monthly_revenue_goal',$out['monthly_revenue'],false);wp_safe_redirect(add_query_arg('kpi_saved','1',home_url('/business-command/')));exit;}
add_action('admin_post_tb_v1416_save','tuff_beatz_v1416_save');
function tuff_beatz_v1416_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$t=tuff_beatz_v1416_targets();$fields=array('annual_revenue'=>'Annual Revenue Target ($)','monthly_revenue'=>'Monthly Revenue Target ($)','operating_margin'=>'Operating Margin Target (%)','pipeline_coverage'=>'Pipeline Coverage Target (%)','collection_rate'=>'Collection Rate Target (%)','monthly_growth'=>'Monthly Growth Target (%)','cost_coverage'=>'Cost Data Coverage Target (%)','max_overhead_ratio'=>'Maximum Overhead Ratio (%)');ob_start();?><section class="tb-v1416-kpi"><div class="tb-v1416-head"><div><small>EXECUTIVE KPI CONTROL • V14.16</small><h3>Goals & Performance Targets</h3><p>Set the management targets used by the executive intelligence layer. Monthly revenue also synchronizes with the V14.10 forecasting target.</p></div><b>CONTROL LAYER</b></div><details><summary>Configure Executive Targets</summary><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tb_v1416_save"><?php wp_nonce_field('tb_v1416_save','tb_v1416_nonce');?><div class="tb-v1416-grid"><?php foreach($fields as $k=>$label):?><label><?php echo esc_html($label);?><input type="number" min="0" step="0.01" name="targets[<?php echo esc_attr($k);?>]" value="<?php echo esc_attr((string)$t[$k]);?>"></label><?php endforeach;?></div><button type="submit">SAVE EXECUTIVE TARGETS</button></form></details><div class="tb-v1416-strip"><?php foreach(array('monthly_revenue'=>'MONTHLY REVENUE','operating_margin'=>'MARGIN','pipeline_coverage'=>'PIPELINE','collection_rate'=>'COLLECTION','monthly_growth'=>'GROWTH','cost_coverage'=>'COST DATA') as $k=>$label):?><span><small><?php echo esc_html($label);?></small><strong><?php echo $k==='monthly_revenue'?'$'.esc_html(number_format((float)$t[$k],0)):esc_html(number_format((float)$t[$k],1).'%');?></strong></span><?php endforeach;?></div><p>Targets are management objectives, not forecasts or guarantees.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var anchor=document.querySelector('.tb-v1415-actions')||document.querySelector('.tb-v1414-scorecard');if(!anchor||document.querySelector('.tb-v1416-kpi'))return;var box=document.createElement('div');box.innerHTML=<?php echo wp_json_encode($html);?>;anchor.insertAdjacentElement('afterend',box.firstElementChild);var eye=document.querySelector('.tb-biz-hero .eyebrow');if(eye)eye.textContent='TUFF BEATZ • STUDIO BUSINESS OS V14.16';});</script><?php }
add_action('wp_footer','tuff_beatz_v1416_panel',16);
function tuff_beatz_v1416_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v1416-kpi{margin-top:18px;padding:20px;border:1px solid rgba(216,180,90,.17);border-radius:18px;background:#090909}.tb-v1416-head{display:flex;justify-content:space-between;gap:20px;align-items:center}.tb-v1416-head small{color:#967c43;font-size:.52rem;letter-spacing:.14em}.tb-v1416-head h3{margin:4px 0;color:#e0d6c1;font-family:Cinzel,serif}.tb-v1416-head p,.tb-v1416-kpi>p{color:#716a5e;font-size:.56rem}.tb-v1416-head>b{color:#c4a957;font-size:.55rem}.tb-v1416-kpi details{margin-top:14px;padding:13px;border:1px solid rgba(255,255,255,.05);border-radius:12px}.tb-v1416-kpi summary{cursor:pointer;color:#d8b95d;font-size:.62rem}.tb-v1416-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:12px}.tb-v1416-grid label{color:#7d7568;font-size:.52rem}.tb-v1416-grid input{display:block;width:100%;margin-top:5px;padding:9px;border:1px solid rgba(255,255,255,.08);border-radius:8px;background:#080808;color:#ddd2bc}.tb-v1416-kpi button{margin-top:10px;padding:9px 12px;border:1px solid rgba(216,180,90,.2);border-radius:8px;background:rgba(216,180,90,.05);color:#d8b95d}.tb-v1416-strip{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-top:10px}.tb-v1416-strip span{padding:10px;border:1px solid rgba(255,255,255,.05);border-radius:10px}.tb-v1416-strip small,.tb-v1416-strip strong{display:block}.tb-v1416-strip small{color:#756b59;font-size:.43rem}.tb-v1416-strip strong{margin-top:4px;color:#d8bd6b;font-family:Cinzel,serif;font-size:.72rem}@media(max-width:900px){.tb-v1416-grid{grid-template-columns:repeat(2,1fr)}.tb-v1416-strip{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.tb-v1416-head{align-items:flex-start;flex-direction:column}.tb-v1416-grid,.tb-v1416-strip{grid-template-columns:1fr}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v1416_css',112);
