<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ V14.3 — Client CRM + Client 360 Commercial Intelligence */
function tuff_beatz_crm_setup(){
 $p=get_page_by_path('producer-crm');
 if(!$p){$id=wp_insert_post(array('post_title'=>'Client CRM','post_name'=>'producer-crm','post_status'=>'publish','post_type'=>'page','post_content'=>''));if(!is_wp_error($id)&&$id)update_post_meta($id,'_wp_page_template','page-producer-crm.php');}
 else update_post_meta($p->ID,'_wp_page_template','page-producer-crm.php');
}
add_action('init','tuff_beatz_crm_setup',35);
function tuff_beatz_crm_assets(){if(is_page('producer-crm')){$p=get_template_directory().'/assets/css/client-crm.css';wp_enqueue_style('tuff-beatz-client-crm',get_template_directory_uri().'/assets/css/client-crm.css',array('tuff-beatz-portal-hubs'),file_exists($p)?filemtime($p):wp_get_theme()->get('Version'));}}
add_action('wp_enqueue_scripts','tuff_beatz_crm_assets',55);
function tuff_beatz_crm_client_projects($uid){$q=new WP_Query(array('post_type'=>'tb_request','post_status'=>'publish','author'=>(int)$uid,'posts_per_page'=>200,'orderby'=>'date','order'=>'DESC'));return $q->posts;}
function tuff_beatz_crm_project_value($id){if(function_exists('tuff_beatz_quote_data')&&function_exists('tuff_beatz_quote_totals')){$q=tuff_beatz_quote_data($id);if($q){$t=tuff_beatz_quote_totals($q);return (float)($t['total']??0);}}return 0;}
function tuff_beatz_crm_project_paid($id){if(function_exists('tuff_beatz_payment_totals')){$t=tuff_beatz_payment_totals($id);return (float)($t['paid']??0);}return 0;}
function tuff_beatz_crm_client_opportunities($uid,$email=''){$out=array();if(!function_exists('tuff_beatz_v14_opportunities'))return $out;$email=strtolower(trim((string)$email));foreach(tuff_beatz_v14_opportunities() as $o){$match=(int)($o['client_id']??0)===(int)$uid;if(!$match&&$email&&strtolower(trim((string)($o['contact_email']??'')))===$email)$match=true;if($match)$out[]=$o;}return $out;}
function tuff_beatz_crm_client_activity($projects,$opportunities=array()){$feed=array();foreach($projects as $p){$id=$p->ID;if(function_exists('tuff_beatz_activity_history'))$items=tuff_beatz_activity_history($id);elseif(function_exists('tuff_beatz_project_activity'))$items=tuff_beatz_project_activity($id);else $items=array();foreach(array_slice(array_reverse($items),0,20) as $a)$feed[]=array('kind'=>'project','label'=>$a['message']??'Project update','time'=>$a['time']??$p->post_modified,'project'=>$p->post_title,'id'=>$id);}
 foreach($opportunities as $o){if(!function_exists('tuff_beatz_v14_opportunity_activity'))continue;foreach(array_slice(array_reverse(tuff_beatz_v14_opportunity_activity($o['id'])),0,20) as $a)$feed[]=array('kind'=>'opportunity','label'=>$a['message']??'Opportunity update','time'=>$a['time']??'','project'=>$o['title'],'id'=>$o['id']);}usort($feed,function($a,$b){return strtotime($b['time'])<=>strtotime($a['time']);});return array_slice($feed,0,30);}
function tuff_beatz_crm_client_summary($uid){$u=get_userdata($uid);if(!$u)return array();$projects=tuff_beatz_crm_client_projects($uid);$value=0;$paid=0;$active=0;$completed=0;$files=0;$last='';foreach($projects as $p){$id=$p->ID;$value+=tuff_beatz_crm_project_value($id);$paid+=tuff_beatz_crm_project_paid($id);$s=get_post_meta($id,'_tb_request_status',true)?:'new';if($s==='completed')$completed++;elseif($s!=='declined')$active++;if(function_exists('tuff_beatz_vault_files'))$files+=count(tuff_beatz_vault_files($id));if(!$last||strtotime($p->post_modified)>strtotime($last))$last=$p->post_modified;}
 $opps=tuff_beatz_crm_client_opportunities($uid,$u->user_email);$open_opps=0;$opp_value=0;$weighted=0;$won=0;$lost=0;$next_followup='';foreach($opps as $o){if($o['stage']==='won'){$won++;continue;}if($o['stage']==='lost'){$lost++;continue;}$open_opps++;$opp_value+=(float)$o['estimated_value'];$weighted+=(float)$o['estimated_value']*((int)$o['probability']/100);if($o['followup_at']&&(!$next_followup||strtotime($o['followup_at'])<strtotime($next_followup)))$next_followup=$o['followup_at'];}
 $activity=tuff_beatz_crm_client_activity($projects,$opps);if($activity&&!empty($activity[0]['time'])&&(!$last||strtotime($activity[0]['time'])>strtotime($last)))$last=$activity[0]['time'];$relationship=$completed>=2?'Repeat Client':($completed===1?'Returning Client':($active||$open_opps?'Active Relationship':'New Client'));
 return array('user'=>$u,'projects'=>$projects,'project_count'=>count($projects),'active'=>$active,'completed'=>$completed,'value'=>$value,'paid'=>$paid,'balance'=>max(0,$value-$paid),'files'=>$files,'last'=>$last,'industry'=>get_user_meta($uid,'_tb_industry_type',true),'opportunities'=>$opps,'open_opportunities'=>$open_opps,'opportunity_value'=>$opp_value,'weighted_opportunity_value'=>$weighted,'won_opportunities'=>$won,'lost_opportunities'=>$lost,'next_followup'=>$next_followup,'relationship'=>$relationship,'activity'=>$activity,'lifetime_value'=>$paid);
}
function tuff_beatz_crm_clients(){$users=get_users(array('role__in'=>array('tb_client','tb_artist'),'orderby'=>'display_name','order'=>'ASC'));$out=array();foreach($users as $u)$out[]=tuff_beatz_crm_client_summary($u->ID);return $out;}
