<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V15.5 — Controlled Automation Policy Engine */
function tuff_beatz_v155_policy(){return array(
 array('domain'=>'INTELLIGENCE','capability'=>'Analyze recorded business/project data','mode'=>'automatic','reason'=>'Read-only analysis may run without changing business records.'),
 array('domain'=>'PLANNING','capability'=>'Generate risks, opportunities and objectives','mode'=>'automatic','reason'=>'Recommendations are advisory and do not execute mutations.'),
 array('domain'=>'EXECUTION','capability'=>'Approve/start/complete strategic initiatives','mode'=>'approval','reason'=>'V15.4 requires explicit producer action.'),
 array('domain'=>'COMMUNICATION','capability'=>'Draft client or collaborator messages','mode'=>'approval','reason'=>'Drafting may be automated; sending requires explicit approval.'),
 array('domain'=>'PIPELINE','capability'=>'Change opportunity stage or commercial value','mode'=>'approval','reason'=>'Commercial record mutations require producer approval.'),
 array('domain'=>'PRICING','capability'=>'Change quote, proposal or project price','mode'=>'manual','reason'=>'Pricing authority remains human-controlled.'),
 array('domain'=>'CONTRACT','capability'=>'Accept/sign/alter contract terms','mode'=>'manual','reason'=>'Contractual commitment must remain an explicit human action.'),
 array('domain'=>'PAYMENT','capability'=>'Record/refund/verify/move money','mode'=>'manual','reason'=>'Financial mutations and money movement are never autonomous.'),
 array('domain'=>'DELIVERY','capability'=>'Confirm final client delivery acceptance','mode'=>'manual','reason'=>'Final acceptance remains bound to authorized client/owner confirmation.'),
 array('domain'=>'ACCESS','capability'=>'Change users, roles or project permissions','mode'=>'manual','reason'=>'Identity and authorization changes are security-sensitive.'),
 array('domain'=>'FILES','capability'=>'Delete/archive protected release assets','mode'=>'blocked','reason'=>'Protected release-history assets must not be removed by automation.'),
 array('domain'=>'SYSTEM','capability'=>'Deploy code or alter production configuration','mode'=>'manual','reason'=>'Production changes require explicit operator control and deployment verification.')
 );}
function tuff_beatz_v155_mode($domain,$capability=''){foreach(tuff_beatz_v155_policy() as $p)if($p['domain']===$domain&&(!$capability||$p['capability']===$capability))return $p['mode'];return 'manual';}
function tuff_beatz_v155_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$p=tuff_beatz_v155_policy();$counts=array('automatic'=>0,'approval'=>0,'manual'=>0,'blocked'=>0);foreach($p as $r)$counts[$r['mode']]++;ob_start();?><section class="tb-v155-policy"><div class="tb-v155-head"><div><small>CONTROLLED AUTOMATION • V15.5</small><h3>Automation Authority Matrix</h3><p>Defines what the Studio OS may analyze automatically, what requires approval, what remains manual, and what automation is prohibited from doing.</p></div><div class="tb-v155-counts"><span><b><?php echo $counts['automatic'];?></b>AUTO</span><span><b><?php echo $counts['approval'];?></b>APPROVAL</span><span><b><?php echo $counts['manual'];?></b>MANUAL</span><span><b><?php echo $counts['blocked'];?></b>BLOCKED</span></div></div><div class="tb-v155-list"><?php foreach($p as $r):?><article class="mode-<?php echo esc_attr($r['mode']);?>"><div><small><?php echo esc_html($r['domain']);?></small><strong><?php echo esc_html($r['capability']);?></strong><p><?php echo esc_html($r['reason']);?></p></div><b><?php echo esc_html(strtoupper($r['mode']));?></b></article><?php endforeach;?></div><p class="tb-v155-foot">This policy is a control boundary for future automation. V15.5 itself does not execute commercial, financial, contractual, access-control, delivery or production mutations.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var a=document.querySelector('.tb-v154-exec');if(!a||document.querySelector('.tb-v155-policy'))return;var b=document.createElement('div');b.innerHTML=<?php echo wp_json_encode($html);?>;a.insertAdjacentElement('afterend',b.firstElementChild);var e=document.querySelector('.tb-biz-hero .eyebrow');if(e)e.textContent='TUFF BEATZ • CONTROLLED AUTOMATION V15.5';});</script><?php }
add_action('wp_footer','tuff_beatz_v155_panel',21);
function tuff_beatz_v155_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v155-policy{margin-top:18px;padding:22px;border:1px solid rgba(216,180,90,.19);border-radius:18px;background:#090909}.tb-v155-head{display:flex;justify-content:space-between;gap:20px;align-items:center}.tb-v155-head small{color:#a48748;font-size:.52rem;letter-spacing:.14em}.tb-v155-head h3{margin:4px 0;color:#e1d6c2;font-family:Cinzel,serif}.tb-v155-head p,.tb-v155-foot{color:#756d61;font-size:.55rem;line-height:1.5}.tb-v155-counts{display:flex;gap:6px}.tb-v155-counts span{min-width:55px;padding:8px;border:1px solid rgba(255,255,255,.06);border-radius:9px;color:#716857;text-align:center;font-size:.42rem}.tb-v155-counts b{display:block;color:#c7aa5d;font:1rem Cinzel,serif}.tb-v155-list{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:14px}.tb-v155-list article{display:flex;justify-content:space-between;gap:12px;padding:12px;border:1px solid rgba(255,255,255,.05);border-radius:10px}.tb-v155-list small{display:block;color:#8e7748;font-size:.44rem}.tb-v155-list strong{display:block;margin-top:3px;color:#d5cbb9;font-size:.62rem}.tb-v155-list p{margin:4px 0 0;color:#756d62;font-size:.5rem;line-height:1.4}.tb-v155-list article>b{align-self:flex-start;color:#b89d58;font-size:.45rem;letter-spacing:.06em}.tb-v155-list .mode-blocked{border-color:rgba(216,180,90,.22)}.tb-v155-foot{margin:10px 0 0}@media(max-width:780px){.tb-v155-head{align-items:flex-start;flex-direction:column}.tb-v155-list{grid-template-columns:1fr}.tb-v155-counts{flex-wrap:wrap}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v155_css',117);
