<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Delivery Engine V13.7 — final-only immutable release manifests + exact acceptance audit */
function tuff_beatz_delivery_manifest($id){$m=get_post_meta((int)$id,'_tb_delivery_manifest_v12',true);return is_array($m)?$m:array();}
function tuff_beatz_delivery_manifest_history($id){$h=get_post_meta((int)$id,'_tb_delivery_manifest_history_v137',true);return is_array($h)?$h:array();}
function tuff_beatz_delivery_release_assets($id){$out=array();foreach(function_exists('tuff_beatz_vault_files')?tuff_beatz_vault_files((int)$id):array() as $f){if(!empty($f['archived']))continue;$type=function_exists('tuff_beatz_vault_asset_type')?tuff_beatz_vault_asset_type($f):'';if($type==='final')$out[]=$f;}return $out;}
function tuff_beatz_delivery_build_manifest($id,$source='Studio OS'){$id=(int)$id;$assets=tuff_beatz_delivery_release_assets($id);if(!$assets)return array();$files=array();foreach($assets as $f)$files[]=array('id'=>(string)($f['id']??''),'name'=>(string)($f['name']??''),'asset_type'=>'final','version'=>(string)($f['version']??''),'size'=>(int)($f['size']??0),'sha256'=>(string)($f['sha256']??''),'uploaded_at'=>(string)($f['uploaded_at']??''));$history=tuff_beatz_delivery_manifest_history($id);$manifest=array('manifest_id'=>wp_generate_uuid4(),'project_id'=>$id,'release_version'=>count($history)+1,'released_at'=>current_time('mysql'),'released_by'=>get_current_user_id(),'source'=>sanitize_text_field($source),'files'=>$files,'notes'=>(string)get_post_meta($id,'_tb_request_delivery_notes',true),'external_links'=>(string)get_post_meta($id,'_tb_request_final_links',true));$history[]=$manifest;add_post_meta($id,'_tb_delivery_manifest_history_entry_v137',$manifest,false);update_post_meta($id,'_tb_delivery_manifest_history_v137',$history);update_post_meta($id,'_tb_delivery_manifest_v12',$manifest);update_post_meta($id,'_tb_delivery_released_at',$manifest['released_at']);update_post_meta($id,'_tb_delivery_released_by',$manifest['released_by']);if(function_exists('tuff_beatz_add_activity'))tuff_beatz_add_activity($id,'delivery','Final delivery package released — manifest '.$manifest['manifest_id'].' v'.$manifest['release_version']);return $manifest;}
function tuff_beatz_delivery_asset_event($id,$added,$category='source',$version='',$asset_type=''){if(!$id||!$added)return;$has_final=false;foreach((array)$added as $f){$type=function_exists('tuff_beatz_vault_asset_type')?tuff_beatz_vault_asset_type($f):'';if($type==='final'){$has_final=true;break;}}if($has_final)tuff_beatz_delivery_build_manifest($id,'Canonical Final Asset Upload');}
add_action('tuff_beatz_vault_files_added','tuff_beatz_delivery_asset_event',35,5);
function tuff_beatz_delivery_acceptance_record($id){$a=get_post_meta((int)$id,'_tb_delivery_acceptance_v12',true);return is_array($a)?$a:array();}
function tuff_beatz_delivery_acceptance_history($id){$h=get_post_meta((int)$id,'_tb_delivery_acceptance_history_v137',true);return is_array($h)?$h:array();}
function tuff_beatz_delivery_capture_acceptance($meta_id,$object_id,$meta_key,$meta_value){if($meta_key!=='_tb_delivery_confirmed_at'||get_post_type($object_id)!=='tb_request'||!$meta_value)return;$manifest=tuff_beatz_delivery_manifest($object_id);if(empty($manifest['manifest_id'])||empty($manifest['files']))return;$existing=tuff_beatz_delivery_acceptance_record($object_id);if(!empty($existing['manifest_id'])&&hash_equals((string)$existing['manifest_id'],(string)$manifest['manifest_id'])&&(int)($existing['release_version']??0)===(int)($manifest['release_version']??0))return;$uid=(int)get_post_meta($object_id,'_tb_delivery_confirmed_by',true);$u=$uid?get_userdata($uid):null;$record=array('acceptance_id'=>wp_generate_uuid4(),'project_id'=>(int)$object_id,'manifest_id'=>(string)$manifest['manifest_id'],'release_version'=>(int)$manifest['release_version'],'accepted_by'=>$uid,'accepted_name'=>$u?$u->display_name:'Client','accepted_at'=>(string)$meta_value,'status'=>'accepted');$history=tuff_beatz_delivery_acceptance_history($object_id);$history[]=$record;add_post_meta($object_id,'_tb_delivery_acceptance_history_entry_v137',$record,false);update_post_meta($object_id,'_tb_delivery_acceptance_history_v137',$history);update_post_meta($object_id,'_tb_delivery_acceptance_v12',$record);if(function_exists('tuff_beatz_add_activity'))tuff_beatz_add_activity($object_id,'delivery','Delivery acceptance recorded — '.$record['acceptance_id'].' for manifest '.$record['manifest_id'].' v'.$record['release_version'],$uid);}
add_action('added_post_meta','tuff_beatz_delivery_capture_acceptance',60,4);add_action('updated_post_meta','tuff_beatz_delivery_capture_acceptance',60,4);
function tuff_beatz_delivery_audit($id){return array('manifest'=>tuff_beatz_delivery_manifest($id),'manifest_history'=>tuff_beatz_delivery_manifest_history($id),'acceptance'=>tuff_beatz_delivery_acceptance_record($id),'acceptance_history'=>tuff_beatz_delivery_acceptance_history($id),'released_at'=>(string)get_post_meta((int)$id,'_tb_delivery_released_at',true),'released_by'=>(int)get_post_meta((int)$id,'_tb_delivery_released_by',true),'confirmed_at'=>(string)get_post_meta((int)$id,'_tb_delivery_confirmed_at',true),'confirmed_by'=>(int)get_post_meta((int)$id,'_tb_delivery_confirmed_by',true));}
function tuff_beatz_delivery_engine_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||!function_exists('tuff_beatz_user_can_view_request')||!tuff_beatz_user_can_view_request($id))return;$m=tuff_beatz_delivery_manifest($id);$a=tuff_beatz_delivery_acceptance_record($id);if(!$m)return;$accepted=!empty($a['manifest_id'])&&hash_equals((string)$a['manifest_id'],(string)($m['manifest_id']??''))&&(int)($a['release_version']??0)===(int)($m['release_version']??0);$count=count($m['files']??array());?><script>document.addEventListener('DOMContentLoaded',function(){var d=document.getElementById('delivery');if(!d)return;var box=document.createElement('section');box.className='tb-delivery-manifest';box.innerHTML=<?php echo wp_json_encode('<div class="tb-delivery-manifest-head"><div><small>OFFICIAL RELEASE PACKAGE</small><h3>Delivery Manifest</h3></div><span>V'.esc_html((string)($m['release_version']??1)).'</span></div><div class="tb-delivery-manifest-grid"><div><strong>'.esc_html((string)$count).'</strong><small>FINAL ASSETS</small></div><div><strong>'.esc_html(mysql2date('M j, Y',($m['released_at']??current_time('mysql')))).'</strong><small>RELEASED</small></div><div><strong>'.esc_html($accepted?'ACCEPTED':'PENDING').'</strong><small>CLIENT ACCEPTANCE</small></div></div><p class="tb-delivery-manifest-id">Manifest '.esc_html((string)($m['manifest_id']??'')).'</p>');?>;var hero=d.querySelector('.tb-delivery-hero');if(hero)hero.insertAdjacentElement('afterend',box);else d.insertBefore(box,d.firstChild);});</script><?php }
add_action('wp_footer','tuff_beatz_delivery_engine_workspace',28);
function tuff_beatz_delivery_engine_assets(){if(!is_page('project-dashboard'))return;$css='.tb-delivery-manifest{margin:18px 0;padding:20px;border:1px solid rgba(216,180,90,.2);border-radius:18px;background:linear-gradient(145deg,rgba(216,180,90,.055),rgba(255,255,255,.018))}.tb-delivery-manifest-head{display:flex;align-items:center;justify-content:space-between;gap:20px}.tb-delivery-manifest-head small,.tb-delivery-manifest-grid small{display:block;color:#8f8675;font-size:.58rem;letter-spacing:.15em}.tb-delivery-manifest-head h3{margin:5px 0 0;color:#f0dfaa;font-family:Cinzel,serif}.tb-delivery-manifest-head>span{border:1px solid rgba(216,180,90,.3);border-radius:999px;padding:6px 10px;color:#e7c96d;font-size:.65rem}.tb-delivery-manifest-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}.tb-delivery-manifest-grid>div{padding:12px;border:1px solid rgba(255,255,255,.06);border-radius:12px;background:rgba(0,0,0,.16)}.tb-delivery-manifest-grid strong{display:block;color:#eee5d2;font-size:.82rem;margin-bottom:3px}.tb-delivery-manifest-id{margin:13px 0 0;color:#706a60;font-size:.58rem;word-break:break-all}@media(max-width:700px){.tb-delivery-manifest-grid{grid-template-columns:1fr}}';wp_add_inline_style('tuff-beatz-project-portal',$css);}
add_action('wp_enqueue_scripts','tuff_beatz_delivery_engine_assets',97);
