<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V13.7 — safe notification and activity deduplication */
function tuff_beatz_event_signature($parts){$clean=array();foreach((array)$parts as $p)$clean[]=strtolower(trim(preg_replace('/\s+/',' ',wp_strip_all_tags((string)$p))));return hash('sha256',implode('|',$clean));}
function tuff_beatz_notification_item_signature($item){return tuff_beatz_event_signature(array($item['type']??'',$item['title']??'',$item['message']??'',implode(',',array_map('intval',(array)($item['recipient_ids']??array())))));}
function tuff_beatz_notification_duplicate($id,$item,$window=8){$sig=tuff_beatz_notification_item_signature($item);$now=current_time('timestamp');foreach(array_reverse(function_exists('tuff_beatz_notifications')?tuff_beatz_notifications($id):array()) as $old){if(!hash_equals($sig,tuff_beatz_notification_item_signature($old)))continue;$t=!empty($old['time'])?strtotime($old['time']):0;if($t&&abs($now-$t)<=$window)return true;}return false;}
function tuff_beatz_notification_dedupe_after_write($meta_id,$object_id,$meta_key,$meta_value){if($meta_key!=='_tb_notifications_v9'||get_post_type($object_id)!=='tb_request'||!is_array($meta_value)||count($meta_value)<2)return;static $busy=false;if($busy)return;$last=end($meta_value);if(!is_array($last))return;$prior=array_slice($meta_value,0,-1);$sig=tuff_beatz_notification_item_signature($last);$lt=!empty($last['time'])?strtotime($last['time']):current_time('timestamp');$duplicate=false;foreach(array_reverse($prior) as $old){if(!is_array($old)||!hash_equals($sig,tuff_beatz_notification_item_signature($old)))continue;$ot=!empty($old['time'])?strtotime($old['time']):0;if($ot&&abs($lt-$ot)<=8){$duplicate=true;break;}}if(!$duplicate)return;$busy=true;update_post_meta($object_id,$meta_key,$prior);$busy=false;}
add_action('added_post_meta','tuff_beatz_notification_dedupe_after_write',5,4);add_action('updated_post_meta','tuff_beatz_notification_dedupe_after_write',5,4);
function tuff_beatz_activity_deduplicated_history($id){$raw=function_exists('tuff_beatz_project_activity')?tuff_beatz_project_activity((int)$id):array();$seen=array();$out=array();foreach($raw as $item){$time=(string)($item['time']??'');$bucket=$time?substr($time,0,16):'';$sig=tuff_beatz_event_signature(array($item['type']??'update',$item['message']??'Project update',$item['user_id']??0,$bucket));if(isset($seen[$sig]))continue;$seen[$sig]=1;$out[]=$item;}return $out;}
function tuff_beatz_event_dedupe_report($id){$notifications=function_exists('tuff_beatz_notifications')?tuff_beatz_notifications($id):array();$activity=function_exists('tuff_beatz_project_activity')?tuff_beatz_project_activity($id):array();$deduped=tuff_beatz_activity_deduplicated_history($id);return array('notification_count'=>count($notifications),'activity_raw_count'=>count($activity),'activity_unique_count'=>count($deduped),'activity_duplicates_hidden'=>max(0,count($activity)-count($deduped)));}
