<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V13.1 — canonical project authorization boundaries */
function tuff_beatz_auth_is_producer($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return $user_id&&user_can($user_id,'edit_post',(int)$request_id);}
function tuff_beatz_auth_is_owner($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();$p=get_post((int)$request_id);return $user_id&&$p&&$p->post_type==='tb_request'&&(int)$p->post_author===(int)$user_id;}
function tuff_beatz_auth_collaborator($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return function_exists('tuff_beatz_find_collaborator')?tuff_beatz_find_collaborator((int)$request_id,(int)$user_id):null;}
function tuff_beatz_auth_can($request_id,$permission='view',$user_id=0){$request_id=(int)$request_id;$user_id=$user_id?:get_current_user_id();if(!$request_id||!$user_id)return false;if(tuff_beatz_auth_is_producer($request_id,$user_id)||tuff_beatz_auth_is_owner($request_id,$user_id))return true;$c=tuff_beatz_auth_collaborator($request_id,$user_id);if(!$c)return false;$allowed=array('view','upload','message','review','approve','billing');if(!in_array($permission,$allowed,true))return false;$perms=array_values(array_intersect(array_map('sanitize_key',(array)($c['permissions']??array())),$allowed));return in_array($permission,$perms,true);}
function tuff_beatz_auth_can_manage_project($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return tuff_beatz_auth_is_producer($request_id,$user_id)||tuff_beatz_auth_is_owner($request_id,$user_id);}
function tuff_beatz_auth_can_manage_files($request_id,$user_id=0){return tuff_beatz_auth_is_producer($request_id,$user_id);}
function tuff_beatz_auth_can_accept_delivery($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return tuff_beatz_auth_is_owner($request_id,$user_id)&&!tuff_beatz_auth_is_producer($request_id,$user_id);}
function tuff_beatz_auth_action_policy(){return array('tb_file_manager_upload'=>'upload','tb_conversation_send'=>'message','tb_submit_mix_review'=>'review','tb_approve_mix'=>'approve');}
function tuff_beatz_auth_endpoint_guard(){if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;$action=sanitize_key($_POST['action']??'');$policy=tuff_beatz_auth_action_policy();if(!isset($policy[$action]))return;$id=(int)($_POST['request_id']??0);if(!$id||!is_user_logged_in()||!tuff_beatz_auth_can($id,$policy[$action])){$url=$id&&function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id):home_url('/client-portal/');wp_safe_redirect(add_query_arg('permission_blocked',$policy[$action],$url));exit;}}
add_action('admin_init','tuff_beatz_auth_endpoint_guard',0);
function tuff_beatz_auth_manage_endpoint_guard(){if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;$action=sanitize_key($_POST['action']??'');$id=(int)($_POST['request_id']??0);if(!$id)return;$producer_only=array('tb_file_manager_update','tb_file_manager_archive','tb_file_manager_delete');if(in_array($action,$producer_only,true)&&!tuff_beatz_auth_can_manage_files($id)){$url=function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id).'#files':home_url('/producer-portal/');wp_safe_redirect(add_query_arg('permission_blocked','producer',$url));exit;}$owner_manage=array('tb_invite_project_collaborator','tb_remove_project_collaborator');if(in_array($action,$owner_manage,true)&&!tuff_beatz_auth_can_manage_project($id)){$url=function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id).'#collaborators':home_url('/client-portal/');wp_safe_redirect(add_query_arg('permission_blocked','manage',$url));exit;}}
add_action('admin_init','tuff_beatz_auth_manage_endpoint_guard',0);
function tuff_beatz_auth_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id)return;$blocked=sanitize_key(wp_unslash($_GET['permission_blocked']??''));$matrix=array('view'=>tuff_beatz_auth_can($id,'view'),'upload'=>tuff_beatz_auth_can($id,'upload'),'message'=>tuff_beatz_auth_can($id,'message'),'review'=>tuff_beatz_auth_can($id,'review'),'approve'=>tuff_beatz_auth_can($id,'approve'),'billing'=>tuff_beatz_auth_can($id,'billing'),'manage'=>tuff_beatz_auth_can_manage_project($id),'producer'=>tuff_beatz_auth_is_producer($id),'owner'=>tuff_beatz_auth_is_owner($id));?><script>window.TB_AUTH_MATRIX=<?php echo wp_json_encode($matrix);?>;document.addEventListener('DOMContentLoaded',function(){var p=window.TB_AUTH_MATRIX||{};if(!p.upload)document.querySelectorAll('.tb-dashboard-upload,.tb-fm-upload').forEach(function(x){x.remove();});if(!p.message)document.querySelectorAll('.tb-message-form,.tb-conversation-compose').forEach(function(x){x.remove();});if(!p.review)document.querySelectorAll('.tb-review-form').forEach(function(x){x.remove();});if(!p.approve)document.querySelectorAll('.tb-approve-form').forEach(function(x){x.remove();});<?php if($blocked):?>var root=document.querySelector('.tb-project-dashboard')||document.querySelector('main');if(root){var n=document.createElement('div');n.className='tb-permission-alert';n.textContent='Studio OS blocked this action because your project role does not include the required permission.';root.insertBefore(n,root.firstChild);}<?php endif;?>});</script><?php }
add_action('wp_footer','tuff_beatz_auth_workspace',2);
function tuff_beatz_auth_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-permission-alert{margin:12px auto 18px;max-width:1180px;padding:13px 16px;border:1px solid rgba(216,180,90,.25);border-radius:12px;background:rgba(216,180,90,.05);color:#d8c79b;font-size:.72rem}');}
add_action('wp_enqueue_scripts','tuff_beatz_auth_assets',100);
