<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V13.7.1 — canonical project authorization boundaries + reconciled mutation endpoint policy */
function tuff_beatz_auth_is_producer($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return $user_id&&user_can($user_id,'edit_post',(int)$request_id);}
function tuff_beatz_auth_is_owner($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();$p=get_post((int)$request_id);return $user_id&&$p&&$p->post_type==='tb_request'&&(int)$p->post_author===(int)$user_id;}
function tuff_beatz_auth_collaborator($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return function_exists('tuff_beatz_find_collaborator')?tuff_beatz_find_collaborator((int)$request_id,(int)$user_id):null;}
function tuff_beatz_auth_can($request_id,$permission='view',$user_id=0){$request_id=(int)$request_id;$user_id=$user_id?:get_current_user_id();if(!$request_id||!$user_id)return false;if(tuff_beatz_auth_is_producer($request_id,$user_id)||tuff_beatz_auth_is_owner($request_id,$user_id))return true;$c=tuff_beatz_auth_collaborator($request_id,$user_id);if(!$c)return false;$allowed=array('view','upload','message','review','approve','billing');if(!in_array($permission,$allowed,true))return false;$perms=array_values(array_intersect(array_map('sanitize_key',(array)($c['permissions']??array())),$allowed));return in_array($permission,$perms,true);}
function tuff_beatz_auth_can_manage_project($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return tuff_beatz_auth_is_producer($request_id,$user_id)||tuff_beatz_auth_is_owner($request_id,$user_id);}
function tuff_beatz_auth_can_manage_files($request_id,$user_id=0){return tuff_beatz_auth_is_producer($request_id,$user_id);}
function tuff_beatz_auth_can_accept_delivery($request_id,$user_id=0){$user_id=$user_id?:get_current_user_id();return tuff_beatz_auth_is_owner($request_id,$user_id)&&!tuff_beatz_auth_is_producer($request_id,$user_id);}
function tuff_beatz_auth_action_policy(){return array(
 'tb_file_manager_upload'=>'upload',
 'tb_conversation_send'=>'message',
 'tb_submit_project_message'=>'message',
 'tb_conversation_mark_read'=>'view',
 'tb_submit_mix_review'=>'review',
 'tb_approve_mix'=>'approve',
 'tb_upload_project_dashboard_files'=>'upload'
);}
function tuff_beatz_auth_producer_actions(){return array('tb_file_manager_update','tb_file_manager_archive','tb_file_manager_delete','tb_admin_upload_delivery_files','tb_producer_console_upload','tb_add_project_payment');}
function tuff_beatz_auth_manage_actions(){return array('tb_invite_project_collaborator','tb_remove_project_collaborator');}
function tuff_beatz_auth_owner_actions(){return array('tb_confirm_final_delivery');}
function tuff_beatz_auth_request_id(){return (int)($_POST['request_id']??$_GET['request_id']??0);}
function tuff_beatz_auth_redirect_blocked($id,$reason,$anchor=''){$url=$id&&function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id):home_url('/client-portal/');if($anchor)$url.='#'.$anchor;wp_safe_redirect(add_query_arg('permission_blocked',sanitize_key($reason),$url));exit;}
function tuff_beatz_auth_endpoint_guard(){if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;$action=sanitize_key($_POST['action']??'');if(!$action)return;$id=tuff_beatz_auth_request_id();$policy=tuff_beatz_auth_action_policy();if(isset($policy[$action])){if(!$id||!is_user_logged_in()||!tuff_beatz_auth_can($id,$policy[$action]))tuff_beatz_auth_redirect_blocked($id,$policy[$action]);return;}if(in_array($action,tuff_beatz_auth_producer_actions(),true)){if(!$id||!is_user_logged_in()||!tuff_beatz_auth_can_manage_files($id))tuff_beatz_auth_redirect_blocked($id,'producer','files');return;}if(in_array($action,tuff_beatz_auth_manage_actions(),true)){if(!$id||!is_user_logged_in()||!tuff_beatz_auth_can_manage_project($id))tuff_beatz_auth_redirect_blocked($id,'manage','collaborators');return;}if(in_array($action,tuff_beatz_auth_owner_actions(),true)){if(!$id||!is_user_logged_in()||!tuff_beatz_auth_can_accept_delivery($id))tuff_beatz_auth_redirect_blocked($id,'owner','delivery');return;}}
add_action('admin_init','tuff_beatz_auth_endpoint_guard',0);
function tuff_beatz_auth_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id)return;$blocked=sanitize_key(wp_unslash($_GET['permission_blocked']??''));$matrix=array('view'=>tuff_beatz_auth_can($id,'view'),'upload'=>tuff_beatz_auth_can($id,'upload'),'message'=>tuff_beatz_auth_can($id,'message'),'review'=>tuff_beatz_auth_can($id,'review'),'approve'=>tuff_beatz_auth_can($id,'approve'),'billing'=>tuff_beatz_auth_can($id,'billing'),'manage'=>tuff_beatz_auth_can_manage_project($id),'producer'=>tuff_beatz_auth_is_producer($id),'owner'=>tuff_beatz_auth_is_owner($id));?><script>window.TB_AUTH_MATRIX=<?php echo wp_json_encode($matrix);?>;document.addEventListener('DOMContentLoaded',function(){var p=window.TB_AUTH_MATRIX||{};if(!p.upload)document.querySelectorAll('.tb-dashboard-upload,.tb-fm-upload').forEach(function(x){x.remove();});if(!p.message)document.querySelectorAll('.tb-message-form,.tb-conversation-compose').forEach(function(x){x.remove();});if(!p.review)document.querySelectorAll('.tb-review-form').forEach(function(x){x.remove();});if(!p.approve)document.querySelectorAll('.tb-approve-form').forEach(function(x){x.remove();});<?php if($blocked):?>var root=document.querySelector('.tb-project-dashboard')||document.querySelector('main');if(root){var n=document.createElement('div');n.className='tb-permission-alert';n.textContent='Studio OS blocked this action because your project role does not include the required permission.';root.insertBefore(n,root.firstChild);}<?php endif;?>});</script><?php }
add_action('wp_footer','tuff_beatz_auth_workspace',2);
function tuff_beatz_auth_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-permission-alert{margin:12px auto 18px;max-width:1180px;padding:13px 16px;border:1px solid rgba(216,180,90,.25);border-radius:12px;background:rgba(216,180,90,.05);color:#d8c79b;font-size:.72rem}');}
add_action('wp_enqueue_scripts','tuff_beatz_auth_assets',100);
