<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.9 — Producer-facing production verification summary. Read-only synthesis; not browser/runtime certification. */
function tuff_beatz_v169_summary($id){
 $gate=function_exists('tuff_beatz_v163_readiness_gate')?tuff_beatz_v163_readiness_gate($id):array();
 $snapshots=function_exists('tuff_beatz_v164_snapshot_history')?tuff_beatz_v164_snapshot_history($id):array();$snapshot=$snapshots?end($snapshots):array();
 $cert_state=function_exists('tuff_beatz_v167_certification_state')?tuff_beatz_v167_certification_state($id):array('state'=>'none','label'=>'NO CERTIFICATION');
 $ledger=function_exists('tuff_beatz_v168_evidence_ledger')?tuff_beatz_v168_evidence_ledger($id):array();$ledger_issues=function_exists('tuff_beatz_v168_ledger_integrity')?tuff_beatz_v168_ledger_integrity($id,$ledger):array();
 $scenarios=function_exists('tuff_beatz_v161_scenarios')?tuff_beatz_v161_scenarios($id):array();$verified=0;$attention=0;$pending=0;foreach((array)$scenarios as $s){$state=(string)($s['state']??'pending');if($state==='verified')$verified++;elseif($state==='attention')$attention++;else$pending++;}
 $anomalies=function_exists('tuff_beatz_v162_anomalies')?tuff_beatz_v162_anomalies($id):array();$critical=0;$high=0;foreach($anomalies as $a){$sev=(string)($a['severity']??'');if($sev==='critical')$critical++;elseif($sev==='high')$high++;}
 $manifest=function_exists('tuff_beatz_delivery_manifest')?tuff_beatz_delivery_manifest($id):array();$acceptance=function_exists('tuff_beatz_delivery_acceptance_record')?tuff_beatz_delivery_acceptance_record($id):array();
 return array('version'=>'16.9','gate'=>sanitize_key($gate['verdict']??'attention'),'gate_counts'=>(array)($gate['counts']??array()),'snapshot_id'=>(string)($snapshot['snapshot_id']??''),'snapshot_verdict'=>sanitize_key($snapshot['verdict']??''),'certification_state'=>sanitize_key($cert_state['state']??'none'),'certification_label'=>(string)($cert_state['label']??'NO CERTIFICATION'),'scenario_verified'=>$verified,'scenario_attention'=>$attention,'scenario_pending'=>$pending,'anomaly_critical'=>$critical,'anomaly_high'=>$high,'ledger_records'=>count($ledger),'ledger_issues'=>count($ledger_issues),'manifest_id'=>(string)($manifest['manifest_id']??''),'release_version'=>(int)($manifest['release_version']??0),'acceptance_id'=>(string)($acceptance['acceptance_id']??''),'checked_at'=>current_time('mysql'));
}
function tuff_beatz_v169_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request'||!current_user_can('edit_post',$id))return;$s=tuff_beatz_v169_summary($id);?><script>document.addEventListener('DOMContentLoaded',function(){var anchor=document.querySelector('.tb-v16-verification');if(!anchor)return;var box=document.createElement('section');box.className='tb-v169-summary is-<?php echo esc_attr($s['gate']);?>';box.innerHTML=<?php ob_start();?><div class="tb-v169-head"><div><small>V16.9 • PRODUCTION VERIFICATION CONTROL</small><strong>Verification Summary</strong><span>Observational code-level synthesis • <?php echo esc_html($s['checked_at']);?></span></div><b><?php echo esc_html(strtoupper($s['gate']));?></b></div><div class="tb-v169-grid"><div><strong><?php echo esc_html((string)$s['scenario_verified']);?></strong><small>SCENARIOS VERIFIED</small><span><?php echo esc_html((string)$s['scenario_attention']);?> attention • <?php echo esc_html((string)$s['scenario_pending']);?> pending</span></div><div><strong><?php echo esc_html((string)($s['anomaly_critical']+$s['anomaly_high']));?></strong><small>HIGH-RISK FINDINGS</small><span><?php echo esc_html((string)$s['anomaly_critical']);?> critical • <?php echo esc_html((string)$s['anomaly_high']);?> high</span></div><div><strong><?php echo esc_html($s['snapshot_id']?'CAPTURED':'NONE');?></strong><small>LATEST SNAPSHOT</small><span><?php echo esc_html(strtoupper($s['snapshot_verdict']?:'none'));?></span></div><div><strong><?php echo esc_html($s['certification_label']);?></strong><small>INTERNAL CERTIFICATION</small><span><?php echo esc_html(strtoupper(str_replace('_',' ',$s['certification_state'])));?></span></div><div><strong><?php echo esc_html((string)$s['ledger_records']);?></strong><small>EVIDENCE RECORDS</small><span><?php echo esc_html((string)$s['ledger_issues']);?> ledger integrity issue(s)</span></div><div><strong><?php echo esc_html($s['manifest_id']?'V'.$s['release_version']:'NONE');?></strong><small>FINAL RELEASE</small><span><?php echo esc_html($s['acceptance_id']?'CLIENT ACCEPTED':'Acceptance not recorded');?></span></div></div><p class="tb-v169-note">READY here is not browser-level, third-party, legal, regulatory, or cryptographic certification. Runtime/browser smoke testing remains a separate verification step.</p><?php $html=ob_get_clean();echo wp_json_encode($html);?>;anchor.insertAdjacentElement('beforebegin',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v169_workspace',6);
function tuff_beatz_v169_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v169-summary{margin:0 0 12px;padding:15px;border:1px solid rgba(216,180,90,.18);border-radius:12px;background:linear-gradient(145deg,rgba(216,180,90,.045),rgba(255,255,255,.012))}.tb-v169-head{display:flex;align-items:center;justify-content:space-between;gap:14px}.tb-v169-head small,.tb-v169-head strong,.tb-v169-head span{display:block}.tb-v169-head small{color:#8d7b50;font-size:.48rem;letter-spacing:.14em}.tb-v169-head strong{color:#e0d5bd;font-size:.75rem;margin-top:3px}.tb-v169-head span{color:#655f55;font-size:.46rem;margin-top:2px}.tb-v169-head b{font-size:.56rem;letter-spacing:.12em;color:#c5a654;border:1px solid rgba(216,180,90,.3);border-radius:999px;padding:6px 9px}.tb-v169-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.tb-v169-grid>div{padding:9px;border:1px solid rgba(255,255,255,.045);border-radius:8px;background:rgba(0,0,0,.13)}.tb-v169-grid strong,.tb-v169-grid small,.tb-v169-grid span{display:block}.tb-v169-grid strong{color:#cfc5b2;font-size:.58rem}.tb-v169-grid small{color:#807765;font-size:.44rem;letter-spacing:.09em;margin-top:2px}.tb-v169-grid span{color:#625d54;font-size:.44rem;margin-top:3px}.tb-v169-note{margin:10px 0 0;color:#655f55;font-size:.47rem}.tb-v169-summary.is-blocked .tb-v169-head b{border-width:2px}@media(max-width:760px){.tb-v169-grid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.tb-v169-grid{grid-template-columns:1fr}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v169_assets',111);
