<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V13.7 — production hardening + release-history asset locks */
function tuff_beatz_hardening_status($id){return (string)(get_post_meta((int)$id,'_tb_request_status',true)?:'new');}
function tuff_beatz_hardening_is_completed($id){return tuff_beatz_hardening_status($id)==='completed';}
function tuff_beatz_hardening_release_file_ids($id){$ids=array();$collect=function($manifest)use(&$ids){foreach((array)($manifest['files']??array()) as $f){$fid=(string)($f['id']??'');if($fid)$ids[$fid]=1;}};$current=function_exists('tuff_beatz_delivery_manifest')?tuff_beatz_delivery_manifest((int)$id):array();if($current)$collect($current);$history=function_exists('tuff_beatz_delivery_manifest_history')?tuff_beatz_delivery_manifest_history((int)$id):array();foreach((array)$history as $m)$collect($m);$acceptances=function_exists('tuff_beatz_delivery_acceptance_history')?tuff_beatz_delivery_acceptance_history((int)$id):array();foreach((array)$acceptances as $a){$mid=(string)($a['manifest_id']??'');$ver=(int)($a['release_version']??0);foreach((array)$history as $m)if($mid&&hash_equals($mid,(string)($m['manifest_id']??''))&&$ver===(int)($m['release_version']??0))$collect($m);}return array_keys($ids);}
function tuff_beatz_hardening_file_is_protected($id,$fid){$fid=(string)$fid;if(in_array($fid,tuff_beatz_hardening_release_file_ids($id),true))return true;foreach(function_exists('tuff_beatz_vault_files')?tuff_beatz_vault_files((int)$id):array() as $f){if((string)($f['id']??'')!==$fid)continue;$type=function_exists('tuff_beatz_vault_asset_type')?tuff_beatz_vault_asset_type($f):'';if(in_array($type,array('master','final'),true))return true;if(in_array(sanitize_key($f['studio_category']??''),array('masters','final'),true))return true;if((string)get_post_meta((int)$id,'_tb_approved_mix_file',true)===$fid)return true;}return false;}
function tuff_beatz_hardening_block($anchor,$reason){$id=(int)($_POST['request_id']??0);$url=function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id).$anchor:home_url('/project-dashboard/');wp_safe_redirect(add_query_arg('studio_blocked',sanitize_key($reason),$url));exit;}
function tuff_beatz_hardening_file_mutations(){if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;$action=sanitize_key($_POST['action']??'');if(!in_array($action,array('tb_file_manager_update','tb_file_manager_archive','tb_file_manager_delete'),true))return;$id=(int)($_POST['request_id']??0);$fid=sanitize_text_field(wp_unslash($_POST['file_id']??''));if(!$id||!$fid)return;if(tuff_beatz_hardening_is_completed($id))tuff_beatz_hardening_block('#files','project-completed');if(tuff_beatz_hardening_file_is_protected($id,$fid))tuff_beatz_hardening_block('#files','protected-delivery');}
add_action('admin_init','tuff_beatz_hardening_file_mutations',1);
function tuff_beatz_hardening_project_mutations(){if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;$action=sanitize_key($_POST['action']??'');$id=(int)($_POST['request_id']??0);if(!$id||!tuff_beatz_hardening_is_completed($id))return;$allowed=array('tb_conversation_send','tb_conversation_mark_read','tb_mark_notifications_read');if(in_array($action,$allowed,true))return;$protected=array('tb_file_manager_upload','tb_workflow_transition','tb_submit_mix_review','tb_approve_mix','tb_confirm_final_delivery');if(in_array($action,$protected,true))tuff_beatz_hardening_block('#overview','project-completed');}
add_action('admin_init','tuff_beatz_hardening_project_mutations',2);
function tuff_beatz_hardening_workflow_lock($meta_id,$object_id,$meta_key,$meta_value){if($meta_key!=='_tb_request_status'||get_post_type($object_id)!=='tb_request')return;$confirmed=(string)get_post_meta($object_id,'_tb_delivery_confirmed_at',true);if(!$confirmed)return;if((string)$meta_value==='completed')return;static $busy=false;if($busy)return;$busy=true;update_post_meta($object_id,'_tb_request_status','completed');if(function_exists('tuff_beatz_add_activity'))tuff_beatz_add_activity($object_id,'system','V13.7 prevented a completed project from reopening without an explicit administrative recovery path.');$busy=false;}
add_action('updated_post_meta','tuff_beatz_hardening_workflow_lock',1,4);
function tuff_beatz_hardening_delivery_manifest_lock($id){$m=function_exists('tuff_beatz_delivery_manifest')?tuff_beatz_delivery_manifest($id):array();return !empty($m)&&!empty($m['manifest_id']);}
function tuff_beatz_hardening_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id)return;$blocked=sanitize_key(wp_unslash($_GET['studio_blocked']??''));$completed=tuff_beatz_hardening_is_completed($id);$manifest=tuff_beatz_hardening_delivery_manifest_lock($id);?><script>document.addEventListener('DOMContentLoaded',function(){var root=document.querySelector('.tb-project-dashboard')||document.querySelector('main');if(!root)return;<?php if($blocked):?>var a=document.createElement('div');a.className='tb-hardening-alert';a.textContent=<?php echo wp_json_encode($blocked==='protected-delivery'?'Release, Master, Final, accepted-manifest, and approved-mix assets are locked against metadata changes, archive, or deletion.':($blocked==='project-completed'?'This project is completed and production-changing actions are locked.':'Studio OS blocked this action to protect project integrity.'));?>;root.insertBefore(a,root.firstChild);<?php endif;?><?php if($completed):?>document.body.classList.add('tb-project-is-locked');document.querySelectorAll('.tb-fm-upload,.tb-workflow-action,.tb-delivery-confirm').forEach(function(x){x.remove();});<?php endif;?><?php if($manifest):?>document.body.classList.add('tb-has-release-manifest');<?php endif;?>});</script><?php }
add_action('wp_footer','tuff_beatz_hardening_workspace',1);
function tuff_beatz_hardening_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-hardening-alert{margin:12px auto 18px;max-width:1180px;padding:13px 16px;border:1px solid rgba(216,180,90,.28);border-radius:12px;background:rgba(216,180,90,.055);color:#d9c797;font-size:.72rem}.tb-project-is-locked .tb-fm-editor form[action*="admin-post"] button[type="submit"]{opacity:.55}.tb-project-is-locked #overview:before{content:"COMPLETED PROJECT • PRODUCTION LOCKED";display:block;margin-bottom:12px;color:#a98c48;font-size:.58rem;letter-spacing:.14em}');}
add_action('wp_enqueue_scripts','tuff_beatz_hardening_assets',99);
