<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.8 — Production Evidence Ledger. Read-only synthesis of append-preserving verification, certification, release and acceptance records. */
function tuff_beatz_v168_evidence_ledger($id){
 $rows=array();
 $snapshots=function_exists('tuff_beatz_v164_snapshot_history')?tuff_beatz_v164_snapshot_history($id):array();
 foreach($snapshots as $s)$rows[]=array('type'=>'verification','time'=>(string)($s['captured_at']??''),'id'=>(string)($s['snapshot_id']??''),'title'=>'Verification Snapshot','state'=>strtoupper((string)($s['verdict']??'unknown')),'detail'=>'Project '.strtoupper((string)($s['project_status']??'unknown')).' • '.(int)($s['verification']['failed']??0).' failed • '.count((array)($s['anomalies']??array())).' anomalies');
 $certs=function_exists('tuff_beatz_v166_certifications')?tuff_beatz_v166_certifications($id):array();
 foreach($certs as $c)$rows[]=array('type'=>'certification','time'=>(string)($c['certified_at']??''),'id'=>(string)($c['certification_id']??''),'title'=>'Producer Certification','state'=>'CERTIFIED','detail'=>'Snapshot '.(string)($c['snapshot_id']??'').' • internal producer attestation');
 $manifests=function_exists('tuff_beatz_delivery_manifest_history')?tuff_beatz_delivery_manifest_history($id):array();
 foreach($manifests as $m)$rows[]=array('type'=>'release','time'=>(string)($m['released_at']??''),'id'=>(string)($m['manifest_id']??''),'title'=>'Final Release Manifest','state'=>'V'.(int)($m['release_version']??0),'detail'=>count((array)($m['files']??array())).' canonical Final asset(s) • append-preserving release history');
 $acceptances=function_exists('tuff_beatz_delivery_acceptance_history')?tuff_beatz_delivery_acceptance_history($id):array();
 foreach($acceptances as $a)$rows[]=array('type'=>'acceptance','time'=>(string)($a['accepted_at']??''),'id'=>(string)($a['acceptance_id']??''),'title'=>'Client Delivery Acceptance','state'=>'ACCEPTED','detail'=>'Manifest '.(string)($a['manifest_id']??'').' V'.(int)($a['release_version']??0));
 usort($rows,function($a,$b){$ta=strtotime($a['time']?:'1970-01-01');$tb=strtotime($b['time']?:'1970-01-01');if($ta===$tb)return 0;return $ta>$tb?-1:1;});return $rows;
}
function tuff_beatz_v168_ledger_integrity($id,$rows){$issues=array();$snapshot_ids=array();$manifest_ids=array();foreach($rows as $r){if($r['type']==='verification'&&$r['id'])$snapshot_ids[$r['id']]=true;if($r['type']==='release'&&$r['id'])$manifest_ids[$r['id']]=true;}$certs=function_exists('tuff_beatz_v166_certifications')?tuff_beatz_v166_certifications($id):array();foreach($certs as $c)if(empty($snapshot_ids[(string)($c['snapshot_id']??'')]))$issues[]='Certification references a snapshot absent from the ledger.';$acceptances=function_exists('tuff_beatz_delivery_acceptance_history')?tuff_beatz_delivery_acceptance_history($id):array();foreach($acceptances as $a)if(empty($manifest_ids[(string)($a['manifest_id']??'')]))$issues[]='Acceptance references a release manifest absent from the ledger.';return array_values(array_unique($issues));}
function tuff_beatz_v168_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request'||!current_user_can('edit_post',$id))return;$rows=tuff_beatz_v168_evidence_ledger($id);if(!$rows)return;$issues=tuff_beatz_v168_ledger_integrity($id,$rows);?><script>document.addEventListener('DOMContentLoaded',function(){var host=document.querySelector('.tb-v167-integrity')||document.querySelector('.tb-v166-cert')||document.querySelector('.tb-v165-history');if(!host)return;var box=document.createElement('section');box.className='tb-v168-ledger';box.innerHTML=<?php ob_start();?><div class="tb-v168-head"><div><small>V16.8 • READ-ONLY EVIDENCE CHAIN</small><strong>Production Evidence Ledger</strong></div><span><?php echo esc_html((string)count($rows));?> RECORDS</span></div><?php if($issues):?><div class="tb-v168-alert"><?php echo esc_html(implode(' ', $issues));?></div><?php endif;?><div class="tb-v168-list"><?php foreach(array_slice($rows,0,14) as $r):?><div class="is-<?php echo esc_attr($r['type']);?>"><i></i><p><strong><?php echo esc_html($r['title']);?> <em><?php echo esc_html($r['state']);?></em></strong><span><?php echo esc_html($r['time']);?> • <?php echo esc_html($r['detail']);?></span><small><?php echo esc_html($r['id']);?></small></p></div><?php endforeach;?></div><p class="tb-v168-note">This ledger synthesizes existing records only. It does not alter workflow, releases, acceptance, verification snapshots, or certifications.</p><?php $html=ob_get_clean();echo wp_json_encode($html);?>;host.insertAdjacentElement('afterend',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v168_workspace',13);
function tuff_beatz_v168_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v168-ledger{margin-top:12px;padding:14px;border:1px solid rgba(216,180,90,.16);border-radius:11px;background:rgba(5,5,5,.42)}.tb-v168-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.tb-v168-head small{display:block;color:#8d7b50;font-size:.47rem;letter-spacing:.13em}.tb-v168-head strong{display:block;color:#d8d0bf;font-size:.68rem;margin-top:2px}.tb-v168-head>span{color:#a78d4e;font-size:.48rem;letter-spacing:.1em}.tb-v168-alert{margin-top:9px;padding:7px 9px;border-left:3px solid rgba(216,180,90,.48);color:#b8a98a;font-size:.5rem;background:rgba(216,180,90,.035)}.tb-v168-list{display:grid;gap:4px;margin-top:10px}.tb-v168-list>div{display:flex;gap:9px;padding:7px 8px;border-bottom:1px solid rgba(255,255,255,.035)}.tb-v168-list i{width:7px;height:7px;border-radius:50%;margin-top:4px;background:#746d60}.tb-v168-list .is-certification i,.tb-v168-list .is-release i,.tb-v168-list .is-acceptance i{background:#b99a4e}.tb-v168-list p{margin:0;min-width:0}.tb-v168-list strong,.tb-v168-list span,.tb-v168-list small{display:block}.tb-v168-list strong{color:#cfc5b2;font-size:.55rem}.tb-v168-list strong em{font-style:normal;color:#8d7b50;font-size:.46rem;margin-left:5px}.tb-v168-list span{color:#716a60;font-size:.48rem;margin-top:2px}.tb-v168-list small{color:#514c44;font-size:.42rem;margin-top:2px;word-break:break-all}.tb-v168-note{margin:10px 0 0;color:#655f55;font-size:.47rem}');}
add_action('wp_enqueue_scripts','tuff_beatz_v168_assets',110);
