<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.7.1 — Internal attestation integrity, freshness & supersession. Read-only; original records remain append-preserved. */
function tuff_beatz_v167_certification_state($id){
 $snapshots=function_exists('tuff_beatz_v164_snapshot_history')?tuff_beatz_v164_snapshot_history($id):array();
 $certs=function_exists('tuff_beatz_v166_certifications')?tuff_beatz_v166_certifications($id):array();
 $latest_snapshot=$snapshots?end($snapshots):array();$latest_cert=$certs?end($certs):array();
 if(!$latest_cert)return array('state'=>'none','label'=>'NO INTERNAL ATTESTATION','detail'=>'No producer internal attestation record exists.','certification'=>array(),'snapshot'=>$latest_snapshot);
 $cid=(string)($latest_cert['snapshot_id']??'');$sid=(string)($latest_snapshot['snapshot_id']??'');
 $found=false;$cert_snapshot=array();foreach($snapshots as $s){if((string)($s['snapshot_id']??'')===$cid){$found=true;$cert_snapshot=$s;break;}}
 if(!$found)return array('state'=>'integrity_attention','label'=>'ATTESTATION INTEGRITY ATTENTION','detail'=>'The attestation references a snapshot not present in current append-preserving snapshot history.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
 if(!$sid)return array('state'=>'integrity_attention','label'=>'ATTESTATION INTEGRITY ATTENTION','detail'=>'Attestation exists but no current verification snapshot is available.','certification'=>$latest_cert,'snapshot'=>array());
 $cf=(string)($latest_cert['evidence_fingerprint']??'');$sf=(string)($cert_snapshot['evidence_fingerprint']??'');
 if(!$cf||!$sf||!hash_equals($sf,$cf))return array('state'=>'integrity_attention','label'=>'ATTESTATION FINGERPRINT ATTENTION','detail'=>'This attestation does not contain an evidence fingerprint matching its referenced snapshot. Legacy attestations remain historical but cannot be treated as current.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
 if($cid!==$sid)return array('state'=>'superseded','label'=>'HISTORICAL ATTESTATION','detail'=>'A newer verification snapshot exists. The original attestation remains preserved but no longer represents the current snapshot.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
 if(($latest_snapshot['verdict']??'')!=='ready')return array('state'=>'superseded','label'=>'HISTORICAL ATTESTATION','detail'=>'The attested snapshot is no longer represented as READY by current snapshot data. The attestation remains historical.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
 $gate=function_exists('tuff_beatz_v163_readiness_gate')?tuff_beatz_v163_readiness_gate($id):array('verdict'=>'attention');
 if(($gate['verdict']??'')!=='ready')return array('state'=>'current_attention','label'=>'ATTESTED SNAPSHOT • CURRENT ATTENTION','detail'=>'The attestation references the latest snapshot, but the live readiness gate is no longer READY.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
 if(!function_exists('tuff_beatz_v164_evidence_fingerprint'))return array('state'=>'current_attention','label'=>'ATTESTATION FRESHNESS UNAVAILABLE','detail'=>'Current evidence fingerprint cannot be calculated.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
 $current=(string)tuff_beatz_v164_evidence_fingerprint($id);if(!$current||!hash_equals($cf,$current))return array('state'=>'current_attention','label'=>'ATTESTATION EVIDENCE DRIFT','detail'=>'Current verification evidence no longer matches the evidence fingerprint recorded by this attestation. Capture a fresh snapshot and attestation.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
 return array('state'=>'current','label'=>'CURRENT INTERNAL ATTESTATION','detail'=>'The latest producer attestation references the latest READY snapshot and its evidence fingerprint exactly matches current verification evidence.','certification'=>$latest_cert,'snapshot'=>$latest_snapshot);
}
function tuff_beatz_v167_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request'||!function_exists('tuff_beatz_auth_is_producer')||!tuff_beatz_auth_is_producer($id))return;$state=tuff_beatz_v167_certification_state($id);if($state['state']==='none')return;?><script>document.addEventListener('DOMContentLoaded',function(){var host=document.querySelector('.tb-v166-cert');if(!host)return;var box=document.createElement('div');box.className='tb-v167-integrity is-<?php echo esc_attr($state['state']);?>';box.innerHTML=<?php ob_start();?><small>V16.7.1 • INTERNAL ATTESTATION INTEGRITY</small><strong><?php echo esc_html($state['label']);?></strong><span><?php echo esc_html($state['detail']);?></span><?php if(!empty($state['certification']['certification_id'])):?><em><?php echo esc_html($state['certification']['certification_id']);?> • snapshot <?php echo esc_html($state['certification']['snapshot_id']??'');?></em><?php endif;?><?php $html=ob_get_clean();echo wp_json_encode($html);?>;host.insertAdjacentElement('afterend',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v167_workspace',12);
function tuff_beatz_v167_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v167-integrity{margin-top:7px;padding:9px 12px;border-left:2px solid rgba(216,180,90,.28);background:rgba(255,255,255,.012)}.tb-v167-integrity small,.tb-v167-integrity strong,.tb-v167-integrity span,.tb-v167-integrity em{display:block}.tb-v167-integrity small{color:#756b57;font-size:.45rem;letter-spacing:.12em}.tb-v167-integrity strong{color:#cfc5b2;font-size:.58rem;margin-top:2px}.tb-v167-integrity span{color:#716a60;font-size:.49rem;margin-top:2px}.tb-v167-integrity em{color:#575249;font-style:normal;font-size:.43rem;margin-top:3px;word-break:break-all}.tb-v167-integrity.is-current{border-left-color:#c7a553}.tb-v167-integrity.is-integrity_attention,.tb-v167-integrity.is-current_attention{border-left-width:3px}');}
add_action('wp_enqueue_scripts','tuff_beatz_v167_assets',109);
require_once get_template_directory() . '/inc/production-evidence-ledger.php';
