<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.6.1 — Producer-controlled internal production attestation with exact evidence freshness binding. */
function tuff_beatz_v166_certifications($id){$rows=get_post_meta((int)$id,'_tb_production_certification_v166',false);return is_array($rows)?array_values(array_filter($rows,'is_array')):array();}
function tuff_beatz_v166_latest_snapshot($id){$h=function_exists('tuff_beatz_v164_snapshot_history')?tuff_beatz_v164_snapshot_history($id):array();return $h?end($h):array();}
function tuff_beatz_v166_snapshot_is_current($id,$s){if(empty($s['snapshot_id'])||empty($s['evidence_fingerprint'])||!function_exists('tuff_beatz_v164_evidence_fingerprint'))return false;$current=tuff_beatz_v164_evidence_fingerprint($id);return $current&&hash_equals((string)$s['evidence_fingerprint'],(string)$current);}
function tuff_beatz_v166_capture(){
 $id=(int)($_POST['request_id']??0);if(!$id||get_post_type($id)!=='tb_request')wp_die('Invalid project.');
 if(!is_user_logged_in()||!function_exists('tuff_beatz_auth_is_producer')||!tuff_beatz_auth_is_producer($id))wp_die('Not authorized.');
 if(!isset($_POST['tb_v166_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_v166_nonce'])),'tb_v166_certify_'.$id))wp_die('Invalid request.');
 $s=tuff_beatz_v166_latest_snapshot($id);if(empty($s['snapshot_id']))wp_die('Capture a verification snapshot first.');
 $gate=function_exists('tuff_beatz_v163_readiness_gate')?tuff_beatz_v163_readiness_gate($id):array('verdict'=>'attention');
 if(($s['verdict']??'')!=='ready'||($gate['verdict']??'')!=='ready')wp_die('Only a current READY verification state can be attested.');
 if(!tuff_beatz_v166_snapshot_is_current($id,$s))wp_die('Verification evidence changed after this snapshot. Capture a fresh READY snapshot before attestation.');
 $record=array('certification_id'=>wp_generate_uuid4(),'version'=>'16.6.1','project_id'=>$id,'snapshot_id'=>sanitize_text_field($s['snapshot_id']),'snapshot_verdict'=>'ready','evidence_fingerprint'=>sanitize_text_field($s['evidence_fingerprint']),'project_status'=>sanitize_key($s['project_status']??''),'certified_by'=>get_current_user_id(),'certified_at'=>current_time('mysql'),'statement'=>'Producer attests that the referenced TUFF BEATZ internal verification snapshot exactly matched the current evidence fingerprint and was READY at attestation time. This is an internal production record, not independent, third-party, legal, cryptographic, or regulatory certification.');
 add_post_meta($id,'_tb_production_certification_v166',$record,false);
 wp_safe_redirect(add_query_arg(array('project'=>$id,'production_certification'=>'recorded'),home_url('/project-dashboard/')));exit;
}
add_action('admin_post_tb_certify_production_snapshot','tuff_beatz_v166_capture');
function tuff_beatz_v166_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request'||!function_exists('tuff_beatz_auth_is_producer')||!tuff_beatz_auth_is_producer($id))return;
 $s=tuff_beatz_v166_latest_snapshot($id);$certs=tuff_beatz_v166_certifications($id);$latest=$certs?end($certs):array();$gate=function_exists('tuff_beatz_v163_readiness_gate')?tuff_beatz_v163_readiness_gate($id):array('verdict'=>'attention');$fresh=tuff_beatz_v166_snapshot_is_current($id,$s);$eligible=!empty($s['snapshot_id'])&&($s['verdict']??'')==='ready'&&($gate['verdict']??'')==='ready'&&$fresh;$already=$latest&&!empty($s['snapshot_id'])&&($latest['snapshot_id']??'')===$s['snapshot_id']&&($latest['evidence_fingerprint']??'')===($s['evidence_fingerprint']??'');?><script>document.addEventListener('DOMContentLoaded',function(){var host=document.querySelector('.tb-v165-history')||document.querySelector('.tb-v164-snapshot');if(!host)return;var box=document.createElement('div');box.className='tb-v166-cert';box.innerHTML=<?php ob_start();?><div><small>V16.6.1 • INTERNAL PRODUCTION ATTESTATION</small><strong><?php echo $already?'CURRENT SNAPSHOT ATTESTED':($eligible?'READY FOR PRODUCER ATTESTATION':(!$fresh&&!empty($s['snapshot_id'])?'FRESH SNAPSHOT REQUIRED':'ATTESTATION NOT AVAILABLE'));?></strong><?php if($latest):?><span>Latest attestation <?php echo esc_html($latest['certified_at']??'');?> • <?php echo esc_html($latest['certification_id']??'');?></span><?php else:?><span>Attestation requires a current READY snapshot whose evidence fingerprint exactly matches current verification evidence.</span><?php endif;?></div><?php if($eligible&&!$already):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tb_certify_production_snapshot"><input type="hidden" name="request_id" value="<?php echo esc_attr((string)$id);?>"><?php wp_nonce_field('tb_v166_certify_'.$id,'tb_v166_nonce');?><button type="submit">ATTEST READY SNAPSHOT</button></form><?php endif;?><?php $html=ob_get_clean();echo wp_json_encode($html);?>;host.insertAdjacentElement('afterend',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v166_workspace',11);
function tuff_beatz_v166_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v166-cert{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-top:9px;padding:12px;border:1px solid rgba(216,180,90,.14);border-radius:9px;background:rgba(216,180,90,.025)}.tb-v166-cert small,.tb-v166-cert strong,.tb-v166-cert span{display:block}.tb-v166-cert small{color:#8d7b50;font-size:.47rem;letter-spacing:.13em}.tb-v166-cert strong{color:#d8c99e;font-size:.62rem;margin-top:3px}.tb-v166-cert span{color:#716a60;font-size:.49rem;margin-top:2px}.tb-v166-cert button{border:1px solid rgba(216,180,90,.38);border-radius:7px;background:rgba(216,180,90,.08);color:#d7b95e;padding:8px 10px;font-size:.49rem;letter-spacing:.1em;cursor:pointer}@media(max-width:680px){.tb-v166-cert{align-items:flex-start;flex-direction:column}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v166_assets',108);
require_once get_template_directory() . '/inc/production-certification-integrity.php';
