<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Producer Audio Review Console V12.1 */
function tuff_beatz_producer_audio_console_files($id){$out=array();if(!function_exists('tuff_beatz_vault_files'))return $out;foreach(tuff_beatz_vault_files($id) as $f){$ext=strtolower(pathinfo($f['name']??'',PATHINFO_EXTENSION));if(!in_array($ext,array('wav','aiff','aif','mp3','m4a'),true))continue;$out[]=array('id'=>$f['id']??'','name'=>$f['name']??'Audio File','version'=>$f['version']??'','category'=>$f['category']??'source','size'=>function_exists('tuff_beatz_vault_human_size')?tuff_beatz_vault_human_size($f['size']??0):'','uploaded_at'=>$f['uploaded_at']??'','stream'=>function_exists('tuff_beatz_vault_stream_url')?tuff_beatz_vault_stream_url($id,$f['id']):'','download'=>function_exists('tuff_beatz_vault_download_url')?tuff_beatz_vault_download_url($id,$f['id']):'');}return array_reverse($out);}
function tuff_beatz_producer_audio_console_assets(){if(!is_page('producer-portal'))return;$p=get_template_directory().'/assets/css/producer-audio-console.css';if(file_exists($p))wp_enqueue_style('tuff-beatz-producer-audio-console',get_template_directory_uri().'/assets/css/producer-audio-console.css',array('tuff-beatz-producer-command-v2'),filemtime($p));}
add_action('wp_enqueue_scripts','tuff_beatz_producer_audio_console_assets',95);
function tuff_beatz_render_producer_audio_console(){if(!is_page('producer-portal')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$q=new WP_Query(array('post_type'=>'tb_request','post_status'=>'publish','posts_per_page'=>100,'fields'=>'ids'));$map=array();foreach($q->posts as $id){if(!current_user_can('edit_post',$id))continue;$files=tuff_beatz_producer_audio_console_files($id);$notes=function_exists('tuff_beatz_review_notes')?tuff_beatz_review_notes($id):array();$map[(string)$id]=array('title'=>get_the_title($id),'status'=>get_post_meta($id,'_tb_request_status',true)?:'new','files'=>$files,'notes'=>$notes,'workspace'=>function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id).'#review':'');}wp_reset_postdata();?><script>document.addEventListener('DOMContentLoaded',function(){var map=<?php echo wp_json_encode($map);?>;function esc(s){return String(s||'').replace(/[&<>'"]/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c];});}function label(f){return esc(f.version||f.name);}function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');}
document.querySelectorAll('.tb-producer-row').forEach(function(row){var link=row.querySelector('a[href*="project-dashboard"][href*="project="]');if(!link)return;var m=link.href.match(/[?&]project=(\d+)/);if(!m||!map[m[1]])return;var d=map[m[1]],actions=row.querySelector('.tb-producer-actions');if(!actions)return;var btn=document.createElement('button');btn.type='button';btn.className='tb-audio-console-open';btn.innerHTML='<span>♫</span> Audio Console <b>'+d.files.length+'</b>';actions.appendChild(btn);var panel=document.createElement('section');panel.className='tb-producer-audio-console';panel.hidden=true;var html='<div class="tb-pac-head"><div><small>PRODUCER AUDIO REVIEW</small><h3>'+esc(d.title)+'</h3></div><div><span>'+esc(d.status.replace(/-/g,' '))+'</span><button type="button" class="tb-pac-close" aria-label="Close">×</button></div></div>';
if(d.files.length){html+='<div class="tb-pac-compare"><div class="tb-pac-compare-top"><div><small>A/B MIX COMPARISON</small><strong>Compare two versions instantly</strong></div><button type="button" class="tb-pac-swap">⇄ Swap A / B</button></div><div class="tb-pac-compare-grid"><label>A<select class="tb-pac-select-a">';d.files.forEach(function(f,i){html+='<option value="'+i+'"'+(i===0?' selected':'')+'>'+label(f)+'</option>';});html+='</select></label><label>B<select class="tb-pac-select-b">';d.files.forEach(function(f,i){html+='<option value="'+i+'"'+(i===Math.min(1,d.files.length-1)?' selected':'')+'>'+label(f)+'</option>';});html+='</select></label></div><div class="tb-pac-ab-decks"><article><span>A</span><strong class="tb-pac-a-name"></strong><audio class="tb-pac-audio-a" controls preload="metadata"></audio></article><article><span>B</span><strong class="tb-pac-b-name"></strong><audio class="tb-pac-audio-b" controls preload="metadata"></audio></article></div><div class="tb-pac-syncbar"><button type="button" class="tb-pac-sync">Sync B to A Position</button><button type="button" class="tb-pac-toggle">A/B Toggle</button><small class="tb-pac-sync-state">Ready</small></div><div class="tb-pac-note-panel"><small>CLIENT REVISION NOTES</small><div class="tb-pac-notes"></div></div></div>';
html+='<div class="tb-pac-list">';d.files.forEach(function(f){html+='<article class="tb-pac-track"><div class="tb-pac-track-head"><div><span>'+(f.category==='delivery'?'REVIEW / DELIVERY':'SOURCE AUDIO')+'</span><strong>'+label(f)+'</strong><small>'+esc(f.name)+' • '+esc(f.size)+'</small></div><a href="'+f.download+'">Download ↓</a></div><audio controls preload="metadata" src="'+f.stream+'"></audio></article>';});html+='</div>';}else{html+='<div class="tb-pac-empty"><strong>No audio in the Private Vault yet.</strong><p>Upload source audio, mixes or masters and they will appear here automatically.</p></div>';}if(d.workspace)html+='<div class="tb-pac-footer"><a href="'+d.workspace+'">Open Full Mix Review Workspace →</a></div>';panel.innerHTML=html;row.insertAdjacentElement('afterend',panel);
function pauseOthers(active){document.querySelectorAll('.tb-producer-audio-console audio').forEach(function(other){if(other!==active)other.pause();});}
panel.querySelectorAll('audio').forEach(function(a){a.addEventListener('play',function(){pauseOthers(a);});});
if(d.files.length){var sa=panel.querySelector('.tb-pac-select-a'),sb=panel.querySelector('.tb-pac-select-b'),aa=panel.querySelector('.tb-pac-audio-a'),ab=panel.querySelector('.tb-pac-audio-b'),an=panel.querySelector('.tb-pac-a-name'),bn=panel.querySelector('.tb-pac-b-name'),notes=panel.querySelector('.tb-pac-notes'),state=panel.querySelector('.tb-pac-sync-state');function renderNotes(f){var list=(d.notes||[]).filter(function(n){return String(n.file_id||'')===String(f.id||'');});if(!list.length){notes.innerHTML='<p>No client notes on selected A version.</p>';return;}notes.innerHTML=list.map(function(n){return '<button type="button" data-sec="'+Number(n.seconds||0)+'"><b>'+fmt(n.seconds||0)+'</b><span>'+esc(n.name||'Client')+': '+esc(n.body||'')+'</span></button>';}).join('');notes.querySelectorAll('button').forEach(function(x){x.addEventListener('click',function(){aa.currentTime=Number(x.dataset.sec||0);aa.play();});});}
function load(){var fa=d.files[Number(sa.value)]||d.files[0],fb=d.files[Number(sb.value)]||d.files[0];aa.src=fa.stream;ab.src=fb.stream;aa.load();ab.load();an.textContent=fa.version||fa.name;bn.textContent=fb.version||fb.name;renderNotes(fa);state.textContent='A: '+(fa.version||fa.name)+' • B: '+(fb.version||fb.name);}sa.addEventListener('change',load);sb.addEventListener('change',load);panel.querySelector('.tb-pac-swap').addEventListener('click',function(){var x=sa.value;sa.value=sb.value;sb.value=x;load();});panel.querySelector('.tb-pac-sync').addEventListener('click',function(){if(isFinite(aa.currentTime)){ab.currentTime=aa.currentTime;state.textContent='Synced at '+fmt(aa.currentTime);}});panel.querySelector('.tb-pac-toggle').addEventListener('click',function(){if(!aa.paused){var t=aa.currentTime;aa.pause();ab.currentTime=t;ab.play();state.textContent='Listening to B at '+fmt(t);}else{var t=ab.currentTime;ab.pause();aa.currentTime=t;aa.play();state.textContent='Listening to A at '+fmt(t);}});load();}
btn.addEventListener('click',function(){document.querySelectorAll('.tb-producer-audio-console').forEach(function(x){if(x!==panel){x.hidden=true;x.querySelectorAll('audio').forEach(function(a){a.pause();});}});panel.hidden=!panel.hidden;if(panel.hidden)panel.querySelectorAll('audio').forEach(function(a){a.pause();});});panel.querySelector('.tb-pac-close').addEventListener('click',function(){panel.hidden=true;panel.querySelectorAll('audio').forEach(function(a){a.pause();});});});});</script><?php }
add_action('wp_footer','tuff_beatz_render_producer_audio_console',18);
