<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Notifications & Client Communication V9 */
function tuff_beatz_notifications($id){$v=get_post_meta((int)$id,'_tb_notifications_v9',true);return is_array($v)?array_values($v):array();}
function tuff_beatz_notification_recipients($id){$out=array();$p=get_post($id);if($p&&$p->post_author){$u=get_userdata($p->post_author);if($u&&is_email($u->user_email))$out[$u->ID]=$u->user_email;}if(function_exists('tuff_beatz_project_collaborators'))foreach(tuff_beatz_project_collaborators($id) as $c){$uid=(int)($c['user_id']??0);$email=sanitize_email($c['email']??'');if($uid&&$email)$out[$uid]=$email;}return $out;}
function tuff_beatz_add_notification($id,$type,$title,$message,$email=true){$id=(int)$id;if(!$id||get_post_type($id)!=='tb_request')return false;$n=tuff_beatz_notifications($id);$item=array('id'=>wp_generate_uuid4(),'type'=>sanitize_key($type),'title'=>sanitize_text_field($title),'message'=>sanitize_text_field($message),'time'=>current_time('mysql'),'read_by'=>array());$n[]=$item;if(count($n)>150)$n=array_slice($n,-150);update_post_meta($id,'_tb_notifications_v9',$n);if(function_exists('tuff_beatz_add_activity'))tuff_beatz_add_activity($id,'notification',$title);if($email){$subject='TUFF BEATZ — '.$title;$body=$message."\n\nProject: ".get_the_title($id)."\nOpen your project: ".(function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id):home_url('/client-portal/'))."\n\nTUFF BEATZ — SOUND. PURPOSE. LEGACY.";foreach(array_unique(tuff_beatz_notification_recipients($id)) as $to)wp_mail($to,$subject,$body);}return $item;}
function tuff_beatz_notify_status_change($meta_id,$object_id,$meta_key,$meta_value){if(get_post_type($object_id)!=='tb_request')return;if($meta_key==='_tb_request_status'){static $busy=false;if($busy)return;$busy=true;$labels=function_exists('tuff_beatz_request_status_label')?tuff_beatz_request_status_label($meta_value):ucwords(str_replace('-',' ',$meta_value));$map=array('reviewing'=>'Project Review Started','approved'=>'Project Approved','in-progress'=>'Production Started','revision'=>'Revision Stage','mastering'=>'Mastering Started','delivery'=>'Final Delivery Ready','completed'=>'Project Completed','declined'=>'Project Status Updated');if(isset($map[$meta_value]))tuff_beatz_add_notification($object_id,'status',$map[$meta_value],'Your project status is now '.$labels.'.');$busy=false;}
if($meta_key==='_tb_request_payment_status'){static $paybusy=false;if($paybusy)return;$paybusy=true;$s=(string)$meta_value;$map=array('Deposit due'=>'Deposit Is Due','Balance due'=>'Balance Payment Is Due','Paid in full'=>'Payment Complete');if(isset($map[$s]))tuff_beatz_add_notification($object_id,'payment',$map[$s],$s==='Paid in full'?'Your project is paid in full. Thank you.':'A payment action is ready in your project workspace.');$paybusy=false;}}
add_action('added_post_meta','tuff_beatz_notify_status_change',20,4);add_action('updated_post_meta','tuff_beatz_notify_status_change',20,4);
function tuff_beatz_notification_mix_meta($meta_id,$object_id,$meta_key,$meta_value){if(get_post_type($object_id)!=='tb_request')return;if($meta_key==='_tb_approved_mix_file')tuff_beatz_add_notification($object_id,'approval','Mix Approved','The approved mix has moved forward to mastering.');}
add_action('added_post_meta','tuff_beatz_notification_mix_meta',25,4);add_action('updated_post_meta','tuff_beatz_notification_mix_meta',25,4);
function tuff_beatz_mark_notifications_read(){ $id=(int)($_POST['request_id']??0);$r=function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id):home_url('/client-portal/');if(!is_user_logged_in()||!function_exists('tuff_beatz_user_project_permission')||!tuff_beatz_user_project_permission($id,'view')){wp_safe_redirect($r);exit;}if(!isset($_POST['tb_notify_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_notify_nonce'])),'tb_notify_'.$id)){wp_safe_redirect($r);exit;}$uid=get_current_user_id();$n=tuff_beatz_notifications($id);foreach($n as &$x){$read=array_map('intval',(array)($x['read_by']??array()));if(!in_array($uid,$read,true))$read[]=$uid;$x['read_by']=$read;}unset($x);update_post_meta($id,'_tb_notifications_v9',$n);wp_safe_redirect($r.'#notifications');exit;}
add_action('admin_post_tb_mark_notifications_read','tuff_beatz_mark_notifications_read');
function tuff_beatz_render_notifications_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||!function_exists('tuff_beatz_user_project_permission')||!tuff_beatz_user_project_permission($id,'view'))return;$all=array_reverse(tuff_beatz_notifications($id));$uid=get_current_user_id();$unread=0;foreach($all as $x)if(!in_array($uid,array_map('intval',(array)($x['read_by']??array())),true))$unread++;echo '<template id="tb-notifications-template"><section id="notifications" class="tb-portal-card tb-workspace-section tb-notifications"><div class="tb-notify-head"><div><p class="tb-card-kicker">COMMUNICATION CENTER V9</p><h2>Notifications</h2></div><span>'.esc_html($unread).' unread</span></div>';if($all){echo '<div class="tb-notify-list">';foreach(array_slice($all,0,40) as $x){$isread=in_array($uid,array_map('intval',(array)($x['read_by']??array())),true);echo '<article class="tb-notify-item'.($isread?' is-read':' is-unread').'"><i></i><div><small>'.esc_html(strtoupper(str_replace('-',' ',$x['type']??'update'))).'</small><h3>'.esc_html($x['title']??'Project Update').'</h3><p>'.esc_html($x['message']??'').'</p><span>'.esc_html(mysql2date('M j, Y g:i a',$x['time']??'')).'</span></div></article>';}echo '</div><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" class="tb-notify-read"><input type="hidden" name="action" value="tb_mark_notifications_read"><input type="hidden" name="request_id" value="'.esc_attr($id).'">';wp_nonce_field('tb_notify_'.$id,'tb_notify_nonce');echo '<button class="btn btn-outline" type="submit">Mark All Read</button></form>';}else echo '<p class="tb-empty-state">No notifications yet. Important project updates will appear here.</p>';echo '</section></template><script>document.addEventListener("DOMContentLoaded",function(){var t=document.getElementById("tb-notifications-template"),m=document.getElementById("messages"),nav=document.querySelector(".tb-dashboard-nav");if(t&&m)m.parentNode.insertBefore(t.content.cloneNode(true),m);if(nav){var a=document.createElement("a");a.href="#notifications";a.textContent="Notifications'.($unread?' ('.(int)$unread.')':'').'";var x=nav.querySelector("a[href=\"#messages\"]");if(x)nav.insertBefore(a,x);else nav.appendChild(a);}});</script>';}
add_action('wp_footer','tuff_beatz_render_notifications_workspace',6);
function tuff_beatz_notifications_assets(){if(is_page(array('project-dashboard','client-portal','producer-portal'))){$p=get_template_directory().'/assets/css/notifications.css';if(file_exists($p))wp_enqueue_style('tuff-beatz-notifications',get_template_directory_uri().'/assets/css/notifications.css',array('tuff-beatz-project-portal'),filemtime($p));}}
add_action('wp_enqueue_scripts','tuff_beatz_notifications_assets',48);
