<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Invoices, Receipts & Payment Reconciliation V7 */
function tuff_beatz_invoice_data($id){$v=get_post_meta((int)$id,'_tb_invoices_v7',true);return is_array($v)?array_values($v):array();}
function tuff_beatz_invoice_settings($id){$v=get_post_meta((int)$id,'_tb_invoice_settings_v7',true);return is_array($v)?$v:array('due_days'=>7);}
function tuff_beatz_invoice_number($id,$type){return 'TBI-'.gmdate('Y').'-'.str_pad((int)$id,5,'0',STR_PAD_LEFT).'-'.strtoupper(substr($type,0,3));}
function tuff_beatz_receipt_number($id,$index){return 'TBR-'.gmdate('Y').'-'.str_pad((int)$id,5,'0',STR_PAD_LEFT).'-'.str_pad((int)$index+1,3,'0',STR_PAD_LEFT);}
function tuff_beatz_invoice_status($invoice,$paid_total=0){$amount=(float)($invoice['amount']??0);$applied=min($amount,max(0,(float)$paid_total-(float)($invoice['offset']??0)));if($amount>0&&$applied>=$amount)return 'paid';$due=$invoice['due_date']??'';if($due&&strtotime($due.' 23:59:59')<current_time('timestamp'))return $applied>0?'partially-paid-overdue':'overdue';return $applied>0?'partially-paid':'due';}
function tuff_beatz_ensure_invoices($id){$q=tuff_beatz_quote_data($id);if(!$q||($q['status']??'')!=='accepted')return tuff_beatz_invoice_data($id);$t=tuff_beatz_quote_totals($q);$settings=tuff_beatz_invoice_settings($id);$days=max(1,(int)($settings['due_days']??7));$existing=tuff_beatz_invoice_data($id);$map=array();foreach($existing as $i=>$inv)$map[$inv['type']??'']=$i;$today=current_time('Y-m-d');$deposit=min($t['total'],$t['deposit']);$balance=max(0,$t['total']-$deposit);
 if($deposit>0&&!isset($map['deposit']))$existing[]=array('type'=>'deposit','number'=>tuff_beatz_invoice_number($id,'deposit'),'amount'=>$deposit,'offset'=>0,'issued_at'=>current_time('mysql'),'due_date'=>date('Y-m-d',strtotime($today.' +'.$days.' days')),'quote_version'=>$q['version']??'');
 $paid=tuff_beatz_payment_totals($id)['paid'];if($balance>0&&$paid>=$deposit&&!isset($map['balance']))$existing[]=array('type'=>'balance','number'=>tuff_beatz_invoice_number($id,'balance'),'amount'=>$balance,'offset'=>$deposit,'issued_at'=>current_time('mysql'),'due_date'=>date('Y-m-d',strtotime($today.' +'.$days.' days')),'quote_version'=>$q['version']??'');
 update_post_meta($id,'_tb_invoices_v7',$existing);return $existing;}
function tuff_beatz_v7_payment_records($id){$p=tuff_beatz_payment_data($id);$changed=false;foreach($p as $i=>&$row){if(empty($row['payment_id'])){$row['payment_id']='pay_'.substr(hash('sha256',$id.'|'.$i.'|'.($row['date']??'').'|'.($row['amount']??0)),0,16);$changed=true;}if(empty($row['receipt_number'])){$row['receipt_number']=tuff_beatz_receipt_number($id,$i);$changed=true;}}unset($row);if($changed)update_post_meta($id,'_tb_payments_v6',$p);return $p;}
function tuff_beatz_v7_add_payment($id,$amount,$method,$reference,$provider='manual',$transaction_id=''){$amount=max(0,(float)$amount);if($amount<=0)return false;$p=tuff_beatz_v7_payment_records($id);if($transaction_id){foreach($p as $r)if(($r['transaction_id']??'')===$transaction_id&&($r['provider']??'')===$provider)return false;}$i=count($p);$p[]=array('payment_id'=>'pay_'.wp_generate_password(16,false,false),'receipt_number'=>tuff_beatz_receipt_number($id,$i),'amount'=>$amount,'method'=>sanitize_text_field($method),'reference'=>sanitize_text_field($reference),'provider'=>sanitize_key($provider),'transaction_id'=>sanitize_text_field($transaction_id),'status'=>'paid','date'=>current_time('mysql'),'recorded_by'=>get_current_user_id());update_post_meta($id,'_tb_payments_v6',$p);tuff_beatz_sync_payment_status($id);tuff_beatz_ensure_invoices($id);return true;}
function tuff_beatz_v7_assets(){if(is_page('project-dashboard')){$p=get_template_directory().'/assets/css/invoicing.css';if(file_exists($p))wp_enqueue_style('tuff-beatz-invoicing',get_template_directory_uri().'/assets/css/invoicing.css',array('tuff-beatz-commerce'),filemtime($p));}}
add_action('wp_enqueue_scripts','tuff_beatz_v7_assets',45);
function tuff_beatz_invoice_admin_box($post){$s=tuff_beatz_invoice_settings($post->ID);$invoices=tuff_beatz_ensure_invoices($post->ID);$payments=tuff_beatz_v7_payment_records($post->ID);wp_nonce_field('tb_invoice_settings_'.$post->ID,'tb_invoice_settings_nonce');echo '<p><label><strong>Invoice due in days</strong></label><br><input type="number" min="1" max="120" name="tb_invoice_due_days" value="'.esc_attr($s['due_days']??7).'" style="width:100%"></p><p><strong>Invoices</strong></p>';if($invoices){$paid=tuff_beatz_payment_totals($post->ID)['paid'];foreach($invoices as $inv)echo '<p><code>'.esc_html($inv['number']).'</code><br>'.esc_html(ucfirst($inv['type']).' • '.tuff_beatz_money($inv['amount']).' • '.tuff_beatz_invoice_status($inv,$paid)).'</p>';}else echo '<p>No invoices yet. Deposit invoice is created after quote/contract acceptance.</p>';if($payments){echo '<hr><p><strong>Receipts</strong></p>';foreach(array_reverse($payments) as $p)echo '<p><code>'.esc_html($p['receipt_number']??'').'</code> '.esc_html(tuff_beatz_money($p['amount']??0)).'</p>';}}
function tuff_beatz_invoice_admin_metabox(){add_meta_box('tb_invoicing_v7',__('Invoices & Receipts V7','tuff-beatz'),'tuff_beatz_invoice_admin_box','tb_request','side','default');}add_action('add_meta_boxes_tb_request','tuff_beatz_invoice_admin_metabox');
function tuff_beatz_save_invoice_settings($id){if(!isset($_POST['tb_invoice_settings_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_invoice_settings_nonce'])),'tb_invoice_settings_'.$id)||!current_user_can('edit_post',$id))return;$days=max(1,min(120,(int)($_POST['tb_invoice_due_days']??7)));update_post_meta($id,'_tb_invoice_settings_v7',array('due_days'=>$days));}
add_action('save_post_tb_request','tuff_beatz_save_invoice_settings',40);
function tuff_beatz_document_url($id,$kind,$token){return wp_nonce_url(add_query_arg(array('action'=>'tb_business_document','request_id'=>(int)$id,'kind'=>$kind,'token'=>$token),admin_url('admin-post.php')),'tb_business_document_'.$id.'_'.$kind.'_'.$token);}
function tuff_beatz_business_document(){if(!is_user_logged_in())wp_die('Login required.',403);$id=(int)($_GET['request_id']??0);$kind=sanitize_key($_GET['kind']??'');$token=sanitize_text_field(wp_unslash($_GET['token']??''));if(!tuff_beatz_commerce_permission($id)||!wp_verify_nonce(sanitize_text_field(wp_unslash($_GET['_wpnonce']??'')),'tb_business_document_'.$id.'_'.$kind.'_'.$token))wp_die('Not authorized.',403);$title='TUFF BEATZ Document';$body='';if($kind==='invoice'){foreach(tuff_beatz_ensure_invoices($id) as $inv)if(($inv['number']??'')===$token){$q=tuff_beatz_quote_data($id);$title='Invoice '.$inv['number'];$body='<h2>'.esc_html(ucfirst($inv['type'])).' Invoice</h2><p><strong>Invoice:</strong> '.esc_html($inv['number']).'</p><p><strong>Project:</strong> '.esc_html(get_the_title($id)).'</p><p><strong>Issued:</strong> '.esc_html($inv['issued_at']).'</p><p><strong>Due:</strong> '.esc_html($inv['due_date']).'</p><div class="amount">'.esc_html(tuff_beatz_money($inv['amount'])).'</div><h3>Scope of Work</h3><p>'.nl2br(esc_html($q['scope']??'')).'</p>';break;}}elseif($kind==='receipt'){foreach(tuff_beatz_v7_payment_records($id) as $p)if(($p['receipt_number']??'')===$token){$title='Receipt '.$p['receipt_number'];$body='<h2>Payment Receipt</h2><p><strong>Receipt:</strong> '.esc_html($p['receipt_number']).'</p><p><strong>Project:</strong> '.esc_html(get_the_title($id)).'</p><p><strong>Date:</strong> '.esc_html($p['date']??'').'</p><p><strong>Method:</strong> '.esc_html($p['method']??'').'</p><p><strong>Reference:</strong> '.esc_html($p['reference']??'').'</p><div class="amount">'.esc_html(tuff_beatz_money($p['amount']??0)).'</div>';break;}}if(!$body)wp_die('Document not found.',404);nocache_headers();header('Content-Type: text/html; charset='.get_bloginfo('charset'));echo '<!doctype html><html><head><meta charset="'.esc_attr(get_bloginfo('charset')).'"><meta name="viewport" content="width=device-width"><title>'.esc_html($title).'</title><style>body{font-family:Arial,sans-serif;background:#eee;margin:0;padding:30px;color:#111}.doc{max-width:760px;margin:auto;background:#fff;padding:54px;box-shadow:0 10px 40px #0002}.brand{font-weight:900;letter-spacing:.12em}.brand span{color:#a77b1f}.amount{font-size:38px;font-weight:900;margin:28px 0;padding:20px 0;border-top:2px solid #111;border-bottom:2px solid #111}p{line-height:1.65}.actions{max-width:760px;margin:15px auto;text-align:right}button{padding:12px 18px;background:#111;color:#fff;border:0;cursor:pointer}@media print{body{background:#fff;padding:0}.doc{box-shadow:none;max-width:none}.actions{display:none}}</style></head><body><div class="actions"><button onclick="window.print()">Print / Save PDF</button></div><main class="doc"><div class="brand">TUFF <span>BEATZ</span></div><p>SOUND. PURPOSE. LEGACY.</p>'.$body.'<hr><p><small>This document is generated from the TUFF BEATZ project workspace.</small></p></main></body></html>';exit;}
add_action('admin_post_tb_business_document','tuff_beatz_business_document');
function tuff_beatz_render_invoicing_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||!tuff_beatz_commerce_permission($id))return;$invoices=tuff_beatz_ensure_invoices($id);$payments=tuff_beatz_v7_payment_records($id);if(!$invoices&&!$payments)return;$paid=tuff_beatz_payment_totals($id)['paid'];echo '<template id="tb-invoicing-template"><section id="invoices" class="tb-portal-card tb-workspace-section tb-invoicing"><p class="tb-card-kicker">BILLING V7</p><h2>Invoices & Receipts</h2>';if($invoices){echo '<div class="tb-invoice-list">';foreach($invoices as $inv){$st=tuff_beatz_invoice_status($inv,$paid);echo '<article><div><span>'.esc_html(strtoupper($inv['type'])).' INVOICE</span><strong>'.esc_html($inv['number']).'</strong><small>Due '.esc_html($inv['due_date']).'</small></div><div><b>'.esc_html(tuff_beatz_money($inv['amount'])).'</b><em class="tb-invoice-status tb-invoice-status--'.esc_attr($st).'">'.esc_html(str_replace('-',' ',$st)).'</em><a href="'.esc_url(tuff_beatz_document_url($id,'invoice',$inv['number'])).'" target="_blank">View / Save PDF ↗</a></div></article>';}echo '</div>';}if($payments){echo '<h3 class="tb-receipt-title">Receipts</h3><div class="tb-receipt-list">';foreach(array_reverse($payments) as $p)echo '<a href="'.esc_url(tuff_beatz_document_url($id,'receipt',$p['receipt_number'])).'" target="_blank"><span>'.esc_html($p['receipt_number']).'</span><strong>'.esc_html(tuff_beatz_money($p['amount']??0)).'</strong><small>'.esc_html($p['date']??'').'</small><b>Receipt ↗</b></a>';echo '</div>';}echo '</section></template><script>document.addEventListener("DOMContentLoaded",function(){var t=document.getElementById("tb-invoicing-template"),commerce=document.getElementById("commerce"),nav=document.querySelector(".tb-dashboard-nav");if(t&&commerce)commerce.parentNode.insertBefore(t.content.cloneNode(true),commerce.nextSibling);if(nav){var a=document.createElement("a");a.href="#invoices";a.textContent="Invoices";var c=nav.querySelector("a[href=\"#commerce\"]");if(c)c.insertAdjacentElement("afterend",a);}});</script>';}
add_action('wp_footer','tuff_beatz_render_invoicing_workspace',10);
/** Provider-neutral signed webhook. Configure TUFF_BEATZ_PAYMENT_WEBHOOK_SECRET in wp-config.php/server environment before use. */
function tuff_beatz_register_reconciliation_route(){register_rest_route('tuff-beatz/v1','/payment-webhook',array('methods'=>'POST','callback'=>'tuff_beatz_payment_webhook','permission_callback'=>'__return_true'));}
add_action('rest_api_init','tuff_beatz_register_reconciliation_route');
function tuff_beatz_payment_webhook(WP_REST_Request $req){if(!defined('TUFF_BEATZ_PAYMENT_WEBHOOK_SECRET')||!TUFF_BEATZ_PAYMENT_WEBHOOK_SECRET)return new WP_REST_Response(array('ok'=>false,'error'=>'webhook_not_configured'),503);$raw=$req->get_body();$sig=(string)$req->get_header('x-tuff-signature');$expected=hash_hmac('sha256',$raw,TUFF_BEATZ_PAYMENT_WEBHOOK_SECRET);if(!$sig||!hash_equals($expected,$sig))return new WP_REST_Response(array('ok'=>false,'error'=>'invalid_signature'),401);$d=json_decode($raw,true);$id=(int)($d['project_id']??0);$amount=(float)($d['amount']??0);$tx=sanitize_text_field($d['transaction_id']??'');$provider=sanitize_key($d['provider']??'gateway');$status=sanitize_key($d['status']??'');if(!$id||get_post_type($id)!=='tb_request'||$amount<=0||!$tx||$status!=='paid')return new WP_REST_Response(array('ok'=>false,'error'=>'invalid_payload'),400);$added=tuff_beatz_v7_add_payment($id,$amount,ucfirst($provider),$tx,$provider,$tx);return new WP_REST_Response(array('ok'=>true,'reconciled'=>$added,'payment_status'=>tuff_beatz_sync_payment_status($id)),200);}
