<?php
if (!defined('ABSPATH')) exit;
/** TUFF BEATZ Production Dashboard V4 — Private Vault + Mix Review */
function tuff_beatz_dashboard_page_setup(){ $page=get_page_by_path('project-dashboard'); if(!$page){$id=wp_insert_post(array('post_title'=>'Project Dashboard','post_name'=>'project-dashboard','post_status'=>'publish','post_type'=>'page','post_content'=>''));if(!is_wp_error($id)&&$id)update_post_meta($id,'_wp_page_template','page-project-dashboard.php');}else update_post_meta($page->ID,'_wp_page_template','page-project-dashboard.php'); }
add_action('init','tuff_beatz_dashboard_page_setup',31);
function tuff_beatz_dashboard_assets(){if(is_page('project-dashboard')){$p=get_template_directory().'/assets/css/project-portal.css';$r=get_template_directory().'/assets/css/mix-review.css';$j=get_template_directory().'/assets/js/mix-review.js';wp_enqueue_style('tuff-beatz-project-portal',get_template_directory_uri().'/assets/css/project-portal.css',array('tuff-beatz-main'),file_exists($p)?filemtime($p):wp_get_theme()->get('Version'));wp_enqueue_style('tuff-beatz-mix-review',get_template_directory_uri().'/assets/css/mix-review.css',array('tuff-beatz-project-portal'),file_exists($r)?filemtime($r):wp_get_theme()->get('Version'));wp_enqueue_script('tuff-beatz-mix-review',get_template_directory_uri().'/assets/js/mix-review.js',array(),file_exists($j)?filemtime($j):wp_get_theme()->get('Version'),true);}}
add_action('wp_enqueue_scripts','tuff_beatz_dashboard_assets',41);
function tuff_beatz_user_can_view_request($id,$uid=0){$id=(int)$id;$uid=$uid?:get_current_user_id();if(!$id||!$uid)return false;if(current_user_can('edit_post',$id))return true;$p=get_post($id);return $p&&$p->post_type==='tb_request'&&(int)$p->post_author===(int)$uid;}
function tuff_beatz_project_dashboard_url($id){return add_query_arg('project',(int)$id,home_url('/project-dashboard/'));}
function tuff_beatz_dashboard_messages($id){$m=get_post_meta((int)$id,'_tb_project_messages',true);return is_array($m)?$m:array();}
function tuff_beatz_review_notes($id){$m=get_post_meta((int)$id,'_tb_mix_review_notes',true);return is_array($m)?$m:array();}
function tuff_beatz_review_status($id,$file_id){$s=get_post_meta((int)$id,'_tb_mix_review_status',true);return is_array($s)&&isset($s[$file_id])?$s[$file_id]:'awaiting-review';}
function tuff_beatz_reviewable_file($f){$ext=strtolower(pathinfo($f['name']??'',PATHINFO_EXTENSION));return ($f['category']??'')==='delivery'&&in_array($ext,array('mp3','wav','m4a','aiff','aif'),true);}
function tuff_beatz_submit_project_message(){$id=(int)($_POST['request_id']??0);$r=tuff_beatz_project_dashboard_url($id);if(!is_user_logged_in()||!tuff_beatz_user_can_view_request($id)){wp_safe_redirect(home_url('/start-a-project/'));exit;}if(!isset($_POST['tb_message_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_message_nonce'])),'tb_project_message_'.$id)){wp_safe_redirect($r);exit;}$body=sanitize_textarea_field(wp_unslash($_POST['message']??''));if(!$body){wp_safe_redirect($r);exit;}$u=wp_get_current_user();$m=tuff_beatz_dashboard_messages($id);$m[]=array('user_id'=>$u->ID,'name'=>$u->display_name,'role'=>current_user_can('edit_post',$id)?'TUFF BEATZ':'Client','body'=>$body,'time'=>current_time('mysql'));update_post_meta($id,'_tb_project_messages',$m);wp_safe_redirect(add_query_arg('message_sent','1',$r).'#messages');exit;}
add_action('admin_post_tb_submit_project_message','tuff_beatz_submit_project_message');
function tuff_beatz_upload_project_dashboard_files(){$id=(int)($_POST['request_id']??0);$r=tuff_beatz_project_dashboard_url($id);if(!is_user_logged_in()||!tuff_beatz_user_can_view_request($id)){wp_safe_redirect(home_url('/start-a-project/'));exit;}if(!isset($_POST['tb_files_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_files_nonce'])),'tb_project_files_'.$id)){wp_safe_redirect($r);exit;}$v=sanitize_text_field(wp_unslash($_POST['upload_version']??'Client Upload'));$new=tuff_beatz_vault_save_files($id,'project_files','source',$v?:'Client Upload');wp_safe_redirect(add_query_arg('files_added',(string)count($new),$r).'#files');exit;}
add_action('admin_post_tb_upload_project_dashboard_files','tuff_beatz_upload_project_dashboard_files');
function tuff_beatz_admin_upload_delivery_files(){$id=(int)($_POST['request_id']??0);$r=admin_url('post.php?post='.$id.'&action=edit');if(!$id||!current_user_can('edit_post',$id)){wp_safe_redirect(admin_url());exit;}if(!isset($_POST['tb_delivery_upload_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_delivery_upload_nonce'])),'tb_delivery_upload_'.$id)){wp_safe_redirect($r);exit;}$v=sanitize_text_field(wp_unslash($_POST['delivery_version']??'Mix V1'));$new=tuff_beatz_vault_save_files($id,'delivery_files','delivery',$v?:'Mix V1');if($new){$s=get_post_meta($id,'_tb_mix_review_status',true);if(!is_array($s))$s=array();foreach($new as $fid)$s[$fid]='awaiting-review';update_post_meta($id,'_tb_mix_review_status',$s);update_post_meta($id,'_tb_request_status','revision');}wp_safe_redirect(add_query_arg('vault_delivery_added',(string)count($new),$r));exit;}
add_action('admin_post_tb_admin_upload_delivery_files','tuff_beatz_admin_upload_delivery_files');
function tuff_beatz_submit_mix_review(){ $id=(int)($_POST['request_id']??0);$fid=sanitize_text_field(wp_unslash($_POST['file_id']??''));$r=tuff_beatz_project_dashboard_url($id).'#review';if(!is_user_logged_in()||!tuff_beatz_user_can_view_request($id)){wp_safe_redirect(home_url('/start-a-project/'));exit;}if(!isset($_POST['tb_review_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_review_nonce'])),'tb_mix_review_'.$id.'_'.$fid)){wp_safe_redirect($r);exit;}$body=sanitize_textarea_field(wp_unslash($_POST['review_note']??''));$sec=max(0,(int)($_POST['timestamp']??0));if($body){$u=wp_get_current_user();$n=tuff_beatz_review_notes($id);$n[]=array('file_id'=>$fid,'seconds'=>$sec,'body'=>$body,'user_id'=>$u->ID,'name'=>$u->display_name,'time'=>current_time('mysql'));update_post_meta($id,'_tb_mix_review_notes',$n);$s=get_post_meta($id,'_tb_mix_review_status',true);if(!is_array($s))$s=array();$s[$fid]='revision-requested';update_post_meta($id,'_tb_mix_review_status',$s);update_post_meta($id,'_tb_request_status','revision');}wp_safe_redirect(add_query_arg('review_saved','1',$r));exit; }
add_action('admin_post_tb_submit_mix_review','tuff_beatz_submit_mix_review');
function tuff_beatz_approve_mix(){ $id=(int)($_POST['request_id']??0);$fid=sanitize_text_field(wp_unslash($_POST['file_id']??''));$r=tuff_beatz_project_dashboard_url($id).'#review';if(!is_user_logged_in()||!tuff_beatz_user_can_view_request($id)){wp_safe_redirect(home_url('/start-a-project/'));exit;}if(!isset($_POST['tb_approve_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_approve_nonce'])),'tb_approve_mix_'.$id.'_'.$fid)){wp_safe_redirect($r);exit;}$s=get_post_meta($id,'_tb_mix_review_status',true);if(!is_array($s))$s=array();$s[$fid]='approved';update_post_meta($id,'_tb_mix_review_status',$s);update_post_meta($id,'_tb_approved_mix_file',$fid);update_post_meta($id,'_tb_request_status','mastering');wp_safe_redirect(add_query_arg('mix_approved','1',$r));exit; }
add_action('admin_post_tb_approve_mix','tuff_beatz_approve_mix');
function tuff_beatz_dashboard_admin_box($post){wp_nonce_field('tb_dashboard_admin_save','tb_dashboard_admin_nonce');$credits=get_post_meta($post->ID,'_tb_request_credits',true);$payment=get_post_meta($post->ID,'_tb_request_payment_status',true)?:'Not invoiced';$delivery=get_post_meta($post->ID,'_tb_request_delivery_notes',true);$final=get_post_meta($post->ID,'_tb_request_final_links',true);echo '<p><strong>Client dashboard:</strong> <a target="_blank" href="'.esc_url(tuff_beatz_project_dashboard_url($post->ID)).'">Open Project Dashboard</a></p><p><label><strong>Credits / Personnel</strong></label><br><textarea style="width:100%;min-height:90px" name="tb_request_credits">'.esc_textarea($credits).'</textarea></p><p><label><strong>Payment Status</strong></label><br><select name="tb_request_payment_status">';foreach(array('Not invoiced','Quote sent','Deposit due','Deposit paid','Balance due','Paid in full') as $v)echo '<option '.selected($payment,$v,false).'>'.esc_html($v).'</option>';echo '</select></p><p><label><strong>Delivery Notes</strong></label><br><textarea style="width:100%;min-height:90px" name="tb_request_delivery_notes">'.esc_textarea($delivery).'</textarea></p><p><label><strong>External Final Delivery Links</strong></label><br><textarea style="width:100%;min-height:80px" name="tb_request_final_links">'.esc_textarea($final).'</textarea></p><hr><p><strong>Private Vault:</strong> '.count(tuff_beatz_vault_files($post->ID)).' file(s)</p><p><strong>Review Notes:</strong> '.count(tuff_beatz_review_notes($post->ID)).'</p>';}
function tuff_beatz_dashboard_admin_metabox(){add_meta_box('tb_dashboard_details',__('Client Dashboard & Delivery','tuff-beatz'),'tuff_beatz_dashboard_admin_box','tb_request','side','default');}add_action('add_meta_boxes_tb_request','tuff_beatz_dashboard_admin_metabox');
function tuff_beatz_delivery_upload_box($post){$files=array_values(array_filter(tuff_beatz_vault_files($post->ID),function($f){return ($f['category']??'')==='delivery';}));echo '<p>Upload review mixes and masters. Audio versions become playable in the client Mix Review workspace.</p>';if($files){echo '<ul>';foreach($files as $f)echo '<li><strong>'.esc_html($f['version']?:'Delivery').'</strong> — '.esc_html($f['name']).' — '.esc_html(tuff_beatz_review_status($post->ID,$f['id'])).'</li>';echo '</ul>';}echo '<form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tb_admin_upload_delivery_files"><input type="hidden" name="request_id" value="'.esc_attr($post->ID).'">';wp_nonce_field('tb_delivery_upload_'.$post->ID,'tb_delivery_upload_nonce');echo '<p><label><strong>Version</strong></label><br><input style="width:100%" name="delivery_version" value="Mix V1" placeholder="Mix V1, Mix V2, Master V1..."></p><p><input type="file" name="delivery_files[]" multiple accept=".wav,.aiff,.aif,.mp3,.m4a,.zip,.pdf,.txt,.mid,.midi"></p><p><button class="button button-primary" type="submit">Upload Review / Delivery Files</button></p></form>';}
function tuff_beatz_delivery_upload_metabox(){add_meta_box('tb_private_delivery',__('Private Vault — Mix Versions & Delivery','tuff-beatz'),'tuff_beatz_delivery_upload_box','tb_request','normal','default');}add_action('add_meta_boxes_tb_request','tuff_beatz_delivery_upload_metabox');
function tuff_beatz_save_dashboard_admin($id){if(!isset($_POST['tb_dashboard_admin_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_dashboard_admin_nonce'])),'tb_dashboard_admin_save')||!current_user_can('edit_post',$id))return;if(isset($_POST['tb_request_credits']))update_post_meta($id,'_tb_request_credits',sanitize_textarea_field(wp_unslash($_POST['tb_request_credits'])));if(isset($_POST['tb_request_payment_status']))update_post_meta($id,'_tb_request_payment_status',sanitize_text_field(wp_unslash($_POST['tb_request_payment_status'])));if(isset($_POST['tb_request_delivery_notes']))update_post_meta($id,'_tb_request_delivery_notes',sanitize_textarea_field(wp_unslash($_POST['tb_request_delivery_notes'])));if(isset($_POST['tb_request_final_links']))update_post_meta($id,'_tb_request_final_links',sanitize_textarea_field(wp_unslash($_POST['tb_request_final_links'])));}
add_action('save_post_tb_request','tuff_beatz_save_dashboard_admin',20);
