<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V13.5 — Release Candidate QA gate */
function tuff_beatz_rc_checks($id=0){$checks=array();$add=function($key,$label,$ok,$severity='critical',$detail='')use(&$checks){$checks[]=array('key'=>$key,'label'=>$label,'ok'=>(bool)$ok,'severity'=>$severity,'detail'=>$detail?:($ok?'PASS':'FAIL'));};
$required=array('tuff_beatz_vault_files','tuff_beatz_user_can_view_request','tuff_beatz_auth_can','tuff_beatz_integrity_report','tuff_beatz_runtime_health','tuff_beatz_delivery_confirmation_authorized','tuff_beatz_delivery_manifest','tuff_beatz_notifications','tuff_beatz_activity_history','tuff_beatz_event_signature');foreach($required as $fn)$add('fn-'.$fn,$fn,function_exists($fn),'critical');
$theme=get_template_directory();foreach(array('inc/private-file-vault.php','inc/project-dashboard.php','inc/final-delivery-guard.php','inc/delivery-engine.php','inc/project-notifications.php','inc/activity-intelligence.php','inc/production-hardening.php','inc/permission-hardening.php','inc/data-integrity.php','inc/event-deduplication.php','inc/runtime-health.php') as $file)$add('file-'.$file,$file,is_readable($theme.'/'.$file),'critical');
$root=function_exists('tuff_beatz_vault_root')?tuff_beatz_vault_root():'';$add('vault-writable','Private Vault writable',$root&&is_dir($root)&&is_writable($root),'critical');
$add('php-runtime','PHP runtime baseline',version_compare(PHP_VERSION,'8.0','>='),'warning','PHP '.PHP_VERSION);
if($id&&get_post_type($id)==='tb_request'){$integrity=function_exists('tuff_beatz_integrity_report')?tuff_beatz_integrity_report($id):array('issues'=>array(array('severity'=>'critical')));$blocking=false;foreach((array)($integrity['issues']??array()) as $x)if(in_array($x['severity']??'',array('critical','high'),true)){$blocking=true;break;}$add('project-integrity','Project data integrity',!$blocking,'critical',$blocking?'High/critical integrity conflict detected':'No blocking integrity conflict');$status=(string)(get_post_meta($id,'_tb_request_status',true)?:'new');if(in_array($status,array('delivery','completed'),true)){$add('delivery-evidence','Canonical delivery evidence',function_exists('tuff_beatz_has_final_delivery_evidence')&&tuff_beatz_has_final_delivery_evidence($id),'critical');$m=function_exists('tuff_beatz_delivery_manifest')?tuff_beatz_delivery_manifest($id):array();$add('delivery-manifest','Official delivery manifest',!empty($m['manifest_id'])&&!empty($m['files']),'critical');}if($status==='completed'){$add('completion-time','Delivery acceptance timestamp',(bool)get_post_meta($id,'_tb_delivery_confirmed_at',true),'critical');$add('completion-user','Delivery accepted by user',(bool)get_post_meta($id,'_tb_delivery_confirmed_by',true),'critical');}}
$critical=0;$warnings=0;foreach($checks as $c)if(!$c['ok']){$c['severity']==='critical'?$critical++:$warnings++;}return array('version'=>'13.5-RC1','status'=>$critical?'blocked':($warnings?'warning':'ready'),'critical'=>$critical,'warnings'=>$warnings,'checks'=>$checks,'checked_at'=>current_time('mysql'));}
function tuff_beatz_rc_store($id=0){$r=tuff_beatz_rc_checks($id);if($id)update_post_meta($id,'_tb_release_candidate_v13',$r);else update_option('_tb_release_candidate_v13',$r,false);return $r;}
function tuff_beatz_rc_guard_completion(){if(($_SERVER['REQUEST_METHOD']??'')!=='POST'||sanitize_key($_POST['action']??'')!=='tb_confirm_final_delivery')return;$id=(int)($_POST['request_id']??0);if(!$id)return;$r=tuff_beatz_rc_checks($id);if($r['critical']){$url=function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id).'#delivery':home_url('/client-portal/');wp_safe_redirect(add_query_arg('rc_blocked','qa',$url));exit;}}
add_action('admin_init','tuff_beatz_rc_guard_completion',4);
function tuff_beatz_rc_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id)return;$producer=function_exists('tuff_beatz_auth_is_producer')?tuff_beatz_auth_is_producer($id):current_user_can('edit_post',$id);if(!$producer)return;$r=tuff_beatz_rc_store($id);$blocked=sanitize_key(wp_unslash($_GET['rc_blocked']??''));?><script>document.addEventListener('DOMContentLoaded',function(){var root=document.querySelector('.tb-project-dashboard')||document.querySelector('main');if(!root)return;var box=document.createElement('section');box.className='tb-rc-panel tb-rc-<?php echo esc_attr($r['status']);?>';box.innerHTML=<?php ob_start();?><div class="tb-rc-head"><div><small>STUDIO OS <?php echo esc_html($r['version']);?></small><strong>Release Readiness</strong></div><span><?php echo esc_html(strtoupper($r['status']));?></span></div><?php if($blocked):?><p class="tb-rc-block">Final completion was blocked because the release QA gate detected a critical project/runtime issue.</p><?php endif;?><div class="tb-rc-summary"><b><?php echo esc_html((string)$r['critical']);?></b><span>CRITICAL</span><b><?php echo esc_html((string)$r['warnings']);?></b><span>WARNINGS</span></div><?php if($r['status']!=='ready'):?><div class="tb-rc-failures"><?php foreach($r['checks'] as $c)if(!$c['ok']):?><div><b><?php echo esc_html(strtoupper($c['severity']));?></b><p><?php echo esc_html($c['label']);?><span><?php echo esc_html($c['detail']);?></span></p></div><?php endif;?></div><?php endif;?><?php $html=ob_get_clean();echo wp_json_encode($html);?>;root.insertBefore(box,root.firstChild);});</script><?php }
add_action('wp_footer','tuff_beatz_rc_workspace',5);
function tuff_beatz_rc_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-rc-panel{max-width:1180px;margin:12px auto 20px;padding:16px;border:1px solid rgba(216,180,90,.22);border-radius:14px;background:rgba(9,9,9,.86)}.tb-rc-head{display:flex;justify-content:space-between;align-items:center}.tb-rc-head small{display:block;color:#8f7b4c;font-size:.54rem;letter-spacing:.14em}.tb-rc-head strong{color:#eee2c7;font-family:Cinzel,serif}.tb-rc-head>span{font-size:.58rem;letter-spacing:.12em;color:#dfc16c}.tb-rc-summary{display:flex;align-items:baseline;gap:7px;margin-top:12px}.tb-rc-summary b{color:#e4c466}.tb-rc-summary span{margin-right:10px;color:#716a5e;font-size:.52rem;letter-spacing:.1em}.tb-rc-failures{display:grid;gap:6px;margin-top:12px}.tb-rc-failures>div{display:flex;gap:10px;padding:8px 10px;border-left:2px solid #a98a47;background:rgba(255,255,255,.018)}.tb-rc-failures b{min-width:58px;color:#c9a853;font-size:.5rem}.tb-rc-failures p{margin:0;color:#c9c0ae;font-size:.64rem}.tb-rc-failures p span{display:block;color:#777066;font-size:.56rem;margin-top:2px}.tb-rc-block{color:#dbc78f;font-size:.68rem}.tb-rc-ready{border-color:rgba(216,180,90,.3)}');}
add_action('wp_enqueue_scripts','tuff_beatz_rc_assets',103);
