<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V13.7.1 — runtime health + reconciled upload failure protection */
function tuff_beatz_runtime_module_map(){return array(
 'vault'=>'tuff_beatz_vault_files',
 'permissions'=>'tuff_beatz_auth_can',
 'hardening'=>'tuff_beatz_hardening_status',
 'integrity'=>'tuff_beatz_integrity_report',
 'notifications'=>'tuff_beatz_notifications',
 'activity'=>'tuff_beatz_activity_history',
 'delivery'=>'tuff_beatz_delivery_manifest',
 'dedupe'=>'tuff_beatz_event_signature',
 'workflow'=>'tuff_beatz_workflow_apply_status'
 );}
function tuff_beatz_runtime_health($id=0){$checks=array();$critical=0;$warn=0;foreach(tuff_beatz_runtime_module_map() as $name=>$fn){$ok=function_exists($fn);$checks[]=array('name'=>'module-'.$name,'label'=>ucwords($name).' Module','status'=>$ok?'ok':'critical','detail'=>$ok?'Loaded':'Missing required function '.$fn);if(!$ok)$critical++;}
 $theme=get_template_directory();$required=array('functions.php','inc/private-file-vault.php','inc/project-dashboard.php','inc/final-delivery-guard.php','inc/delivery-engine.php','inc/project-notifications.php','inc/activity-intelligence.php','inc/production-hardening.php','inc/permission-hardening.php','inc/data-integrity.php','inc/event-deduplication.php');foreach($required as $file){$ok=is_readable($theme.'/'.$file);$checks[]=array('name'=>'file-'.sanitize_key($file),'label'=>'Theme file: '.$file,'status'=>$ok?'ok':'critical','detail'=>$ok?'Readable':'Missing or unreadable');if(!$ok)$critical++;}
 $root=function_exists('tuff_beatz_vault_root')?tuff_beatz_vault_root():'';$root_ok=$root&&is_dir($root)&&is_writable($root);$checks[]=array('name'=>'vault-storage','label'=>'Private Vault Storage','status'=>$root_ok?'ok':'critical','detail'=>$root_ok?'Writable private storage':'Private vault path is unavailable or not writable');if(!$root_ok)$critical++;
 $upload=wp_upload_dir();$upload_ok=empty($upload['error']);$checks[]=array('name'=>'wordpress-upload','label'=>'WordPress Upload Runtime','status'=>$upload_ok?'ok':'warning','detail'=>$upload_ok?'WordPress upload runtime available':sanitize_text_field((string)$upload['error']));if(!$upload_ok)$warn++;
 $php_ok=version_compare(PHP_VERSION,'8.0','>=');$checks[]=array('name'=>'php-version','label'=>'PHP '.PHP_VERSION,'status'=>$php_ok?'ok':'warning','detail'=>$php_ok?'Supported runtime baseline':'PHP 8.0+ recommended for Studio OS');if(!$php_ok)$warn++;
 $memory=ini_get('memory_limit');$checks[]=array('name'=>'php-memory','label'=>'PHP Memory Limit','status'=>'ok','detail'=>(string)$memory);
 if($id&&function_exists('tuff_beatz_integrity_report')){$r=tuff_beatz_integrity_report($id);$s=$r['issue_count']?($r['issue_count']>2?'warning':'warning'):'ok';$checks[]=array('name'=>'project-integrity','label'=>'Project Data Integrity','status'=>$s,'detail'=>$r['issue_count']?(string)$r['issue_count'].' issue(s) detected':'No integrity conflicts detected');if($r['issue_count'])$warn++;}
 return array('status'=>$critical?'critical':($warn?'warning':'ok'),'critical'=>$critical,'warnings'=>$warn,'checks'=>$checks,'checked_at'=>current_time('mysql'));
}
function tuff_beatz_runtime_store($id=0){$health=tuff_beatz_runtime_health($id);if($id)update_post_meta((int)$id,'_tb_runtime_health_v13',$health);else update_option('_tb_runtime_health_v13',$health,false);return $health;}
function tuff_beatz_runtime_upload_actions(){return array('tb_file_manager_upload','tb_upload_project_dashboard_files','tb_admin_upload_delivery_files','tb_producer_console_upload');}
function tuff_beatz_runtime_guard_upload(){if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;$action=sanitize_key($_POST['action']??'');if(!in_array($action,tuff_beatz_runtime_upload_actions(),true))return;$health=tuff_beatz_runtime_health((int)($_POST['request_id']??0));if($health['critical']){$id=(int)($_POST['request_id']??0);$url=$id&&function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id).'#files':home_url('/producer-portal/');wp_safe_redirect(add_query_arg('runtime_blocked','storage',$url));exit;}}
add_action('admin_init','tuff_beatz_runtime_guard_upload',3);
function tuff_beatz_runtime_workspace(){if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id)return;$producer=function_exists('tuff_beatz_auth_is_producer')?tuff_beatz_auth_is_producer($id):current_user_can('edit_post',$id);if(!$producer)return;$h=tuff_beatz_runtime_store($id);$blocked=sanitize_key(wp_unslash($_GET['runtime_blocked']??''));if($h['status']==='ok'&&!$blocked)return;?><script>document.addEventListener('DOMContentLoaded',function(){var root=document.querySelector('.tb-project-dashboard')||document.querySelector('main');if(!root)return;var box=document.createElement('section');box.className='tb-runtime-health tb-runtime-<?php echo esc_attr($h['status']);?>';box.innerHTML=<?php ob_start();?><div class="tb-runtime-head"><div><small>STUDIO OS V13.7</small><strong>Runtime Health</strong></div><span><?php echo esc_html(strtoupper($h['status']));?></span></div><?php if($blocked):?><p class="tb-runtime-block">Upload blocked because Studio OS detected a critical storage/runtime problem.</p><?php endif;?><div class="tb-runtime-list"><?php foreach($h['checks'] as $c){if($c['status']==='ok')continue;?><div><b><?php echo esc_html(strtoupper($c['status']));?></b><p><strong><?php echo esc_html($c['label']);?></strong><span><?php echo esc_html($c['detail']);?></span></p></div><?php }?></div><?php $html=ob_get_clean();echo wp_json_encode($html);?>;root.insertBefore(box,root.firstChild);});</script><?php }
add_action('wp_footer','tuff_beatz_runtime_workspace',4);
function tuff_beatz_runtime_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-runtime-health{max-width:1180px;margin:12px auto 20px;padding:16px;border:1px solid rgba(216,180,90,.22);border-radius:14px;background:rgba(10,10,10,.82)}.tb-runtime-head{display:flex;justify-content:space-between;align-items:center}.tb-runtime-head small{display:block;color:#8d7b50;font-size:.54rem;letter-spacing:.14em}.tb-runtime-head strong{color:#e8dfca;font-family:Cinzel,serif}.tb-runtime-head>span{font-size:.58rem;letter-spacing:.12em;color:#d8bb65}.tb-runtime-list{display:grid;gap:7px;margin-top:12px}.tb-runtime-list>div{display:flex;gap:10px;padding:9px 10px;background:rgba(255,255,255,.02);border-left:2px solid #a48949}.tb-runtime-list b{min-width:58px;font-size:.5rem;color:#c7a553}.tb-runtime-list p{margin:0}.tb-runtime-list p strong,.tb-runtime-list p span{display:block}.tb-runtime-list p strong{color:#d8d0bf;font-size:.65rem}.tb-runtime-list p span{color:#817a6e;font-size:.58rem;margin-top:2px}.tb-runtime-block{color:#d6c187;font-size:.68rem}');}
add_action('wp_enqueue_scripts','tuff_beatz_runtime_assets',102);
