<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.12 — Runtime Evidence History & Regression Detection. Read-only comparison of append-preserving V16.11 records. */
function tuff_beatz_v1612_check_map($record){$map=array();foreach((array)($record['checks']??array()) as $c){$key=(string)($c['key']??'');if($key!=='')$map[$key]=array('label'=>(string)($c['label']??$key),'status'=>sanitize_key($c['status']??'unknown'),'detail'=>(string)($c['detail']??''));}return $map;}
function tuff_beatz_v1612_regression($previous,$current){
 if(!$previous||!$current)return array('state'=>'baseline','label'=>'BASELINE','regressions'=>array(),'recoveries'=>array());
 $a=tuff_beatz_v1612_check_map($previous);$b=tuff_beatz_v1612_check_map($current);$reg=array();$rec=array();foreach($b as $key=>$now){$before=$a[$key]['status']??'unknown';if($before==='pass'&&$now['status']==='fail')$reg[]=array('key'=>$key,'label'=>$now['label'],'detail'=>$now['detail']);if($before==='fail'&&$now['status']==='pass')$rec[]=array('key'=>$key,'label'=>$now['label'],'detail'=>$now['detail']);}
 $state=$reg?'regression':($rec?'recovery':'stable');return array('state'=>$state,'label'=>strtoupper($state),'regressions'=>$reg,'recoveries'=>$rec);
}
function tuff_beatz_v1612_history_rows($id){$h=function_exists('tuff_beatz_v1611_evidence_history')?tuff_beatz_v1611_evidence_history($id):array();$rows=array();$prev=array();foreach($h as $r){$change=tuff_beatz_v1612_regression($prev,$r);$rows[]=array('evidence_id'=>(string)($r['evidence_id']??''),'captured_at'=>(string)($r['captured_at']??''),'status'=>sanitize_key($r['status']??'attention'),'passed'=>(int)($r['passed']??0),'failed'=>(int)($r['failed']??0),'change'=>$change);$prev=$r;}return $rows;}
function tuff_beatz_v1612_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request')return;$producer=function_exists('tuff_beatz_v1611_is_producer')?tuff_beatz_v1611_is_producer($id):(function_exists('tuff_beatz_auth_is_producer')?tuff_beatz_auth_is_producer($id):current_user_can('edit_post',$id));if(!$producer)return;$rows=tuff_beatz_v1612_history_rows($id);if(!$rows)return;$latest=end($rows);?><script>document.addEventListener('DOMContentLoaded',function(){var host=document.querySelector('.tb-v1611-evidence');if(!host)return;var box=document.createElement('section');box.className='tb-v1612-history is-<?php echo esc_attr($latest['change']['state']);?>';box.innerHTML=<?php ob_start();?><div class="tb-v1612-head"><div><small>V16.12 • READ-ONLY RUNTIME COMPARISON</small><strong>Runtime Evidence History</strong></div><b><?php echo esc_html($latest['change']['label']);?></b></div><?php if(!empty($latest['change']['regressions'])):?><div class="tb-v1612-alert"><strong>PASS → FAIL regression detected</strong><?php foreach($latest['change']['regressions'] as $r):?><span><?php echo esc_html($r['label']);?> • <?php echo esc_html($r['detail']);?></span><?php endforeach;?></div><?php elseif(!empty($latest['change']['recoveries'])):?><div class="tb-v1612-recovery"><strong>FAIL → PASS recovery detected</strong><?php foreach($latest['change']['recoveries'] as $r):?><span><?php echo esc_html($r['label']);?></span><?php endforeach;?></div><?php endif;?><div class="tb-v1612-list"><?php foreach(array_slice(array_reverse($rows),0,8) as $r):?><div><i></i><p><strong><?php echo esc_html(strtoupper($r['status']));?> • <?php echo esc_html($r['change']['label']);?></strong><span><?php echo esc_html($r['captured_at']);?> • <?php echo esc_html((string)$r['passed']);?> pass / <?php echo esc_html((string)$r['failed']);?> fail</span><small><?php echo esc_html($r['evidence_id']);?></small></p></div><?php endforeach;?></div><p class="tb-v1612-note">Regression status is computed from preserved evidence records. Historical runtime evidence is not edited or deleted.</p><?php $html=ob_get_clean();echo wp_json_encode($html);?>;host.insertAdjacentElement('afterend',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v1612_workspace',9);
function tuff_beatz_v1612_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v1612-history{margin:0 0 12px;padding:13px 14px;border:1px solid rgba(216,180,90,.13);border-radius:10px;background:rgba(5,5,5,.38)}.tb-v1612-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.tb-v1612-head small{display:block;color:#84744f;font-size:.45rem;letter-spacing:.12em}.tb-v1612-head strong{display:block;color:#d2c8b5;font-size:.61rem;margin-top:2px}.tb-v1612-head>b{color:#b99a4e;font-size:.47rem;letter-spacing:.1em}.tb-v1612-alert,.tb-v1612-recovery{margin-top:8px;padding:8px 10px;border-left:3px solid rgba(216,180,90,.48);background:rgba(216,180,90,.035)}.tb-v1612-alert strong,.tb-v1612-alert span,.tb-v1612-recovery strong,.tb-v1612-recovery span{display:block}.tb-v1612-alert strong,.tb-v1612-recovery strong{color:#c9b47e;font-size:.5rem}.tb-v1612-alert span,.tb-v1612-recovery span{color:#756d60;font-size:.45rem;margin-top:2px}.tb-v1612-list{display:grid;gap:3px;margin-top:8px}.tb-v1612-list>div{display:flex;gap:8px;padding:6px 7px;border-bottom:1px solid rgba(255,255,255,.03)}.tb-v1612-list i{width:6px;height:6px;border-radius:50%;margin-top:4px;background:#8b7950}.tb-v1612-list p{margin:0}.tb-v1612-list strong,.tb-v1612-list span,.tb-v1612-list small{display:block}.tb-v1612-list strong{color:#bfb6a5;font-size:.49rem}.tb-v1612-list span{color:#655f55;font-size:.44rem;margin-top:1px}.tb-v1612-list small{color:#4f4a42;font-size:.41rem;margin-top:1px;word-break:break-all}.tb-v1612-note{margin:8px 0 0;color:#625d54;font-size:.45rem}');}
add_action('wp_enqueue_scripts','tuff_beatz_v1612_assets',114);
