<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.13 — Conservative Runtime Readiness Decision. Read-only synthesis; not browser-level certification. */
function tuff_beatz_v1613_decision($id){
 $gate=function_exists('tuff_beatz_v163_readiness_gate')?tuff_beatz_v163_readiness_gate($id):array('verdict'=>'attention');
 $history=function_exists('tuff_beatz_v1611_evidence_history')?tuff_beatz_v1611_evidence_history($id):array();$latest=$history?end($history):array();
 $rows=function_exists('tuff_beatz_v1612_history_rows')?tuff_beatz_v1612_history_rows($id):array();$runtime_change=$rows?end($rows):array();
 $cert=function_exists('tuff_beatz_v167_certification_state')?tuff_beatz_v167_certification_state($id):array('state'=>'none');
 $ledger=function_exists('tuff_beatz_v168_evidence_ledger')?tuff_beatz_v168_evidence_ledger($id):array();$ledger_issues=function_exists('tuff_beatz_v168_ledger_integrity')?tuff_beatz_v168_ledger_integrity($id,$ledger):array();
 $reasons=array();$blocked=false;$attention=false;
 $gate_v=sanitize_key($gate['verdict']??'attention');if($gate_v==='blocked'){$blocked=true;$reasons[]='Production readiness gate is BLOCKED.';}elseif($gate_v!=='ready'){$attention=true;$reasons[]='Production readiness gate requires attention.';}
 if(!$latest){$attention=true;$reasons[]='No captured runtime smoke-test evidence exists.';}elseif(($latest['failed']??0)>0||($latest['status']??'')!=='pass'){$blocked=true;$reasons[]='Latest captured runtime evidence contains failed checks.';}
 $change=sanitize_key($runtime_change['change']['state']??'baseline');if($change==='regression'){$blocked=true;$reasons[]='Latest runtime comparison contains PASS → FAIL regression(s).';}
 if(!empty($ledger_issues)){$blocked=true;$reasons[]='Production evidence ledger contains broken record references.';}
 $cert_state=sanitize_key($cert['state']??'none');if(in_array($cert_state,array('integrity_attention','current_attention'),true)){$blocked=true;$reasons[]='Internal certification integrity requires attention.';}elseif(in_array($cert_state,array('none','superseded'),true)){$attention=true;$reasons[]='No current internal producer certification represents the latest verification state.';}
 $decision=$blocked?'blocked':($attention?'attention':'ready');if(!$reasons)$reasons[]='Code-level readiness, runtime evidence, regression state, ledger integrity and internal certification are aligned.';
 return array('version'=>'16.13','decision'=>$decision,'gate'=>$gate_v,'runtime_status'=>sanitize_key($latest['status']??'none'),'runtime_failed'=>(int)($latest['failed']??0),'runtime_change'=>$change,'certification_state'=>$cert_state,'ledger_issues'=>count($ledger_issues),'reasons'=>$reasons,'checked_at'=>current_time('mysql'),'scope'=>'Server-side and internal evidence decision only. Browser workflows, actual upload transactions, audio playback, authenticated multi-role sessions, and external-network behavior remain outside this decision.');
}
function tuff_beatz_v1613_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request')return;$producer=function_exists('tuff_beatz_v1611_is_producer')?tuff_beatz_v1611_is_producer($id):(function_exists('tuff_beatz_auth_is_producer')?tuff_beatz_auth_is_producer($id):current_user_can('edit_post',$id));if(!$producer)return;$d=tuff_beatz_v1613_decision($id);?><script>document.addEventListener('DOMContentLoaded',function(){var host=document.querySelector('.tb-v1612-history')||document.querySelector('.tb-v1611-evidence');if(!host)return;var box=document.createElement('section');box.className='tb-v1613-decision is-<?php echo esc_attr($d['decision']);?>';box.innerHTML=<?php ob_start();?><div class="tb-v1613-head"><div><small>V16.13 • CONSERVATIVE PRODUCTION DECISION</small><strong>Runtime Readiness Decision</strong><span><?php echo esc_html($d['checked_at']);?></span></div><b><?php echo esc_html(strtoupper($d['decision']));?></b></div><div class="tb-v1613-grid"><div><small>READINESS GATE</small><strong><?php echo esc_html(strtoupper($d['gate']));?></strong></div><div><small>RUNTIME EVIDENCE</small><strong><?php echo esc_html(strtoupper($d['runtime_status']));?></strong></div><div><small>REGRESSION</small><strong><?php echo esc_html(strtoupper($d['runtime_change']));?></strong></div><div><small>CERTIFICATION</small><strong><?php echo esc_html(strtoupper(str_replace('_',' ',$d['certification_state'])));?></strong></div><div><small>LEDGER ISSUES</small><strong><?php echo esc_html((string)$d['ledger_issues']);?></strong></div></div><div class="tb-v1613-reasons"><?php foreach($d['reasons'] as $reason):?><span><?php echo esc_html($reason);?></span><?php endforeach;?></div><p><?php echo esc_html($d['scope']);?></p><?php $html=ob_get_clean();echo wp_json_encode($html);?>;host.insertAdjacentElement('afterend',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v1613_workspace',10);
function tuff_beatz_v1613_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v1613-decision{margin:0 0 13px;padding:15px;border:1px solid rgba(216,180,90,.17);border-radius:11px;background:linear-gradient(145deg,rgba(216,180,90,.04),rgba(0,0,0,.28))}.tb-v1613-head{display:flex;align-items:center;justify-content:space-between;gap:14px}.tb-v1613-head small,.tb-v1613-head strong,.tb-v1613-head span{display:block}.tb-v1613-head small{color:#8b784c;font-size:.46rem;letter-spacing:.13em}.tb-v1613-head strong{color:#ddd2bb;font-size:.7rem;margin-top:2px}.tb-v1613-head span{color:#5f594f;font-size:.43rem;margin-top:2px}.tb-v1613-head>b{color:#c5a654;font-size:.58rem;letter-spacing:.13em;border:1px solid rgba(216,180,90,.3);border-radius:999px;padding:6px 10px}.tb-v1613-decision.is-blocked .tb-v1613-head>b{border-width:2px}.tb-v1613-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:11px}.tb-v1613-grid>div{padding:7px 8px;border:1px solid rgba(255,255,255,.035);border-radius:7px}.tb-v1613-grid small,.tb-v1613-grid strong{display:block}.tb-v1613-grid small{color:#655f55;font-size:.4rem;letter-spacing:.08em}.tb-v1613-grid strong{color:#bfb5a2;font-size:.48rem;margin-top:2px}.tb-v1613-reasons{margin-top:9px}.tb-v1613-reasons span{display:block;color:#807767;font-size:.46rem;margin-top:2px}.tb-v1613-decision>p{margin:9px 0 0;color:#5f594f;font-size:.44rem}@media(max-width:760px){.tb-v1613-grid{grid-template-columns:1fr 1fr}}');}
add_action('wp_enqueue_scripts','tuff-beatz_v1613_assets',115);
