<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.10.1 — Runtime Smoke-Test Control. Non-destructive runtime observations only; no browser certification claim. */
function tuff_beatz_v1610_smoke_checks($id){
 $id=(int)$id;$checks=array();
 $add=function($key,$label,$ok,$detail='')use(&$checks){$checks[]=array('key'=>$key,'label'=>$label,'status'=>$ok?'pass':'fail','detail'=>$detail);};
 $add('project','Project Runtime',get_post_type($id)==='tb_request','tb_request #'.$id);
 $health=function_exists('tuff_beatz_runtime_health')?tuff_beatz_runtime_health($id):array('status'=>'critical','critical'=>1,'warnings'=>0);
 $add('runtime','Runtime Health',($health['critical']??1)===0,strtoupper((string)($health['status']??'unknown')).' • '.(int)($health['warnings']??0).' warning(s)');
 $root=function_exists('tuff_beatz_vault_root')?tuff_beatz_vault_root():'';$add('vault','Private Vault Runtime',$root&&is_dir($root)&&is_writable($root),$root?'Private storage path resolved':'Private storage unavailable');
 $required=array('tuff_beatz_auth_can'=>'Authorization','tuff_beatz_vault_files'=>'Vault API','tuff_beatz_workflow_apply_status'=>'Workflow Engine','tuff_beatz_delivery_manifest'=>'Delivery Engine','tuff_beatz_integrity_report'=>'Integrity Engine','tuff_beatz_v163_readiness_gate'=>'Readiness Gate','tuff_beatz_v169_summary'=>'Verification Summary');foreach($required as $fn=>$label)$add('fn-'.sanitize_key($fn),$label,function_exists($fn),function_exists($fn)?'Callable':'Missing '.$fn);
 $upload=wp_upload_dir();$add('wp-upload','WordPress Upload Runtime',empty($upload['error']),empty($upload['error'])?'Available':sanitize_text_field((string)$upload['error']));
 $db_ok=false;global $wpdb;if($wpdb instanceof wpdb){$probe=$wpdb->get_var('SELECT 1');$db_ok=((string)$probe==='1');}$add('database','WordPress Database Read',$db_ok,$db_ok?'Read probe succeeded':'Read probe failed');
 $fail=count(array_filter($checks,function($c){return $c['status']==='fail';}));return array('version'=>'16.10.1','status'=>$fail?'attention':'pass','passed'=>count($checks)-$fail,'failed'=>$fail,'checks'=>$checks,'checked_at'=>current_time('mysql'));
}
function tuff_beatz_v1610_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request')return;if(!function_exists('tuff_beatz_auth_is_producer')||!tuff_beatz_auth_is_producer($id))return;$s=tuff_beatz_v1610_smoke_checks($id);?><script>document.addEventListener('DOMContentLoaded',function(){var host=document.querySelector('.tb-v169-summary')||document.querySelector('.tb-v16-verification');if(!host)return;var box=document.createElement('section');box.className='tb-v1610-smoke is-<?php echo esc_attr($s['status']);?>';box.innerHTML=<?php ob_start();?><div class="tb-v1610-head"><div><small>V16.10.1 • NON-DESTRUCTIVE RUNTIME PROBES</small><strong>Runtime Smoke-Test Control</strong><span><?php echo esc_html($s['checked_at']);?></span></div><b><?php echo esc_html(strtoupper($s['status']));?></b></div><div class="tb-v1610-score"><strong><?php echo esc_html((string)$s['passed']);?></strong><span>PASS</span><strong><?php echo esc_html((string)$s['failed']);?></strong><span>FAIL</span></div><div class="tb-v1610-list"><?php foreach($s['checks'] as $c):?><div class="is-<?php echo esc_attr($c['status']);?>"><i></i><p><strong><?php echo esc_html($c['label']);?></strong><span><?php echo esc_html($c['detail']);?></span></p><b><?php echo esc_html(strtoupper($c['status']));?></b></div><?php endforeach;?></div><p class="tb-v1610-note">These probes execute inside WordPress/PHP and are intentionally non-destructive. They do not simulate client/producer browser clicks, uploads, audio playback, authentication sessions, or external network behavior.</p><?php $html=ob_get_clean();echo wp_json_encode($html);?>;host.insertAdjacentElement('afterend',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v1610_workspace',7);
function tuff_beatz_v1610_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v1610-smoke{margin:0 0 12px;padding:14px;border:1px solid rgba(216,180,90,.16);border-radius:11px;background:rgba(6,6,6,.55)}.tb-v1610-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.tb-v1610-head small,.tb-v1610-head strong,.tb-v1610-head span{display:block}.tb-v1610-head small{color:#8d7b50;font-size:.46rem;letter-spacing:.13em}.tb-v1610-head strong{color:#d8d0bf;font-size:.68rem;margin-top:2px}.tb-v1610-head span{color:#625d54;font-size:.44rem;margin-top:2px}.tb-v1610-head>b{color:#c5a654;font-size:.5rem;letter-spacing:.11em}.tb-v1610-score{display:flex;align-items:baseline;gap:6px;margin-top:9px}.tb-v1610-score strong{color:#d8c99e;font-size:.72rem}.tb-v1610-score span{color:#655f55;font-size:.43rem;margin-right:8px}.tb-v1610-list{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:9px}.tb-v1610-list>div{display:flex;align-items:flex-start;gap:7px;padding:7px 8px;border:1px solid rgba(255,255,255,.035);border-radius:7px}.tb-v1610-list i{width:6px;height:6px;border-radius:50%;margin-top:4px;background:#b99a4e}.tb-v1610-list .is-fail i{box-shadow:0 0 0 2px rgba(185,154,78,.18)}.tb-v1610-list p{margin:0;flex:1}.tb-v1610-list p strong,.tb-v1610-list p span{display:block}.tb-v1610-list p strong{color:#c9c0ae;font-size:.52rem}.tb-v1610-list p span{color:#655f55;font-size:.44rem;margin-top:2px}.tb-v1610-list>div>b{color:#8d7b50;font-size:.42rem}.tb-v1610-note{margin:9px 0 0;color:#655f55;font-size:.46rem}@media(max-width:680px){.tb-v1610-list{grid-template-columns:1fr}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v1610_assets',112);
require_once get_template_directory() . '/inc/runtime-test-evidence.php';
