<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V16.11 — Producer-triggered append-preserving runtime smoke-test evidence. No workflow/business-state mutation. */
function tuff_beatz_v1611_evidence_history($id){$rows=get_post_meta((int)$id,'_tb_runtime_test_evidence_v1611',false);return is_array($rows)?array_values(array_filter($rows,'is_array')):array();}
function tuff_beatz_v1611_is_producer($id){return function_exists('tuff_beatz_auth_is_producer')?tuff_beatz_auth_is_producer((int)$id):current_user_can('edit_post',(int)$id);}
function tuff_beatz_v1611_capture(){
 $id=(int)($_POST['request_id']??0);if(!$id||get_post_type($id)!=='tb_request')wp_die('Invalid project.');
 if(!is_user_logged_in()||!tuff_beatz_v1611_is_producer($id))wp_die('Not authorized.');
 if(!isset($_POST['tb_v1611_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_v1611_nonce'])),'tb_v1611_capture_'.$id))wp_die('Invalid request.');
 if(!function_exists('tuff_beatz_v1610_smoke_checks'))wp_die('Runtime smoke-test engine unavailable.');
 $smoke=tuff_beatz_v1610_smoke_checks($id);$record=array('evidence_id'=>wp_generate_uuid4(),'version'=>'16.11','project_id'=>$id,'smoke_version'=>(string)($smoke['version']??'16.10'),'status'=>sanitize_key($smoke['status']??'attention'),'passed'=>(int)($smoke['passed']??0),'failed'=>(int)($smoke['failed']??0),'checks'=>(array)($smoke['checks']??array()),'captured_by'=>get_current_user_id(),'captured_at'=>current_time('mysql'),'scope'=>'Server-side WordPress/PHP smoke-test evidence only. No browser interaction, upload transaction, audio playback, authentication-session, or external-network certification.');
 add_post_meta($id,'_tb_runtime_test_evidence_v1611',$record,false);
 wp_safe_redirect(add_query_arg(array('project'=>$id,'runtime_evidence'=>'captured'),home_url('/project-dashboard/')));exit;
}
add_action('admin_post_tb_capture_runtime_test_evidence','tuff_beatz_v1611_capture');
function tuff_beatz_v1611_workspace(){
 if(!is_page('project-dashboard')||!is_user_logged_in())return;$id=(int)($_GET['project']??0);if(!$id||get_post_type($id)!=='tb_request'||!tuff_beatz_v1611_is_producer($id))return;$history=tuff_beatz_v1611_evidence_history($id);$latest=$history?end($history):array();?><script>document.addEventListener('DOMContentLoaded',function(){var host=document.querySelector('.tb-v1610-smoke');if(!host)return;var box=document.createElement('section');box.className='tb-v1611-evidence';box.innerHTML=<?php ob_start();?><div><small>V16.11 • APPEND-PRESERVING RUNTIME EVIDENCE</small><strong>Runtime Test Evidence</strong><?php if($latest):?><span>Latest: <?php echo esc_html(strtoupper($latest['status']??'unknown'));?> • <?php echo esc_html((string)($latest['passed']??0));?> pass / <?php echo esc_html((string)($latest['failed']??0));?> fail • <?php echo esc_html($latest['captured_at']??'');?></span><em><?php echo esc_html($latest['evidence_id']??'');?></em><?php else:?><span>No runtime evidence has been captured yet.</span><?php endif;?></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tb_capture_runtime_test_evidence"><input type="hidden" name="request_id" value="<?php echo esc_attr((string)$id);?>"><?php wp_nonce_field('tb_v1611_capture_'.$id,'tb_v1611_nonce');?><button type="submit">CAPTURE RUNTIME EVIDENCE</button></form><?php $html=ob_get_clean();echo wp_json_encode($html);?>;host.insertAdjacentElement('afterend',box);});</script><?php }
add_action('wp_footer','tuff_beatz_v1611_workspace',8);
function tuff_beatz_v1611_assets(){if(!is_page('project-dashboard'))return;wp_add_inline_style('tuff-beatz-project-portal','.tb-v1611-evidence{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:0 0 12px;padding:12px 14px;border:1px solid rgba(216,180,90,.14);border-radius:10px;background:rgba(216,180,90,.02)}.tb-v1611-evidence small,.tb-v1611-evidence strong,.tb-v1611-evidence span,.tb-v1611-evidence em{display:block}.tb-v1611-evidence small{color:#8d7b50;font-size:.45rem;letter-spacing:.12em}.tb-v1611-evidence strong{color:#d5cbb8;font-size:.61rem;margin-top:2px}.tb-v1611-evidence span{color:#6f685d;font-size:.47rem;margin-top:2px}.tb-v1611-evidence em{color:#514c44;font-size:.42rem;font-style:normal;margin-top:2px;word-break:break-all}.tb-v1611-evidence button{border:1px solid rgba(216,180,90,.34);border-radius:7px;background:rgba(216,180,90,.07);color:#d2b55d;padding:8px 10px;font-size:.47rem;letter-spacing:.09em;cursor:pointer}@media(max-width:680px){.tb-v1611-evidence{align-items:flex-start;flex-direction:column}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v1611_assets',113);
