<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V15.1 — Strategic Intelligence Command Center */
function tuff_beatz_v151_intelligence(){
 $score=function_exists('tuff_beatz_v1414_scorecard')?tuff_beatz_v1414_scorecard():array();
 $targets=function_exists('tuff_beatz_v1416_targets')?tuff_beatz_v1416_targets():array();
 $forecast=$score['forecast']??array();$operating=$score['operating']??array();$trends=$score['trends']??array();$pipeline=$score['pipeline']??array();$business=$score['business']??array();
 $monthly=(float)($forecast['month_collected']??0);$goal=(float)($targets['monthly_revenue']??($forecast['goal']??0));$annual=(float)($targets['annual_revenue']??0);$weighted=(float)($pipeline['weighted_value']??0);$receivable=(float)($business['receivable']??0);$margin=$operating['operating_margin']??null;$growth=$trends['revenue_change']??null;
 $pace=$annual>0?min(200,(($monthly*12)/$annual)*100):null;$coverage=$goal>0?(($weighted+$receivable)/$goal)*100:null;
 $priorities=array();
 if($pace!==null&&$pace<80)$priorities[]='Annualized collection pace is materially below the configured annual revenue objective.';
 if($coverage!==null&&$coverage<(float)($targets['pipeline_coverage']??100))$priorities[]='Forward commercial coverage is below the configured pipeline objective.';
 if($margin!==null&&$margin<(float)($targets['operating_margin']??20))$priorities[]='Covered operating margin is below the executive target.';
 if($growth!==null&&$growth<(float)($targets['monthly_growth']??5))$priorities[]='Collection momentum is below the configured monthly growth objective.';
 if(!$priorities)$priorities[]='No major strategic exception is currently detected from configured targets and recorded Business OS data.';
 return array('score'=>$score['score']??null,'grade'=>$score['grade']??'N/A','pace'=>$pace,'coverage'=>$coverage,'margin'=>$margin,'growth'=>$growth,'monthly'=>$monthly,'annual_goal'=>$annual,'weighted'=>$weighted,'receivable'=>$receivable,'priorities'=>$priorities);
}
function tuff_beatz_v151_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$x=tuff_beatz_v151_intelligence();ob_start();?><section class="tb-v151-strategy"><div class="tb-v151-head"><div><small>STRATEGIC INTELLIGENCE • V15.1</small><h3>Executive Strategy Command</h3><p>A decision-support layer translating Business OS performance into strategic direction. It does not execute financial or commercial decisions automatically.</p></div><div class="tb-v151-index"><strong><?php echo $x['score']===null?'N/A':esc_html((string)$x['score']);?></strong><span>BUSINESS INDEX</span><b><?php echo esc_html($x['grade']);?></b></div></div><div class="tb-v151-grid"><article><small>ANNUAL REVENUE PACE</small><strong><?php echo $x['pace']===null?'N/A':esc_html(number_format($x['pace'],1).'%');?></strong><p>Annualized from current-month recorded collections versus configured annual objective.</p></article><article><small>FORWARD COVERAGE</small><strong><?php echo $x['coverage']===null?'N/A':esc_html(number_format($x['coverage'],1).'%');?></strong><p>Weighted pipeline plus receivables relative to the configured monthly revenue objective.</p></article><article><small>OPERATING MARGIN</small><strong><?php echo $x['margin']===null?'N/A':esc_html(number_format((float)$x['margin'],1).'%');?></strong><p>Management operating view based on available cost-covered records.</p></article><article><small>COLLECTION MOMENTUM</small><strong><?php echo $x['growth']===null?'N/A':esc_html(number_format((float)$x['growth'],1).'%');?></strong><p>Month-over-month recorded collection movement from the financial trend layer.</p></article></div><div class="tb-v151-priorities"><small>STRATEGIC PRIORITIES</small><?php foreach($x['priorities'] as $p):?><p><?php echo esc_html($p);?></p><?php endforeach;?></div><p class="tb-v151-foot">Strategic Intelligence is internal management guidance derived from recorded Studio Business OS data. It is not a valuation, accounting opinion, financial forecast guarantee, or autonomous decision system.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var a=document.querySelector('.tb-v1416-kpi')||document.querySelector('.tb-v1415-actions');if(!a||document.querySelector('.tb-v151-strategy'))return;var b=document.createElement('div');b.innerHTML=<?php echo wp_json_encode($html);?>;a.insertAdjacentElement('afterend',b.firstElementChild);var e=document.querySelector('.tb-biz-hero .eyebrow');if(e)e.textContent='TUFF BEATZ • STRATEGIC INTELLIGENCE V15.1';});</script><?php }
add_action('wp_footer','tuff_beatz_v151_panel',17);
function tuff_beatz_v151_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v151-strategy{margin-top:18px;padding:22px;border:1px solid rgba(216,180,90,.2);border-radius:18px;background:linear-gradient(145deg,#090909,#0c0b09)}.tb-v151-head{display:flex;justify-content:space-between;gap:24px;align-items:center;padding-bottom:16px;border-bottom:1px solid rgba(255,255,255,.05)}.tb-v151-head small,.tb-v151-priorities small{color:#a68a49;font-size:.52rem;letter-spacing:.14em}.tb-v151-head h3{margin:4px 0;color:#e3d9c5;font-family:Cinzel,serif}.tb-v151-head p,.tb-v151-foot{max-width:720px;color:#756d60;font-size:.56rem;line-height:1.5}.tb-v151-index{text-align:center;min-width:125px;padding:12px;border:1px solid rgba(216,180,90,.2);border-radius:14px}.tb-v151-index strong,.tb-v151-index span,.tb-v151-index b{display:block}.tb-v151-index strong{color:#e5c969;font:2rem Cinzel,serif}.tb-v151-index span{color:#776b51;font-size:.46rem}.tb-v151-index b{margin-top:3px;color:#b99d5a;font-size:.6rem}.tb-v151-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:14px}.tb-v151-grid article{padding:13px;border:1px solid rgba(255,255,255,.05);border-radius:12px}.tb-v151-grid small{color:#756b59;font-size:.45rem}.tb-v151-grid strong{display:block;margin:6px 0;color:#d8bd6b;font:1rem Cinzel,serif}.tb-v151-grid p,.tb-v151-priorities p{color:#7e766a;font-size:.53rem;line-height:1.45}.tb-v151-priorities{margin-top:10px;padding:14px;border:1px solid rgba(255,255,255,.05);border-radius:12px}.tb-v151-priorities p{margin:7px 0 0}.tb-v151-foot{margin:10px 0 0}@media(max-width:850px){.tb-v151-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.tb-v151-head{align-items:flex-start;flex-direction:column}.tb-v151-grid{grid-template-columns:1fr}.tb-v151-index{text-align:left}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v151_css',113);
