<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V15.2 — Strategic Risk & Opportunity Intelligence */
function tuff_beatz_v152_intelligence(){
 $s=function_exists('tuff_beatz_v151_intelligence')?tuff_beatz_v151_intelligence():array();
 $score=$s['score']??array();$targets=function_exists('tuff_beatz_v1416_targets')?tuff_beatz_v1416_targets():array();
 $operating=$score['operating']??array();$trends=$score['trends']??array();$business=$score['business']??array();$pipeline=$score['pipeline']??array();
 $risks=array();$opps=array();
 $add=function(&$set,$severity,$domain,$title,$evidence){$rank=array('critical'=>4,'high'=>3,'medium'=>2,'low'=>1);$set[]=array('severity'=>$severity,'rank'=>$rank[$severity]??1,'domain'=>$domain,'title'=>$title,'evidence'=>$evidence);};
 $goal=(float)($targets['monthly_revenue']??0);$weighted=(float)($pipeline['weighted_value']??0);$recv=(float)($business['receivable']??0);$margin=$operating['operating_margin']??null;$coverage=(float)($operating['cost_coverage']??0);$growth=$trends['revenue_change']??null;$over=(float)($operating['overhead']??0);$covered=(float)($operating['covered_collected']??0);
 if($goal>0&&$weighted+$recv<$goal*.5)$add($risks,'high','PIPELINE','Forward revenue exposure','Weighted pipeline plus receivables cover less than 50% of the monthly revenue objective.');
 if($margin!==null&&$margin<(float)($targets['operating_margin']??20))$add($risks,'high','MARGIN','Profitability pressure','Covered operating margin is below the configured executive target.');
 if($coverage<(float)($targets['cost_coverage']??70))$add($risks,'medium','DATA','Profitability confidence risk','Recorded cost-basis coverage is below the configured data-quality target.');
 if($growth!==null&&$growth<0)$add($risks,'medium','MOMENTUM','Revenue momentum risk','Recorded collections declined month over month.');
 if($covered>0&&($over/$covered*100)>(float)($targets['max_overhead_ratio']??35))$add($risks,'medium','OVERHEAD','Overhead pressure','Entered overhead exceeds the configured share of cost-covered collections.');
 $client_share=(float)($business['top_client_share']??($business['client_concentration']??0));if($client_share>40)$add($risks,'high','CONCENTRATION','Client concentration exposure','The leading client represents more than 40% of the available client revenue measure.');
 if($goal>0&&$weighted>=$goal)$add($opps,'medium','PIPELINE','Strong commercial coverage','Weighted pipeline alone meets or exceeds the configured monthly revenue objective.');
 if($margin!==null&&$margin>=(float)($targets['operating_margin']??20)+10)$add($opps,'medium','PRICING','Margin expansion capacity','Covered operating margin is at least ten points above the configured target.');
 if($growth!==null&&$growth>=(float)($targets['monthly_growth']??5))$add($opps,'medium','GROWTH','Positive collection momentum','Month-over-month collection growth meets or exceeds the configured target.');
 if($coverage>=90)$add($opps,'low','DATA','High cost-data visibility','Cost-basis coverage is at least 90%, improving confidence in profitability decisions.');
 if(!$risks)$add($risks,'low','HEALTH','No major strategic risk triggered','No configured V15.2 risk threshold is currently breached by the available Business OS data.');
 if(!$opps)$add($opps,'low','DISCOVERY','Opportunity discovery required','No major strategic opportunity threshold is currently triggered; continue building pipeline and complete business records.');
 usort($risks,function($a,$b){return $b['rank']<=>$a['rank'];});usort($opps,function($a,$b){return $b['rank']<=>$a['rank'];});return array('risks'=>$risks,'opportunities'=>$opps);
}
function tuff_beatz_v152_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$x=tuff_beatz_v152_intelligence();ob_start();?><section class="tb-v152-ro"><div class="tb-v152-head"><div><small>STRATEGIC RISK + OPPORTUNITY • V15.2</small><h3>Executive Exposure Map</h3><p>Separates strategic downside signals from upside opportunities using configured targets and recorded Business OS evidence.</p></div></div><div class="tb-v152-cols"><div><h4>RISK INTELLIGENCE</h4><?php foreach($x['risks'] as $r):?><article class="is-<?php echo esc_attr($r['severity']);?>"><small><?php echo esc_html(strtoupper($r['severity']).' • '.$r['domain']);?></small><strong><?php echo esc_html($r['title']);?></strong><p><?php echo esc_html($r['evidence']);?></p></article><?php endforeach;?></div><div><h4>OPPORTUNITY INTELLIGENCE</h4><?php foreach($x['opportunities'] as $r):?><article><small><?php echo esc_html(strtoupper($r['severity']).' • '.$r['domain']);?></small><strong><?php echo esc_html($r['title']);?></strong><p><?php echo esc_html($r['evidence']);?></p></article><?php endforeach;?></div></div><p class="tb-v152-foot">Signals are deterministic management indicators, not guarantees, valuations or autonomous decisions. Missing or incomplete records can materially affect the analysis.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var a=document.querySelector('.tb-v151-strategy');if(!a||document.querySelector('.tb-v152-ro'))return;var b=document.createElement('div');b.innerHTML=<?php echo wp_json_encode($html);?>;a.insertAdjacentElement('afterend',b.firstElementChild);var e=document.querySelector('.tb-biz-hero .eyebrow');if(e)e.textContent='TUFF BEATZ • STRATEGIC INTELLIGENCE V15.2';});</script><?php }
add_action('wp_footer','tuff_beatz_v152_panel',18);
function tuff_beatz_v152_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v152-ro{margin-top:18px;padding:22px;border:1px solid rgba(216,180,90,.16);border-radius:18px;background:#090909}.tb-v152-head small{color:#9e8245;font-size:.52rem;letter-spacing:.14em}.tb-v152-head h3{margin:4px 0;color:#dfd5c1;font-family:Cinzel,serif}.tb-v152-head p,.tb-v152-foot{color:#736b60;font-size:.55rem;line-height:1.5}.tb-v152-cols{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:15px}.tb-v152-cols>div{padding:13px;border:1px solid rgba(255,255,255,.05);border-radius:13px}.tb-v152-cols h4{margin:0 0 9px;color:#9f864d;font-size:.58rem;letter-spacing:.1em}.tb-v152-cols article{padding:11px;margin-top:7px;border:1px solid rgba(255,255,255,.05);border-radius:10px}.tb-v152-cols article.is-high,.tb-v152-cols article.is-critical{border-color:rgba(216,180,90,.22)}.tb-v152-cols small{display:block;color:#776b55;font-size:.44rem;letter-spacing:.08em}.tb-v152-cols strong{display:block;margin-top:4px;color:#d6ccba;font-size:.65rem}.tb-v152-cols p{margin:4px 0 0;color:#786f63;font-size:.52rem;line-height:1.45}.tb-v152-foot{margin:10px 0 0}@media(max-width:720px){.tb-v152-cols{grid-template-columns:1fr}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v152_css',114);
