<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS V15.3 — Strategic Planning Engine */
function tuff_beatz_v153_objectives(){
 $x=function_exists('tuff_beatz_v152_intelligence')?tuff_beatz_v152_intelligence():array('risks'=>array(),'opportunities'=>array());
 $targets=function_exists('tuff_beatz_v1416_targets')?tuff_beatz_v1416_targets():array();$items=array();
 $map=array('PIPELINE'=>array('Build forward revenue coverage','Pipeline coverage','pipeline_coverage','business-command'),'MARGIN'=>array('Protect operating contribution','Operating margin','operating_margin','business-command'),'DATA'=>array('Raise profitability data confidence','Cost data coverage','cost_coverage','business-command'),'MOMENTUM'=>array('Restore collection momentum','Monthly growth','monthly_growth','business-command'),'OVERHEAD'=>array('Control overhead exposure','Maximum overhead ratio','max_overhead_ratio','business-command'),'CONCENTRATION'=>array('Diversify client revenue exposure','Top-client concentration','', 'business-command'));
 foreach(($x['risks']??array()) as $r){$d=$r['domain']??'';if(!isset($map[$d])||$d==='HEALTH')continue;$m=$map[$d];$target=$m[2]!==''?($targets[$m[2]]??null):40;$items[]=array('priority'=>in_array($r['severity'],array('critical','high'),true)?'HIGH':'MEDIUM','type'=>'RISK RESPONSE','objective'=>$m[0],'metric'=>$m[1],'target'=>$target,'reason'=>$r['evidence'],'url'=>home_url('/'.$m[3].'/'));}
 foreach(($x['opportunities']??array()) as $r){$d=$r['domain']??'';if($d==='DISCOVERY')continue;$items[]=array('priority'=>'MEDIUM','type'=>'GROWTH','objective'=>'Capitalize on '.$r['title'],'metric'=>$d.' signal','target'=>null,'reason'=>$r['evidence'],'url'=>home_url('/business-command/'));}
 if(!$items)$items[]=array('priority'=>'LOW','type'=>'MAINTAIN','objective'=>'Maintain strategic operating discipline','metric'=>'Executive KPI health','target'=>null,'reason'=>'No major risk-response or growth objective is currently generated from available strategic signals.','url'=>home_url('/business-command/'));
 return $items;
}
function tuff_beatz_v153_panel(){if(!is_page('business-command')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$items=tuff_beatz_v153_objectives();ob_start();?><section class="tb-v153-plan"><div class="tb-v153-head"><div><small>STRATEGIC PLANNING • V15.3</small><h3>Objective Portfolio</h3><p>Transforms current strategic signals into measurable management objectives. Objectives are generated as planning guidance; execution remains under producer control.</p></div><strong><?php echo esc_html((string)count($items));?><span>OBJECTIVES</span></strong></div><div class="tb-v153-list"><?php foreach($items as $i):?><article><div><small><?php echo esc_html($i['priority'].' • '.$i['type']);?></small><h4><?php echo esc_html($i['objective']);?></h4><p><?php echo esc_html($i['reason']);?></p></div><div class="tb-v153-metric"><span><?php echo esc_html($i['metric']);?></span><b><?php echo $i['target']===null?'TRACK':esc_html(number_format((float)$i['target'],1).'%');?></b></div><a href="<?php echo esc_url($i['url']);?>">MANAGE →</a></article><?php endforeach;?></div><p class="tb-v153-foot">Generated objectives are deterministic planning prompts based on available records and configured KPI targets. They are not autonomous instructions, guarantees or formal financial plans.</p></section><?php $html=ob_get_clean();?><script>document.addEventListener('DOMContentLoaded',function(){var a=document.querySelector('.tb-v152-ro');if(!a||document.querySelector('.tb-v153-plan'))return;var b=document.createElement('div');b.innerHTML=<?php echo wp_json_encode($html);?>;a.insertAdjacentElement('afterend',b.firstElementChild);var e=document.querySelector('.tb-biz-hero .eyebrow');if(e)e.textContent='TUFF BEATZ • STRATEGIC PLANNING V15.3';});</script><?php }
add_action('wp_footer','tuff_beatz_v153_panel',19);
function tuff_beatz_v153_css(){if(!is_page('business-command'))return;wp_add_inline_style('tuff-beatz-business-command','.tb-v153-plan{margin-top:18px;padding:22px;border:1px solid rgba(216,180,90,.17);border-radius:18px;background:#090909}.tb-v153-head{display:flex;justify-content:space-between;gap:20px;align-items:center}.tb-v153-head small{color:#9f8348;font-size:.52rem;letter-spacing:.14em}.tb-v153-head h3{margin:4px 0;color:#e0d5c1;font-family:Cinzel,serif}.tb-v153-head p,.tb-v153-foot{color:#736b60;font-size:.55rem;line-height:1.5}.tb-v153-head>strong{color:#dec265;font:1.7rem Cinzel,serif;text-align:center}.tb-v153-head>strong span{display:block;color:#6f654f;font:400 .45rem Inter,sans-serif}.tb-v153-list{display:grid;gap:8px;margin-top:14px}.tb-v153-list article{display:grid;grid-template-columns:1fr 130px auto;gap:14px;align-items:center;padding:13px;border:1px solid rgba(255,255,255,.05);border-radius:11px}.tb-v153-list small{color:#8f7747;font-size:.45rem;letter-spacing:.08em}.tb-v153-list h4{margin:4px 0;color:#d8cebb;font-size:.68rem}.tb-v153-list p{margin:0;color:#776f64;font-size:.52rem;line-height:1.45}.tb-v153-metric span,.tb-v153-metric b{display:block}.tb-v153-metric span{color:#716858;font-size:.46rem}.tb-v153-metric b{margin-top:3px;color:#c6aa5c;font-size:.62rem}.tb-v153-list a{color:#c6a958;text-decoration:none;font-size:.5rem;white-space:nowrap}.tb-v153-foot{margin:10px 0 0}@media(max-width:720px){.tb-v153-head{align-items:flex-start;flex-direction:column}.tb-v153-list article{grid-template-columns:1fr}}');}
add_action('wp_enqueue_scripts','tuff_beatz_v153_css',115);
