<?php
if(!defined('ABSPATH'))exit;
/** TUFF BEATZ Studio OS Workflow Automation V11.1 */
function tuff_beatz_workflow_order(){return array('new','reviewing','approved','in-progress','revision','mastering','delivery','completed');}
function tuff_beatz_workflow_next_status($status){$order=tuff_beatz_workflow_order();$i=array_search($status,$order,true);return ($i!==false&&isset($order[$i+1]))?$order[$i+1]:'';}
function tuff_beatz_workflow_milestone_map(){return array(
 'reviewing'=>array('Stems / Source Files Due'),
 'approved'=>array('Deposit Paid','Stems / Source Files Due'),
 'in-progress'=>array('Deposit Paid','Stems / Source Files Due','Production'),
 'revision'=>array('Deposit Paid','Stems / Source Files Due','Production','Mix V1','Client Review'),
 'mastering'=>array('Deposit Paid','Stems / Source Files Due','Production','Mix V1','Client Review','Mix Approval'),
 'delivery'=>array('Deposit Paid','Stems / Source Files Due','Production','Mix V1','Client Review','Mix Approval','Mastering'),
 'completed'=>array('Deposit Paid','Stems / Source Files Due','Production','Mix V1','Client Review','Mix Approval','Mastering','Final Delivery')
 );}
function tuff_beatz_workflow_sync_milestones($id,$status){if(!function_exists('tuff_beatz_ensure_milestones'))return;$map=tuff_beatz_workflow_milestone_map();if(empty($map[$status]))return;$targets=$map[$status];$m=tuff_beatz_ensure_milestones($id);$changed=false;foreach($m as &$x){if(in_array($x['title']??'',$targets,true)&&($x['status']??'')!=='completed'){$x['status']='completed';$changed=true;}}unset($x);if($changed){update_post_meta($id,'_tb_milestones_v8',$m);if(function_exists('tuff_beatz_add_activity'))tuff_beatz_add_activity($id,'automation','Studio OS synchronized milestones with '.ucwords(str_replace('-',' ',$status)));}}
function tuff_beatz_workflow_complete_milestone($id,$title,$source='Automation') {if(!function_exists('tuff_beatz_ensure_milestones'))return false;$m=tuff_beatz_ensure_milestones($id);$changed=false;foreach($m as &$x){if(($x['title']??'')===$title&&($x['status']??'')!=='completed'){$x['status']='completed';$changed=true;break;}}unset($x);if($changed){update_post_meta($id,'_tb_milestones_v8',$m);if(function_exists('tuff_beatz_add_activity'))tuff_beatz_add_activity($id,'automation',$source.' completed milestone: '.$title);}return $changed;}
function tuff_beatz_workflow_apply_status($id,$status,$source='producer'){$id=(int)$id;$allowed=array_merge(tuff_beatz_workflow_order(),array('declined'));if(!$id||get_post_type($id)!=='tb_request'||!in_array($status,$allowed,true))return false;$old=get_post_meta($id,'_tb_request_status',true)?:'new';if($old===$status)return true;update_post_meta($id,'_tb_request_status',$status);tuff_beatz_workflow_sync_milestones($id,$status);if(function_exists('tuff_beatz_add_activity'))tuff_beatz_add_activity($id,'workflow','Workflow: '.ucwords(str_replace('-',' ',$old)).' → '.ucwords(str_replace('-',' ',$status)).' via '.$source);return true;}
function tuff_beatz_workflow_safe_advance($id,$target,$source){$current=get_post_meta($id,'_tb_request_status',true)?:'new';$order=tuff_beatz_workflow_order();$ci=array_search($current,$order,true);$ti=array_search($target,$order,true);if($ci===false||$ti===false||$ti!==$ci+1)return false;return tuff_beatz_workflow_apply_status($id,$target,$source);}
function tuff_beatz_workflow_transition_action(){$id=(int)($_POST['request_id']??0);$status=sanitize_key(wp_unslash($_POST['status']??''));$return=sanitize_text_field(wp_unslash($_POST['return']??'producer'));$fallback=$return==='workspace'&&function_exists('tuff_beatz_project_dashboard_url')?tuff_beatz_project_dashboard_url($id):home_url('/producer-portal/');if(!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user()||!current_user_can('edit_post',$id)){wp_safe_redirect($fallback);exit;}if(!isset($_POST['tb_workflow_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_workflow_nonce'])),'tb_workflow_'.$id.'_'.$status)){wp_safe_redirect($fallback);exit;}tuff_beatz_workflow_apply_status($id,$status,'Producer Command Center');wp_safe_redirect(add_query_arg('workflow_updated','1',$fallback));exit;}
add_action('admin_post_tb_workflow_transition','tuff_beatz_workflow_transition_action');
function tuff_beatz_workflow_button($id,$status,$label,$return='producer',$class=''){ob_start();?><form class="tb-workflow-action <?php echo esc_attr($class);?>" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="tb_workflow_transition"><input type="hidden" name="request_id" value="<?php echo esc_attr($id);?>"><input type="hidden" name="status" value="<?php echo esc_attr($status);?>"><input type="hidden" name="return" value="<?php echo esc_attr($return);?>"><?php wp_nonce_field('tb_workflow_'.$id.'_'.$status,'tb_workflow_nonce');?><button type="submit"><?php echo esc_html($label);?></button></form><?php return ob_get_clean();}
function tuff_beatz_workflow_automation_hooks($meta_id,$object_id,$meta_key,$meta_value){if(get_post_type($object_id)!=='tb_request')return;if($meta_key==='_tb_approved_mix_file'&&$meta_value){tuff_beatz_workflow_complete_milestone($object_id,'Mix Approval','Client mix approval');$current=get_post_meta($object_id,'_tb_request_status',true)?:'new';if($current==='revision')tuff_beatz_workflow_safe_advance($object_id,'mastering','Client Mix Approval');}if($meta_key==='_tb_request_status')tuff_beatz_workflow_sync_milestones($object_id,(string)$meta_value);}
add_action('added_post_meta','tuff_beatz_workflow_automation_hooks',40,4);add_action('updated_post_meta','tuff_beatz_workflow_automation_hooks',40,4);
function tuff_beatz_workflow_vault_events($request_id,$added,$category='source',$version=''){if(!$request_id||!is_array($added)||!$added)return;$category=sanitize_key($category);$version=sanitize_text_field($version);if($category==='source'){tuff_beatz_workflow_complete_milestone($request_id,'Stems / Source Files Due','Private Vault');$current=get_post_meta($request_id,'_tb_request_status',true)?:'new';if($current==='new')tuff_beatz_workflow_safe_advance($request_id,'reviewing','Source Files Received');}
if($category==='delivery'){$reviewable=false;foreach($added as $f){$ext=strtolower(pathinfo($f['name']??'',PATHINFO_EXTENSION));if(in_array($ext,array('wav','aiff','aif','mp3','m4a'),true)){$reviewable=true;break;}}$label=strtolower($version.' '.implode(' ',array_map(function($f){return $f['name']??'';},$added)));if($reviewable&&preg_match('/mix|review|v[0-9]/',$label)){tuff_beatz_workflow_complete_milestone($request_id,'Mix V1','Review Mix Upload');$current=get_post_meta($request_id,'_tb_request_status',true)?:'new';if($current==='in-progress')tuff_beatz_workflow_safe_advance($request_id,'revision','Review Mix Ready');}if(preg_match('/master|final|delivery/',$label)){tuff_beatz_workflow_complete_milestone($request_id,'Mastering','Master Delivery Upload');$current=get_post_meta($request_id,'_tb_request_status',true)?:'new';if($current==='mastering')tuff_beatz_workflow_safe_advance($request_id,'delivery','Final Master Uploaded');}}
}
add_action('tuff_beatz_vault_files_added','tuff_beatz_workflow_vault_events',20,4);
function tuff_beatz_workflow_assets(){if(is_page('producer-portal')){$p=get_template_directory().'/assets/css/workflow-automation.css';if(file_exists($p))wp_enqueue_style('tuff-beatz-workflow-automation',get_template_directory_uri().'/assets/css/workflow-automation.css',array('tuff-beatz-producer-command-v2'),filemtime($p));}}
add_action('wp_enqueue_scripts','tuff_beatz_workflow_assets',90);
function tuff_beatz_render_producer_workflow_controls(){if(!is_page('producer-portal')||!is_user_logged_in()||!function_exists('tuff_beatz_is_producer_user')||!tuff_beatz_is_producer_user())return;$q=new WP_Query(array('post_type'=>'tb_request','post_status'=>'publish','posts_per_page'=>100,'fields'=>'ids'));$items=array();foreach($q->posts as $id){$s=get_post_meta($id,'_tb_request_status',true)?:'new';$next=tuff_beatz_workflow_next_status($s);$items[(string)$id]=array('status'=>$s,'next'=>$next,'nextLabel'=>$next?ucwords(str_replace('-',' ',$next)):'','html'=>$next?tuff_beatz_workflow_button($id,$next,'Advance → '.$next,'producer','is-primary'):'');}wp_reset_postdata();?><script>document.addEventListener('DOMContentLoaded',function(){var map=<?php echo wp_json_encode($items);?>;document.querySelectorAll('.tb-producer-row').forEach(function(row){var link=row.querySelector('a[href*="project-dashboard"][href*="project="]');if(!link)return;var m=link.href.match(/[?&]project=(\d+)/);if(!m||!map[m[1]])return;var d=map[m[1]],actions=row.querySelector('.tb-producer-actions')||row;var bar=document.createElement('div');bar.className='tb-workflow-bar';bar.innerHTML='<span class="tb-workflow-label">AUTOMATION</span><span class="tb-workflow-chip"><i></i>'+d.status.replace(/-/g,' ')+'</span>'+d.html;actions.insertAdjacentElement('afterend',bar);});<?php if(isset($_GET['workflow_updated'])):?>var c=document.querySelector('.tb-command-project-tools');if(c){var n=document.createElement('div');n.className='tb-workflow-toast';n.textContent='Studio OS updated the project stage, timeline and client notifications.';c.parentNode.insertBefore(n,c);}<?php endif;?>});</script><?php }
add_action('wp_footer','tuff_beatz_render_producer_workflow_controls',15);
