<?php /** Template Name: Start a Project */ if(!defined('ABSPATH'))exit;get_header();
$error=sanitize_key(wp_unslash($_GET['portal_error']??''));$messages=array('security'=>'Your session could not be verified. Please try again.','registration_fields'=>'Enter your name, a valid email, and a password with at least 10 characters.','email_exists'=>'An account already exists with that email. Please log in instead.','registration_failed'=>'We could not create your account. Please try again.','required_fields'=>'Please complete the required project fields.','submit_failed'=>'Your project request could not be submitted. Please try again.','consent'=>'Please confirm you have permission to share the submitted files.');$industries=tuff_beatz_industry_types();$services=tuff_beatz_services(); ?>
<main class="tb-portal" id="main">
<section class="tb-portal-hero"><div class="container tb-portal-hero__inner"><p class="eyebrow">TUFF BEATZ PRODUCTION PORTAL</p><h1>BUILD YOUR <span>PROJECT</span></h1><p>A professional production intake for artists, groups, bands, songwriters, producers, musicians, labels and the wider music industry — from the first idea through mixing, mastering and delivery.</p><div class="tb-portal-trust"><span>INDUSTRY-WIDE SERVICES</span><span>MULTI-FILE UPLOAD</span><span>MIXING + MASTERING READY</span><span>DIRECT PROJECT REVIEW</span></div></div></section>
<section class="tb-portal-body section"><div class="container">
<?php if($error&&isset($messages[$error])):?><div class="tb-portal-alert tb-portal-alert--error"><?php echo esc_html($messages[$error]);?></div><?php endif;if(isset($_GET['welcome'])):?><div class="tb-portal-alert">Your account is ready. Build and submit your project below.</div><?php endif;if(isset($_GET['submitted'])):?><div class="tb-portal-alert">Project received. Your files and production brief have been added to the TUFF BEATZ review queue.</div><?php endif;?>
<?php if(!is_user_logged_in()): ?>
<div class="tb-auth-grid"><article class="tb-portal-card tb-login-card"><p class="tb-card-kicker">RETURNING INDUSTRY CLIENT</p><h2>Enter the portal</h2><p>Access your project intake and recent requests.</p><?php wp_login_form(array('redirect'=>home_url('/start-a-project/'),'remember'=>true,'label_username'=>'Email or Username','label_password'=>'Password','label_remember'=>'Keep me signed in','label_log_in'=>'Enter Production Portal'));?><a class="tb-small-link" href="<?php echo esc_url(wp_lostpassword_url(home_url('/start-a-project/')));?>">Forgot your password?</a></article>
<article class="tb-portal-card tb-register-card"><p class="tb-card-kicker">CREATE YOUR INDUSTRY ACCOUNT</p><h2>Who are you?</h2><p>Choose the role that best describes how you work in the music industry.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="tb-portal-form"><input type="hidden" name="action" value="tb_register_portal_account"><?php wp_nonce_field('tb_register_account','tb_register_nonce');?><input class="tb-honeypot" type="text" name="company_website" tabindex="-1" autocomplete="off" aria-hidden="true"><div class="tb-field"><label>Full / Professional Name *</label><input name="display_name" type="text" required autocomplete="name"></div><div class="tb-field"><label>Email *</label><input name="email" type="email" required autocomplete="email"></div><div class="tb-field"><label>Password *</label><input name="password" type="password" minlength="10" required autocomplete="new-password"><small>Minimum 10 characters.</small></div><div class="tb-field"><label>I am a / representing</label><select name="industry_type"><?php foreach($industries as $v=>$l):?><option value="<?php echo esc_attr($v);?>"><?php echo esc_html($l);?></option><?php endforeach;?></select></div><button class="btn btn-gold tb-submit" type="submit">Create Account & Continue</button></form></article></div>
<div class="tb-locked-preview"><div class="tb-lock-mark">♪</div><div><strong>One portal. The entire production ecosystem.</strong><span>Create an account to submit production, mixing, mastering, songwriting, band, collaboration and media projects.</span></div></div>
<?php else:$user=wp_get_current_user();$requests=new WP_Query(array('post_type'=>'tb_request','post_status'=>'publish','author'=>$user->ID,'posts_per_page'=>8,'orderby'=>'date','order'=>'DESC'));$industry=get_user_meta($user->ID,'_tb_industry_type',true)?:'artist'; ?>
<div class="tb-portal-userbar"><div><span>SIGNED IN</span><strong><?php echo esc_html($user->display_name);?></strong><small><?php echo esc_html(($industries[$industry]??'Industry Client').' • '.$user->user_email);?></small></div><a class="btn btn-outline" href="<?php echo esc_url(wp_logout_url(home_url('/start-a-project/')));?>">Log Out</a></div>
<div class="tb-project-grid"><article class="tb-portal-card tb-project-form-card"><p class="tb-card-kicker">PRODUCTION INTAKE</p><h2>How can TUFF BEATZ help?</h2><p>Select your role and service, describe the record, then upload the material needed for production review.</p>
<form method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="tb-portal-form tb-project-form"><input type="hidden" name="action" value="tb_submit_project_request"><?php wp_nonce_field('tb_submit_project','tb_project_nonce');?>
<div class="tb-intake-step"><b>01</b><span>WHO ARE YOU?</span></div><div class="tb-form-row"><div class="tb-field"><label>Artist / Client / Organization *</label><input name="artist_name" type="text" value="<?php echo esc_attr($user->display_name);?>" required></div><div class="tb-field"><label>Industry Role *</label><select name="industry_type" required><?php foreach($industries as $v=>$l):?><option value="<?php echo esc_attr($v);?>" <?php selected($industry,$v);?>><?php echo esc_html($l);?></option><?php endforeach;?></select></div></div>
<div class="tb-intake-step"><b>02</b><span>WHAT DO YOU NEED?</span></div><div class="tb-form-row"><div class="tb-field"><label>Service *</label><select name="service" required><option value="">Select a service</option><?php foreach($services as $v=>$l):?><option value="<?php echo esc_attr($v);?>"><?php echo esc_html($l);?></option><?php endforeach;?></select></div><div class="tb-field"><label>Project / Song Title *</label><input name="project_title" type="text" required></div></div>
<div class="tb-form-row"><div class="tb-field"><label>Project Type</label><select name="project_type"><option>Single / Song</option><option>EP</option><option>Album</option><option>Band Project</option><option>Film / TV / Media</option><option>Live Performance</option><option>Other</option></select></div><div class="tb-field"><label>Genre / Style</label><input name="genre" type="text" placeholder="Kompa, Afrobeats, R&B, Gospel..."></div></div>
<div class="tb-intake-step"><b>03</b><span>BUILD THE PROJECT</span></div><div class="tb-form-row tb-form-row--3"><div class="tb-field"><label>BPM</label><input name="bpm" type="text" inputmode="numeric" placeholder="104"></div><div class="tb-field"><label>Key</label><input name="song_key" type="text" placeholder="F# Minor"></div><div class="tb-field"><label>Track / Stem Count</label><input name="track_count" type="text" inputmode="numeric" placeholder="48"></div></div>
<div class="tb-form-row"><div class="tb-field"><label>Estimated Budget</label><select name="budget"><option value="">Select range</option><option>Under $1,000</option><option>$1,000–$2,999</option><option>$3,000–$5,999</option><option>$6,000–$9,999</option><option>$10,000+</option><option>Need a quote</option></select></div><div class="tb-field"><label>Target Release / Deadline</label><input name="target_date" type="date"></div></div>
<div class="tb-field"><label>Reference / Demo Link</label><input name="reference_url" type="url" placeholder="Spotify, YouTube, SoundCloud, Drive..."></div><div class="tb-field"><label>Creative Direction & Project Details *</label><textarea name="details" rows="7" required placeholder="Describe the sound, current stage, deliverables, collaborators, references and what you need TUFF BEATZ to handle."></textarea></div>
<div class="tb-mix-panel"><div><p class="tb-card-kicker">MIXING / MASTERING DETAILS</p><h3>Sending a record to mix or master?</h3><p>Include your rough mix/reference plus notes about vocals, dynamics, effects, tone and delivery requirements.</p></div><div class="tb-field"><label>Mix / Master Notes</label><textarea name="mix_notes" rows="5" placeholder="Example: lead vocal forward, warm low end, wider backgrounds, preserve dynamics, streaming master + instrumental..."></textarea></div></div>
<div class="tb-intake-step"><b>04</b><span>UPLOAD YOUR FILES</span></div><div class="tb-upload-zone"><strong>Drop in your production material</strong><p>Upload stems, vocals, rough mixes, stereo mixes, references, MIDI, briefs or ZIP packages.</p><input name="project_files[]" type="file" multiple accept=".wav,.aiff,.aif,.mp3,.m4a,.zip,.pdf,.txt,.mid,.midi,audio/*,application/zip,application/pdf"><small>Up to 12 files per submission. WAV • AIFF • MP3 • M4A • ZIP • MIDI • PDF • TXT. Your server's upload-size limit still applies.</small></div>
<div class="tb-field"><label>Large Session / Transfer Link</label><input name="transfer_url" type="url" placeholder="Google Drive, Dropbox, WeTransfer or another secure transfer link"><small>Recommended when your multitrack session is larger than the website upload limit.</small></div>
<label class="tb-consent"><input type="checkbox" name="rights_confirm" value="1" required><span>I confirm that I own, control, or have permission to share these files with TUFF BEATZ for project evaluation and production work.</span></label><button class="btn btn-gold tb-submit" type="submit">Submit Project + Files</button></form></article>
<aside class="tb-portal-side"><article class="tb-portal-card tb-process-card"><p class="tb-card-kicker">PRODUCTION WORKFLOW</p><ol><li><span>01</span><div><strong>Files Received</strong><small>Your brief and material enter the project queue.</small></div></li><li><span>02</span><div><strong>Review & Scope</strong><small>Service, files, sound, budget and deadline are reviewed.</small></div></li><li><span>03</span><div><strong>Production</strong><small>Approved work moves into production, mixing or mastering.</small></div></li><li><span>04</span><div><strong>Revisions</strong><small>Version feedback and adjustments are handled before approval.</small></div></li><li><span>05</span><div><strong>Final Delivery</strong><small>Approved masters and deliverables are prepared for release.</small></div></li></ol></article>
<article class="tb-portal-card tb-history-card"><p class="tb-card-kicker">YOUR PROJECTS</p><h3>Recent requests</h3><?php if($requests->have_posts()):?><div class="tb-request-list"><?php while($requests->have_posts()):$requests->the_post();$status=get_post_meta(get_the_ID(),'_tb_request_status',true)?:'new';?><div class="tb-request-item"><div><strong><?php the_title();?></strong><small><?php echo esc_html(get_the_date('M j, Y'));?></small></div><span class="tb-status tb-status--<?php echo esc_attr($status);?>"><?php echo esc_html(tuff_beatz_request_status_label($status));?></span></div><?php endwhile;wp_reset_postdata();?></div><?php else:?><p class="tb-empty-state">No projects yet. Your submissions will appear here.</p><?php endif;?></article></aside></div><?php endif;?></div></section></main><?php get_footer(); ?>