<?php /** Template Name: TUFF BEATZ Proposal */ if(!defined('ABSPATH'))exit;
if(!defined('DONOTCACHEPAGE'))define('DONOTCACHEPAGE',true);if(!defined('DONOTCACHEDB'))define('DONOTCACHEDB',true);if(!defined('DONOTCACHEOBJECT'))define('DONOTCACHEOBJECT',true);if(function_exists('nocache_headers'))nocache_headers();if(!headers_sent()){header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('Pragma: no-cache');header('Expires: Wed, 11 Jan 1984 05:00:00 GMT');}
$id=(int)($_GET['opportunity']??$_POST['opportunity_id']??0);
$token=sanitize_text_field(wp_unslash($_GET['proposal_token']??$_POST['proposal_token']??''));
if(!$id||!function_exists('tuff_beatz_v14_proposal_access')||!tuff_beatz_v14_proposal_access($id,$token)){status_header(403);wp_die('This proposal link is invalid or unavailable.');}
$o=tuff_beatz_v14_opportunity_data($id);$p=tuff_beatz_v14_proposal_data($id);$a=tuff_beatz_v14_proposal_acceptance($id);$t=tuff_beatz_v14_proposal_totals($p);$expired=!empty($p['expires'])&&strtotime($p['expires'].' 23:59:59')<current_time('timestamp');
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['tb_proposal_page_decision'])){
    if(!isset($_POST['tb_v14_proposal_decision_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['tb_v14_proposal_decision_nonce'])),'tb_v14_proposal_decision_'.$id))wp_die('Proposal verification failed.',403);
    $posted_version=sanitize_text_field(wp_unslash($_POST['proposal_version']??''));
    if(!$p||!$posted_version||!hash_equals((string)($p['version']??''),$posted_version))wp_die('Proposal revision changed. Reload the proposal and try again.',409);
    if($expired){wp_safe_redirect(add_query_arg(array('opportunity'=>$id,'proposal_token'=>$token,'proposal_state'=>'expired','tbv'=>'345'),home_url('/proposal/')));exit;}
    $decision=sanitize_key($_POST['decision']??'');if(!in_array($decision,array('accepted','declined'),true))wp_die('Invalid proposal decision.',400);
    $record=array('decision'=>$decision,'proposal_version'=>$p['version']??'','proposal_revision'=>(int)($p['revision']??1),'name'=>sanitize_text_field(wp_unslash($_POST['client_name']??'')),'email'=>sanitize_email(wp_unslash($_POST['client_email']??'')),'decided_at'=>current_time('mysql'),'ip_hash'=>hash('sha256',($_SERVER['REMOTE_ADDR']??'').'|'.wp_salt('auth')));
    update_post_meta($id,'_tb_v14_proposal_acceptance',$record);$p['status']=$decision;update_post_meta($id,'_tb_v14_proposal',$p);
    if($decision==='accepted'){update_post_meta($id,'_tb_v14_stage','contract');update_post_meta($id,'_tb_v14_probability',75);if(function_exists('tuff_beatz_v14_add_opportunity_activity'))tuff_beatz_v14_add_opportunity_activity($id,'proposal','Proposal accepted by '.$record['name']);}
    else{if(function_exists('tuff_beatz_v14_add_opportunity_activity'))tuff_beatz_v14_add_opportunity_activity($id,'proposal','Proposal declined by '.$record['name']);}
    wp_mail(get_option('admin_email'),'TUFF BEATZ — Proposal '.ucfirst($decision),get_the_title($id).' — '.$record['name'].' <'.$record['email'].'>');
    wp_safe_redirect(add_query_arg(array('opportunity'=>$id,'proposal_token'=>$token,'proposal_state'=>$decision,'tbv'=>'345'),home_url('/proposal/')));exit;
}
$decision_token=function_exists('tuff_beatz_v14_proposal_token')?tuff_beatz_v14_proposal_token($id):$token;get_header();?>
<main class="tb-proposal-page"><section class="tb-proposal-shell"><div class="tb-proposal-brand"><span>TUFF BEATZ</span><small>SOUND. PURPOSE. LEGACY.</small></div><div class="tb-proposal-hero"><p>PRIVATE CLIENT PROPOSAL • <?php echo esc_html($p['number']??'TUFF BEATZ');?></p><h1><?php echo esc_html($o['title']);?></h1><div><span>Prepared for <?php echo esc_html($o['contact_name']?:'Client');?></span><span>Revision <?php echo esc_html((int)($p['revision']??1));?></span><?php if(!empty($p['expires'])):?><span>Valid through <?php echo esc_html(wp_date('M j, Y',strtotime($p['expires'])));?></span><?php endif;?></div></div>
<?php if(!$p):?><div class="tb-proposal-card"><h2>Proposal not ready</h2><p>This proposal is still being prepared.</p></div><?php else:?><div class="tb-proposal-grid"><article class="tb-proposal-card"><p class="tb-proposal-kicker">VISION & OBJECTIVE</p><h2>Executive Summary</h2><p><?php echo nl2br(esc_html($p['summary']??''));?></p></article><article class="tb-proposal-card"><p class="tb-proposal-kicker">PROJECT SCOPE</p><h2>Scope & Deliverables</h2><p><?php echo nl2br(esc_html($p['scope']??''));?></p></article></div><section class="tb-proposal-investment"><div><p class="tb-proposal-kicker">INVESTMENT</p><h2>Project Investment</h2></div><div class="tb-proposal-numbers"><div><small>SUBTOTAL</small><strong><?php echo esc_html(tuff_beatz_money($t['subtotal']));?></strong></div><?php if($t['discount']>0):?><div><small>DISCOUNT</small><strong>-<?php echo esc_html(tuff_beatz_money($t['discount']));?></strong></div><?php endif;?><div><small>TAX / FEES</small><strong><?php echo esc_html(tuff_beatz_money($t['tax']));?></strong></div><div class="is-total"><small>TOTAL</small><strong><?php echo esc_html(tuff_beatz_money($t['total']));?></strong></div><div><small>DEPOSIT</small><strong><?php echo esc_html(tuff_beatz_money($t['deposit']));?></strong><span><?php echo esc_html($t['deposit_pct']);?>%</span></div></div></section>
<?php $state=sanitize_key($_GET['proposal_state']??($a['decision']??''));if($state==='accepted'):?><div class="tb-proposal-decision is-accepted"><strong>✓ PROPOSAL ACCEPTED</strong><p>Thank you. TUFF BEATZ has recorded your approval and the opportunity is ready for the contract stage.</p></div><?php elseif($state==='declined'):?><div class="tb-proposal-decision"><strong>PROPOSAL DECLINED</strong><p>Your decision has been recorded. TUFF BEATZ can prepare a revised proposal if needed.</p></div><?php elseif($expired):?><div class="tb-proposal-decision"><strong>PROPOSAL EXPIRED</strong><p>Please contact TUFF BEATZ for an updated proposal.</p></div><?php elseif(!$a):?><form class="tb-proposal-accept" method="post" action=""><input type="hidden" name="tb_proposal_page_decision" value="1"><input type="hidden" name="opportunity_id" value="<?php echo esc_attr($id);?>"><input type="hidden" name="proposal_token" value="<?php echo esc_attr($decision_token);?>"><input type="hidden" name="proposal_version" value="<?php echo esc_attr($p['version']??'');?>"><?php wp_nonce_field('tb_v14_proposal_decision_'.$id,'tb_v14_proposal_decision_nonce');?><div><p class="tb-proposal-kicker">CLIENT DECISION</p><h2>Approve this proposal</h2><p>Approval records this exact proposal revision, pricing and scope. Contract terms are handled separately in the next stage.</p><small style="opacity:.55">Approval Engine 14.4.2</small></div><div class="tb-proposal-fields"><input required name="client_name" placeholder="Full name" value="<?php echo esc_attr($o['contact_name']);?>"><input required type="email" name="client_email" placeholder="Email" value="<?php echo esc_attr($o['contact_email']);?>"><div class="tb-proposal-actions"><button name="decision" value="accepted" type="submit">Approve Proposal</button><button class="is-decline" name="decision" value="declined" type="submit">Decline</button></div></div></form><?php endif;?><?php endif;?></section></main><?php get_footer();?>