<?php /** Template Name: Project Dashboard */ if(!defined('ABSPATH'))exit;get_header();
if(!is_user_logged_in()){wp_safe_redirect(wp_login_url(home_url('/project-dashboard/')));exit;}
$request_id=(int)($_GET['project']??0);if(!$request_id||!tuff_beatz_user_can_view_request($request_id)){wp_safe_redirect(home_url('/start-a-project/'));exit;}
$post=get_post($request_id);$services=tuff_beatz_services();$industries=tuff_beatz_industry_types();$status=get_post_meta($request_id,'_tb_request_status',true)?:'new';$service=get_post_meta($request_id,'_tb_request_service',true);$industry=get_post_meta($request_id,'_tb_request_industry_type',true);$vault=tuff_beatz_vault_files($request_id);$source_files=array_values(array_filter($vault,function($f){return ($f['category']??'source')!=='delivery';}));$delivery_files=array_values(array_filter($vault,function($f){return ($f['category']??'')==='delivery';}));$legacy=get_post_meta($request_id,'_tb_request_attachments',true);if(!is_array($legacy))$legacy=array();$messages=tuff_beatz_dashboard_messages($request_id);$credits=get_post_meta($request_id,'_tb_request_credits',true);$payment=get_post_meta($request_id,'_tb_request_payment_status',true)?:'Not invoiced';$delivery=get_post_meta($request_id,'_tb_request_delivery_notes',true);$final=get_post_meta($request_id,'_tb_request_final_links',true);$final_links=array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',$final?:''))); ?>
<main class="tb-portal tb-dashboard" id="main">
<section class="tb-dashboard-hero"><div class="container"><a class="tb-back-link" href="<?php echo esc_url(home_url('/start-a-project/'));?>">← Back to Production Portal</a><div class="tb-dashboard-title"><div><p class="eyebrow">TUFF BEATZ PROJECT WORKSPACE</p><h1><?php echo esc_html($post->post_title);?></h1><p><?php echo esc_html($services[$service]??$service);?> • <?php echo esc_html($industries[$industry]??'Industry Client');?></p></div><span class="tb-status tb-status--<?php echo esc_attr($status);?>"><?php echo esc_html(tuff_beatz_request_status_label($status));?></span></div>
<div class="tb-dashboard-progress"><span class="<?php echo in_array($status,array('new','reviewing','approved','in-progress','revision','mastering','delivery','completed'),true)?'active':'';?>">01 Intake</span><span class="<?php echo in_array($status,array('approved','in-progress','revision','mastering','delivery','completed'),true)?'active':'';?>">02 Approved</span><span class="<?php echo in_array($status,array('in-progress','revision','mastering','delivery','completed'),true)?'active':'';?>">03 Production</span><span class="<?php echo in_array($status,array('revision','mastering','delivery','completed'),true)?'active':'';?>">04 Revisions</span><span class="<?php echo in_array($status,array('mastering','delivery','completed'),true)?'active':'';?>">05 Mastering</span><span class="<?php echo in_array($status,array('delivery','completed'),true)?'active':'';?>">06 Delivery</span></div></div></section>
<section class="section tb-dashboard-body"><div class="container"><nav class="tb-dashboard-nav"><a href="#overview">Overview</a><a href="#files">Files</a><a href="#messages">Messages</a><a href="#credits">Credits</a><a href="#payments">Payments</a><a href="#delivery">Delivery</a></nav>
<?php if(isset($_GET['message_sent'])):?><div class="tb-portal-alert">Message sent to the project workspace.</div><?php endif;if(isset($_GET['files_added'])):?><div class="tb-portal-alert"><?php echo esc_html((int)$_GET['files_added']);?> secure file(s) added to this project.</div><?php endif;?>
<div class="tb-dashboard-layout"><div class="tb-dashboard-main">
<section id="overview" class="tb-portal-card tb-workspace-section"><p class="tb-card-kicker">OVERVIEW</p><h2>Project Brief</h2><div class="tb-meta-grid"><div><small>Service</small><strong><?php echo esc_html($services[$service]??$service);?></strong></div><div><small>Status</small><strong><?php echo esc_html(tuff_beatz_request_status_label($status));?></strong></div><div><small>Genre</small><strong><?php echo esc_html(get_post_meta($request_id,'_tb_request_genre',true)?:'—');?></strong></div><div><small>BPM / Key</small><strong><?php echo esc_html(trim((get_post_meta($request_id,'_tb_request_bpm',true)?:'—').' / '.(get_post_meta($request_id,'_tb_request_key',true)?:'—')));?></strong></div><div><small>Tracks / Stems</small><strong><?php echo esc_html(get_post_meta($request_id,'_tb_request_track_count',true)?:'—');?></strong></div><div><small>Target Date</small><strong><?php echo esc_html(get_post_meta($request_id,'_tb_request_target_date',true)?:'—');?></strong></div></div><div class="tb-project-copy"><h3>Creative Direction</h3><p><?php echo nl2br(esc_html(get_post_meta($request_id,'_tb_request_details',true)));?></p></div><?php $mix=get_post_meta($request_id,'_tb_request_mix_notes',true);if($mix):?><div class="tb-project-copy"><h3>Mix / Master Notes</h3><p><?php echo nl2br(esc_html($mix));?></p></div><?php endif;?></section>

<section id="files" class="tb-portal-card tb-workspace-section"><p class="tb-card-kicker">PRIVATE FILE VAULT</p><h2>Project Files</h2><p class="tb-vault-note">Secure project files are stored outside the public website and require an authorized TUFF BEATZ account to download.</p>
<?php if($source_files):?><div class="tb-file-list"><?php foreach($source_files as $file):?><a class="tb-file-row" href="<?php echo esc_url(tuff_beatz_vault_download_url($request_id,$file['id']));?>"><span>🔒</span><div><strong><?php echo esc_html($file['name']);?></strong><small><?php echo esc_html(($file['version']?:'Project File').' • '.tuff_beatz_vault_human_size($file['size']??0).' • Secure Download');?></small></div><b>↓</b></a><?php endforeach;?></div><?php else:?><p class="tb-empty-state">No private-vault source files are attached yet.</p><?php endif;?>
<?php if($legacy):?><div class="tb-legacy-files"><small>LEGACY FILES</small><p>Some earlier uploads may still use the original WordPress media storage. New uploads now enter the Private File Vault.</p></div><?php endif;?>
<?php $transfer=get_post_meta($request_id,'_tb_request_transfer_url',true);if($transfer):?><a class="btn btn-outline tb-transfer-btn" href="<?php echo esc_url($transfer);?>" target="_blank" rel="noopener">Open Large Session Transfer</a><?php endif;?>
<form method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="tb-dashboard-upload"><input type="hidden" name="action" value="tb_upload_project_dashboard_files"><input type="hidden" name="request_id" value="<?php echo esc_attr($request_id);?>"><?php wp_nonce_field('tb_project_files_'.$request_id,'tb_files_nonce');?><label>Add files to the Private Vault</label><input name="upload_version" type="text" placeholder="Version label: New Stems, Vocal Fixes, Revision Notes..."><input name="project_files[]" type="file" multiple accept=".wav,.aiff,.aif,.mp3,.m4a,.zip,.pdf,.txt,.mid,.midi"><button class="btn btn-gold" type="submit">Upload Securely</button></form></section>

<section id="messages" class="tb-portal-card tb-workspace-section"><p class="tb-card-kicker">MESSAGES</p><h2>Project Conversation</h2><div class="tb-message-list"><?php if($messages):foreach($messages as $m):?><article class="tb-message"><div><strong><?php echo esc_html($m['name']??'User');?></strong><span><?php echo esc_html($m['role']??'Client');?> • <?php echo esc_html(mysql2date('M j, Y g:i a',$m['time']??''));?></span></div><p><?php echo nl2br(esc_html($m['body']??''));?></p></article><?php endforeach;else:?><p class="tb-empty-state">No project messages yet. Use the form below to start the conversation.</p><?php endif;?></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="tb-message-form"><input type="hidden" name="action" value="tb_submit_project_message"><input type="hidden" name="request_id" value="<?php echo esc_attr($request_id);?>"><?php wp_nonce_field('tb_project_message_'.$request_id,'tb_message_nonce');?><textarea name="message" rows="4" required placeholder="Write a project message, revision note, question or update..."></textarea><button class="btn btn-gold" type="submit">Send Message</button></form></section>
<section id="credits" class="tb-portal-card tb-workspace-section"><p class="tb-card-kicker">CREDITS</p><h2>Personnel & Credits</h2><?php if($credits):?><p class="tb-preline"><?php echo nl2br(esc_html($credits));?></p><?php else:?><p class="tb-empty-state">Credits have not been finalized yet. Producers, writers, musicians, engineers and collaborators can be documented here as the project develops.</p><?php endif;?></section>
<section id="payments" class="tb-portal-card tb-workspace-section"><p class="tb-card-kicker">PAYMENTS</p><h2>Financial Status</h2><div class="tb-payment-card"><span>PROJECT PAYMENT STATUS</span><strong><?php echo esc_html($payment);?></strong><small>Quotes, deposits, balances and paid-in-full status are tracked here.</small></div></section>

<section id="delivery" class="tb-portal-card tb-workspace-section"><p class="tb-card-kicker">FINAL DELIVERY</p><h2>Mixes, Masters & Deliverables</h2><?php if($delivery):?><p class="tb-preline"><?php echo nl2br(esc_html($delivery));?></p><?php endif;?>
<?php if($delivery_files):?><div class="tb-delivery-list"><?php foreach($delivery_files as $file):?><a href="<?php echo esc_url(tuff_beatz_vault_download_url($request_id,$file['id']));?>"><span><?php echo esc_html(strtoupper($file['version']?:'PRIVATE DELIVERY'));?></span><strong><?php echo esc_html($file['name']);?></strong><b><?php echo esc_html(tuff_beatz_vault_human_size($file['size']??0));?> • Download ↓</b></a><?php endforeach;?></div><?php endif;?>
<?php if($final_links):?><div class="tb-delivery-list"><?php foreach($final_links as $link):$safe=esc_url($link);if(!$safe)continue;?><a href="<?php echo $safe;?>" target="_blank" rel="noopener"><span>EXTERNAL DELIVERY</span><strong><?php echo esc_html($link);?></strong><b>Open ↗</b></a><?php endforeach;?></div><?php endif;?>
<?php if(!$delivery_files&&!$final_links):?><p class="tb-empty-state">Final mixes, masters and approved deliverables will appear here when the project reaches delivery.</p><?php endif;?></section>
</div><aside class="tb-dashboard-side"><article class="tb-portal-card"><p class="tb-card-kicker">PROJECT SNAPSHOT</p><h3><?php echo esc_html($post->post_title);?></h3><div class="tb-side-meta"><span>Submitted <b><?php echo esc_html(get_the_date('M j, Y',$request_id));?></b></span><span>Budget <b><?php echo esc_html(get_post_meta($request_id,'_tb_request_budget',true)?:'Need a quote');?></b></span><span>Private Files <b><?php echo esc_html(count($vault));?></b></span><span>Messages <b><?php echo esc_html(count($messages));?></b></span></div></article><article class="tb-portal-card"><p class="tb-card-kicker">SECURITY</p><p>Private-vault files are delivered through authenticated WordPress download requests instead of public media URLs.</p></article><article class="tb-portal-card"><p class="tb-card-kicker">WORKSPACE RULE</p><p>Keep files, revision notes, approvals and project communication attached to this project so the full production history stays organized in one place.</p></article></aside></div></div></section></main><?php get_footer(); ?>