<?php /** Template Name: Client Portal */
if(!defined('ABSPATH'))exit;
if(!is_user_logged_in()){wp_safe_redirect(wp_login_url(home_url('/client-portal/')));exit;}
if(tuff_beatz_is_producer_user()){wp_safe_redirect(home_url('/producer-portal/'));exit;}
$u=wp_get_current_user();$projects=tuff_beatz_client_projects($u->ID);$uid=$u->ID;
$active=0;$completed=0;$unread=0;$unread_messages=0;$next_deadline=null;$latest_update=null;$latest_project=$projects?reset($projects):null;
foreach($projects as $p){$id=$p->ID;$s=get_post_meta($id,'_tb_request_status',true)?:'new';if($s==='completed')$completed++;elseif($s!=='declined')$active++;$unread_messages+=function_exists('tuff_beatz_conversation_unread')?tuff_beatz_conversation_unread($id,$uid):0;
 if(function_exists('tuff_beatz_notifications')){foreach(tuff_beatz_notifications($id) as $n){$read=array_map('intval',(array)($n['read_by']??array()));if(!in_array($uid,$read,true))$unread++;$t=strtotime($n['time']??'');if($t&&(!$latest_update||$t>$latest_update['ts']))$latest_update=array('ts'=>$t,'project'=>$p,'item'=>$n);}}
 if(function_exists('tuff_beatz_project_milestones')){foreach(tuff_beatz_project_milestones($id) as $m){$due=$m['due_date']??'';if($due&&($m['status']??'')!=='completed'){$ts=strtotime($due.' 23:59:59');if($ts&&$ts>=current_time('timestamp')&&(!$next_deadline||$ts<$next_deadline['ts']))$next_deadline=array('ts'=>$ts,'project'=>$p,'milestone'=>$m);}}}
}
get_header();?>
<main class="tb-hub tb-client-v2">
<section class="tb-client-hero"><div class="container tb-client-hero-grid"><div class="tb-client-hero-copy"><p class="eyebrow">TUFF BEATZ • PRIVATE CLIENT EXPERIENCE</p><h1>Your Sound.<br>Your Workspace.</h1><p>Welcome back, <strong><?php echo esc_html($u->display_name);?></strong>. Follow every project from intake to final delivery without losing the creative flow.</p><div class="tb-hub-actions"><a class="btn btn-gold" href="<?php echo esc_url(home_url('/start-a-project/'));?>">+ Start New Project</a><?php if($latest_project):?><a class="btn btn-outline" href="<?php echo esc_url(tuff_beatz_project_dashboard_url($latest_project->ID));?>">Open Latest Workspace</a><?php endif;?></div></div>
<aside class="tb-client-pulse"><div class="tb-client-pulse-top"><span><i></i> PROJECT PULSE</span><small><?php echo esc_html(wp_date('M j, Y'));?></small></div><strong><?php echo esc_html($active);?></strong><p>active project<?php echo $active===1?'':'s';?></p><div class="tb-client-pulse-grid"><div><small>Unread Messages</small><b class="<?php echo $unread_messages?'has-unread':'';?>"><?php echo esc_html($unread_messages);?></b></div><div><small>Unread Updates</small><b><?php echo esc_html($unread);?></b></div><div><small>Completed</small><b><?php echo esc_html($completed);?></b></div><div><small>Total Projects</small><b><?php echo esc_html(count($projects));?></b></div></div><?php if($next_deadline):?><a class="tb-client-deadline" href="<?php echo esc_url(tuff_beatz_project_dashboard_url($next_deadline['project']->ID).'#timeline');?>"><span>NEXT MILESTONE</span><b><?php echo esc_html($next_deadline['milestone']['title']);?></b><em><?php echo esc_html(wp_date('M j, Y',$next_deadline['ts']));?> →</em></a><?php elseif($latest_update):?><a class="tb-client-deadline" href="<?php echo esc_url(tuff_beatz_project_dashboard_url($latest_update['project']->ID).'#notifications');?>"><span>LATEST UPDATE</span><b><?php echo esc_html($latest_update['item']['title']??'Project Update');?></b><em>View update →</em></a><?php endif;?></aside></div></section>
<section class="section tb-client-overview"><div class="container"><div class="tb-client-section-head"><div><p class="tb-card-kicker">MY CREATIVE WORLD</p><h2>Project Portfolio</h2></div><span><?php echo esc_html(count($projects));?> TOTAL</span></div>
<?php if($projects):?><div class="tb-client-projects"><?php foreach($projects as $index=>$p):$id=$p->ID;$status=get_post_meta($id,'_tb_request_status',true)?:'new';$service=get_post_meta($id,'_tb_request_service',true);$progress=tuff_beatz_project_progress_percent($id);$services=tuff_beatz_services();$pay=get_post_meta($id,'_tb_request_payment_status',true)?:'Not invoiced';$notif=0;if(function_exists('tuff_beatz_notifications'))foreach(tuff_beatz_notifications($id) as $n)if(!in_array($uid,array_map('intval',(array)($n['read_by']??array())),true))$notif++;$msg_unread=function_exists('tuff_beatz_conversation_unread')?tuff_beatz_conversation_unread($id,$uid):0;?><article class="tb-client-project <?php echo $index===0?'is-featured':'';?><?php echo $msg_unread?' has-unread-messages':'';?>"><div class="tb-client-project-main"><div class="tb-client-project-head"><span class="tb-status tb-status--<?php echo esc_attr($status);?>"><?php echo esc_html(tuff_beatz_request_status_label($status));?></span><small>PROJECT #<?php echo esc_html($id);?></small></div><h3><?php echo esc_html($p->post_title);?><?php if($msg_unread):?><a class="tb-client-message-badge" href="<?php echo esc_url(tuff_beatz_project_dashboard_url($id).'#messages');?>" aria-label="<?php echo esc_attr($msg_unread.' unread messages');?>">✉ <?php echo esc_html($msg_unread);?> unread</a><?php endif;?></h3><p><?php echo esc_html($services[$service]??$service);?></p><div class="tb-client-project-meta"><span><small>PROGRESS</small><b><?php echo esc_html($progress);?>%</b></span><span><small>PAYMENT</small><b><?php echo esc_html($pay);?></b></span><span><small>UPDATES</small><b><?php echo esc_html($notif);?> unread</b></span><span class="tb-client-message-meta"><small>MESSAGES</small><b><?php echo esc_html($msg_unread);?> unread</b></span></div></div><div class="tb-client-project-progress"><div class="tb-client-progress-ring" style="--p:<?php echo esc_attr($progress);?>"><span><?php echo esc_html($progress);?>%</span></div><a class="btn btn-gold" href="<?php echo esc_url(tuff_beatz_project_dashboard_url($id));?>">Enter Workspace →</a></div></article><?php endforeach;?></div><?php else:?><div class="tb-empty-hub tb-client-empty"><p class="tb-card-kicker">YOUR FIRST PROJECT STARTS HERE</p><h3>Build something unforgettable.</h3><p>Send your brief, upload your music, and your private TUFF BEATZ workspace will be created automatically.</p><a class="btn btn-gold" href="<?php echo esc_url(home_url('/start-a-project/'));?>">Start a Project</a></div><?php endif;?>
<div class="tb-client-assurance"><div><small>PRIVATE ACCESS</small><strong>Your project workspace is permission-controlled.</strong></div><div><small>ONE PLACE</small><strong>Files, reviews, messages, contracts and delivery stay together.</strong></div><div><small>DIRECT CONNECTION</small><strong>Project updates flow directly between you and TUFF BEATZ.</strong></div></div>
</div></section></main><?php get_footer();?>